### ISSUE TITLE
Labels.Serialize() crashes on 4.9.4.0 or higher

### ISSUE THREAD

**Issue by HollidayHT** [MapWindow/MapWinGIS#1]
After installing MapWinGIS 4.9.4.0 or 4.9.4.2 the Labels.Serialize() function give a AccessViolationExpection error:

An unhandled exception of type 'System.AccessViolationException' occurred

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

This code executes as expected in 4.3.9.5 but fails on later releases.

 sf = pMapImage.AxMap1.get_Shapefile(iHandle)
 Dim xmlLabelInfo As String = sf.Labels.Serialize()

**Comment by pmeems** [comment]
I can't reproduce this. I use this piece of code:
var sf = new ShapefileClass();
if (!sf.Open(@"D:\dev\GIS-Data\Vector\Shapefiles\roads.shp"))
{
    Debug.WriteLine(DateTime.Now + " Could not open shapefile. Reason " + sf.ErrorMsg[sf.LastErrorCode]);
    return;
}

if (sf.Labels.Count == 0)
{
    sf.GenerateLabels(1, tkLabelPositioning.lpCenter, true);
}

Debug.WriteLine(sf.Labels.Serialize());

// Add shapefile to map:
var hndl = axMap1.AddLayer(sf, true);

// Get shapefile from map:
var sf2 = axMap1.get_Shapefile(hndl);
Debug.WriteLine(sf2.Labels.Serialize());

Do you have this issue with all your shapefiles or with just one (or a few).
Can you share your data?

**Comment by HollidayHT** [comment]
Thanks for the response, I have attached one of the shapefiles that had the issue.

**Comment by HollidayHT** [comment]
This issue was caused by using the MWLite.Symbology.dll to generate the labels. The resolution was to manually build the labels.
