### ISSUE TITLE
Find leght from start of shape

### ISSUE THREAD

**Issue by bouvin87** [MapWindow/MapWinGIS#10]
I have a mousclickevent to find a shape (POLYLINE). I can find the shape and get the minX and minY (point(0).x and point(0).y).

Now i whant to calculate the lengt of the shape until where my mouseclick is (e.x and e.y).

How can this be done?

**Comment by timkolesa** [comment]
I assume you mean distance, so the simple answer is SQRT( (x1-x2)^2 + (y1-y2)^2 ) but this does not account for curvature of earth so the margin of error increases as the distance calculated increases.

**Comment by timkolesa** [comment]
Disregard the comment above as you will be working with lat/lon coordinates. Much more complex. See http://www.movable-type.co.uk/scripts/latlong.html

**Comment by bouvin87** [comment]
Using 2D plane map. 
I figured out how to find the closest point in the shape using caluclation of distance between my click and all given points in the shape. 

Now the problem is to find if that point is the correct one to calculate distance from.
My shape can have 10 points.

A = Point 3 in shape
C = Mouseclick

Closest point to C is A. But if C is located somewere inbetween point 2 and point 3 i need to know distance to point 2 instead of distance to point 3.

But if C is somewere inbetween point 3 and point 4 the distance shuld be from point 3 to C.

**Comment by timkolesa** [comment]
If your shape can have up to only 10 points, I would just test each point to determine the closest one. You would not have to calculate the distance using the affine equation to determine the closest one. Just use the simple distance formula to find the closest one, then use the affine equation to calculate the actual distance.

Hope this helps you

**Comment by bouvin87** [comment]
But i dont always need the closest point. See example in image.
https://s28.postimg.org/93ob0d0a5/Untitled_1.jpg

**Comment by gpsfishing** [comment]
On 2/8/2017 1:01 PM, bouvin87 wrote:
> But i dont always need the closest point. See example in image.
> [http://imgur.com/a/okL38](url)
>
Now I understand. You need to find the two closest points to the user 
click and calculate the distance between them.

First find the two closest points using the simple distance formula, 
then use the affine formula to calculate the distance between those two 
points.

**Comment by timkolesa** [comment]
Instead of the affine formula I refered you to, there is a function in 
the utils class which will calculate the distance for you:

Utils.GeodesicDistance 
<http://www.mapwindow.org/documentation/mapwingis4.9/class_utils.html#a3195c2d8ac666af75fc50629547145f2>(lat1,lng1,lat2,lng2)

*Returns:*
    Geodesic distance between 2 points in meters.

**Comment by pmeems** [comment]
Did you have a look at Shape.ClosestPoints: http://www.mapwindow.org/documentation/mapwingis4.9/class_shape.html#a50fb5435d697e3e59d31131d9e65c5e0
or Shapefile.GetClosestVertex: http://www.mapwindow.org/documentation/mapwingis4.9/group__shapefile__selection.html#ga43e6c5f88c8a0b1a01239b02acc8fa77
