### ISSUE TITLE
MouseDown and MouseMove event

### ISSUE THREAD

**Issue by paygate591** [MapWindow/MapWinGIS#100]
I use AxMap control in 2 different forms. MouseMove event to update statustrip, and MouseDown to get location. But in the first form, It works well, and on second, It doesn't work...
My mouse move around the map, but my statusbar isn't update.
![image](https://user-images.githubusercontent.com/8900495/40222418-9bdec414-5aa9-11e8-9f8c-b095953d5e68.png)
set for MouseMove and MouseDown event
![image](https://user-images.githubusercontent.com/8900495/40222440-b1d15fc0-5aa9-11e8-808e-f03c0b64fa6d.png)
and my code below
![image](https://user-images.githubusercontent.com/8900495/40222491-dae7c9c6-5aa9-11e8-98e6-67ed4ba4d31a.png)

**Comment by jerryfaust** [comment]
Can you tell us what isn't working?
Are you getting the event?  getting the point?  getting the formatted string?
Is is possible you just need a `toolStripStatusLabel1.Refresh()` call?

**Comment by paygate591** [comment]
MouseMove and MouseDown aren't working in this form. My code included MouseMove and MouseDown event, but seem that code doesn't work

![image](https://user-images.githubusercontent.com/8900495/40263684-5643e7d0-5b40-11e8-87b4-cd1c5f236bbb.png)

MouseDown event in my code, if it works, messenger box will show... but

https://youtu.be/H43bnJsgnyc

**Comment by jerryfaust** [comment]
Ok.  It's likely because you have to enable the MouseDown event.  Check out these properties.

```
bool AxMap.SendMouseDown
bool AxMap.SendMouseMove
bool AxMap.SendMouseUp
```
I believe the reason these properties exist (and default to false) is because there is default mouse behavior built into the Editing tools, and if you want to provide custom mouse behavior, you enable the mouse events.

**Comment by paygate591** [comment]
Oh, I see. Thank you a lot.
