### ISSUE TITLE
Using Prefetch for offline use

### ISSUE THREAD

**Issue by olofk48** [MapWindow/MapWinGIS#103]
I am using MapWingIs in a Project. Sometimes I need to work offline, and I have tried to use the Prefetch routine in the following way (this is old VB6 code, but the same result with VB.NET):

```
'saving cache
Dim a As tkCacheType
Dim a As Long, b As tkTileProvider, c As IStopExecution
a = 1
Form3.Map1.Tiles.DiskCacheFilename = "C:\cash\olle.db3"
Form3.Map1.Tiles.MaxCacheSize(a) = 12000
Form3.Map1.Tiles.DoCaching(a) = True
a = Form3.Map1.Tiles.Prefetch(56,58, 216,18, 17, b, c)
 
and using cache offline

Dim a As tkCacheType
a = 1
Form3.Map1.Tiles.UseCache(a) = True
Form3.Map1.Tiles.DiskCacheFilename = "C:\cash\olle.db3"
Form3.Map1.Tiles.MaxCacheSize(a) = 12000
```

It works, but the whole area is not transferred, it stops prematurely. There are missing areas and "holes" in the cached area.

Is it supposed to work in this way, or is it more complicated with use of some server? Is something missing?
Thanks in advance
Olof

**Comment by pmeems** [comment]
When you are done prefetching, what is the size of `olle.db3`?
Is it close to the `MaxCacheSize`?

**Comment by olofk48** [comment]
No, it is far from the max cache size. I would like to use the Callback    
Function, but I cannot see it from my programming environvent, I only see the Tiles subclass.

Also sent by email

**Comment by zontick** [comment]
Prefetch(56,58, 216,18, 17, b, c)
Your latMin param bigger then latMax param.
may bee you mean (56,58, 16,18, 17, b, c) 
I had the same problem and ran the function 2-3 times to get all the tiles. in this area the number of tiles is more than 500,000 and the procedure for checking their existence in the database is long. And when tiles over 1,000,000 are getting long the procedure for getting these tiles by UseCache.
Install MS4W and use PrefetchToFolder save and get tiles will be much faster.

**Comment by olofk48** [comment]
Thank you for this advise, and yes it was a misprint. 

What you mean is that the more tiles you download, the longer time it will take to fetch and display a certain tile?

**Comment by zontick** [comment]
yes extraction of tiles from sqlite slow with a large number of tiles.

**Comment by pmeems** [comment]
Hi Zontick,

Can you elaborate a bit more on the PrefetchToFolder function in MS4W? Is it just a single command?
If it uses GDAL we could try to incorporate it in MapWinGIS as well.

**Comment by zontick** [comment]
I think you misunderstood me. For save tiles I use PrefetchToFolder in mapwingis based application. But for get tiles on several machines I need MS4W.  But even if you only use saved tiles locally, is this possible get tiles without a web server?

**Comment by pmeems** [comment]
You need a webserver to get the tiles from, but when you have the tiles you don't need to tiles nor a internet connection.
I've used it on a laptop outdoors without a remote connection.
First I downloaded the tiles in the office and later I can use the tiles in the field.

I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
