### ISSUE TITLE
None "English" regional setting - shapefile issue

### ISSUE THREAD

**Issue by rossmclean** [MapWindow/MapWinGIS#105]
Hi all. 
I have a problem. :-)

I create a shapefile, to display locations on top of anoher maps. When regional setting are UK/English, US etc it works as expected. 
When set to, in this case Serbian, the points dont display on the map... 
Is there a simple solution? 

My assumption is that it is somthing to do with MapWinGIS and how it interacts with the regional settings, as up to the point when i add the ponit to a shape, and add that shape to the shape file everything looks the same in both regional settings instances... 
Thanks
Ross

**Comment by pmeems** [comment]
How are you adding the points? It might be related to dot vs comma.
Can you show some code?

**Comment by rossmclean** [comment]
Hi. 
Sorry for late reply. 

I will provide some code, and more background. 

I collected the lat longs from Excel. They are passed back to my code as strings - as confirmed in the debug window. This works the same in all conditions. The lat long strings are then passed to a function to create a x/y which is a compatbale with the web map (function below) - I belive this is a also the same - I will doubble check soon. 
After this, I creat the shape file, code below. 
As I said before, it all works with UK setttings, but not when i which to serbian. I create the shape file in memory - so i will try and save it to disk and take alook at the 2 out puts to confirm my hunch. 

Thanks for any support, really appreciate it. 

I've dumped the whole lot here, sorry if thats bad form, I thought it would be the best option...

```
 Code removed by poster... 
   
```















Lat Long to WebMercator Function
```
Public Function ToWebMercator(ByVal x As Double, ByVal Y As Double) As Boolean
        Dim Num As Double
        Num = x * 0.0174532925199433
        Dim Num2 As Double
        Num2 = 6378137.0# * Num
        Dim a As Double
        a = Y * 0.0174532925199433
        x = Num2
        Y = 3189068.5 * Math.Log((1.0# + Math.Sin(a)) / (1.0# - Math.Sin(a)))
        ToWebMercator_X = x
        ToWebMercator_Y = Y

    End Function
```

**Comment by rossmclean** [comment]
OK, I see the issue, sorry... 
:-((((

Ross

**Comment by rossmclean** [comment]
OK, sorry i was doing an implicit converson from string to dbl, and it was going wrong there.. 
Sorry I should ahve debugged more my self. 

Ross

**Comment by rossmclean** [comment]
FYI, 
I updated the function to this, which fixed the issue. 

```
 Public Function ToWebMercator(ByVal x As String, ByVal Y As String) As Boolean
        Dim xD As Double
        Dim yD As Double

        ''This converts the stings to decimal, with out the local regioal setting getting in the way...
        xD = System.Convert.ToDouble(x, CultureInfo.InvariantCulture)
        yD = System.Convert.ToDouble(Y, CultureInfo.InvariantCulture)
       
        Dim Num As Double
        Num = xD * 0.0174532925199433
        Dim Num2 As Double
        Num2 = 6378137.0# * Num
        Dim a As Double
        a = yD * 0.0174532925199433
        xD = Num2
        yD = 3189068.5 * Math.Log((1.0# + Math.Sin(a)) / (1.0# - Math.Sin(a)))
        ToWebMercator_X = xD
        ToWebMercator_Y = yD

    End Function

```
