### ISSUE TITLE
MWLite usage

### ISSUE THREAD

**Issue by krvax** [MapWindow/MapWinGIS#106]
#Hi everyone,

I'm currently working on a C# project which involves MapWinGIS and some MWLite functions. 

I have some problems including the MWLite Librarys. I've searched for documentation but had no success.

I appreciate your kind help.

Environment:
Windows 10 
Visual Studio 2017
MapWinGIS 4.9

Miguel

**Comment by pmeems** [comment]
MWLite was just a showcase/pre-release of MapWindow5.
Nobody is working on it anymore and it has no documentation.

Can't you use MapWindow5 and create a plug-in?

What tasks do you want to do?

**Comment by krvax** [comment]
MWLite was used as the core of some functions like LegendControls ( `using MWLite.Symbology.LegendControl;` )

Should I search in the MapWindows5 source code?

**Comment by pmeems** [comment]
You can download the source code for MWLite as well:
https://github.com/MapWindow/MapWinGIS/tree/master/demo
And have a look how it was done what you need. 
So you can re-use the code in your own application.

I always encourage developers to **not** make a custom application using MapWinGIS and duplicate a lot of functionality that MapWindow5 (MW5) already provides but to create a plug-in for MW5.
Then you only need to create your specific functionality and let the user use all the functionality of MW5 without the need for you to rewrite any code for it.
We have a template plug-in you can use to get started.

**Comment by krvax** [comment]
Thanks, I'll look the way it's done and then create a plugin with my needs. I appreciate your kind help.
