### ISSUE TITLE
OGR PostGIS layers: Index Out of Bounds

### ISSUE THREAD

**Issue by palmerj** [MapWindow/MapWinGIS#107]
Hi All,

I'm trying to load a PostGIS dataset via the `AddLayerFromDatabase` method e.g 

```
map.AddLayerFromDatabase.(conn, "SELECT * FROM nz_primary_parcels_nztm", true)
```

However the result doesn't display if I have a large number of features that need to be fetched to the map viewport. 

I've tracked this down to the following hard coded setting of ogrLayerMaxFeatureCount being 50,000: https://github.com/MapWindow/MapWinGIS/blob/d5c72793e1df94e94699e6299ce70913677fa6b2/src/Control/GlobalSettingsInfo.h#L137

Can we make this configurable?

**Comment by pmeems** [comment]
It is already configurable but getting more than 50,000 features at once is normally not a good practice.
Look at the Global Settings class: https://www.mapwindow.org/documentation/mapwingis4.9/class_global_settings.html#ad55425992f2e70a6fda68a5ddaf630d7

`new GlobalSettings() { ogrLayerMaxFeatureCount = 60000 };`

**Comment by palmerj** [comment]
Thanks. Can this be done via the OLE/COM interface? I'm using Powerbuilder and a OLE control

**Comment by palmerj** [comment]
> but getting more than 50,000 features at once is normally not a good practice.

Could be a good idea to raise a user message or control event that this has occurred.

**Comment by pmeems** [comment]
The ogr driver is setting a max. of 50,000 features. It does not know how many features are available.
In your code you could do a 'Select count ...' first to get the number of features.

I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
