### ISSUE TITLE
Polygons layers with LineWidth="1.0" do not display

### ISSUE THREAD

**Issue by palmerj** [MapWindow/MapWinGIS#108]
I have a large layer of parcel polygons that won't display when the fill style is off unless set the outline line width is set to something greater than 1.0.  e.g 1.1.

The data I'm using here: https://www.dropbox.com/s/qxqhfsu0n6f2wsb/nz_primary_parcels.zip?dl=1

**Comment by jerryfaust** [comment]
I have seen this behavior as well; I will need to review it.

**Comment by pmeems** [comment]
I have created https://mapwindow.atlassian.net/browse/MWGIS-122 for this.

**Comment by jerryfaust** [comment]
The fix for this has been pushed to the 'develop' branch.

**Comment by palmerj** [comment]
Thanks @jerryfaust. I only have VS 2017 installed. Do you think it will build in that?

**Comment by pmeems** [comment]
This fix is in v5.0 and further.

I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
