### ISSUE TITLE
Is map.LoadLayerOptions working?

### ISSUE THREAD

**Issue by palmerj** [MapWindow/MapWinGIS#109]
I have a PostgreSQL layer successfully loaded into the OLE map control but can't load the style data stored from the `mw_styles` database table. The table exists and has a style record. I have turned on PostgreSQL statement logging and no mw_styles select SQL statement is being run. 

My Powerbuilder(!) code looks like this:

```
li_handle  = ole_mapwindow.Object.AddLayerFromDatabase(ls_conn, "SELECT * FROM nz_primary_parcels_nztm limit 500", true)

ole_mapwindow.Object.LoadLayerOptions(li_handle, "nz_primary_parcels_nztm", "")
```
But `LoadLayerOptions` returns false. 

Thanks.

**Comment by pmeems** [comment]
I've created https://mapwindow.atlassian.net/browse/MWGIS-124.

I need to look into this.

**Comment by palmerj** [comment]
Thanks for taking a look.

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWinGIS/releases) could you create a new issue?
For now, I close this old issue.
