### ISSUE TITLE
Cannot Install Into Delphi XE7

### ISSUE THREAD

**Issue by CharlieHeaps** [MapWindow/MapWinGIS#11]
I would like to try out MapWinGIS in my Delphi Application as a replacement for ESRI MapObjects which is no longer supported (and is only 32 bit). I need a system that can be embedded in a 32 and 64 bit Windows application. MapWinGIS seems to fit the bill in theory, but I am unable to get it installed properly into Delphi (I am using Delphi XE7). I have installed MapWinGIS OK into Windows 7 (4.9.4.2) but when I try to use the Delphi Import Component/Import ActiveX Control and then Add the MapWinGIS.ocx component I see this error message. 

Error Loading Type Library/DLL (80029C)

A similar problem has been logged here: http://qc.embarcadero.com/wc/qcmain.aspx?d=103653
Does anyone have any suggestions on how to get MapWinGIS properly working with Delphi?
Thanks in advance!

**Comment by MasterLi** [comment]
I have the same problem under Delphi 7. I get an error - The entry point to the procedure InitializeConditionVariable was not found.

**Comment by pmeems** [comment]
@MasterLi Are you also running the latest version of MapWinGIS (v4.9.4)? On which version of Windows are you. What Delphi tool are you using?
I'm working on this with @CharlieHeaps when we made some progress we will let you know.

**Comment by MasterLi** [comment]
I'm using Windows XP SP3, many more users are working on it. I managed to import version 4.9.3.5 without errors, all versions above this issue an error when importing into Delphi.

**Comment by BrendanM-RSA** [comment]
Hi did you manage to get v4.9.4.2 running on XP SP3? I cannot get the OCX registered in this OS. V4.9.3.5 works fine. Not sure what else to try. I have made sure VC++ 2013 is installed and so is .NET 4

**Comment by pmeems** [comment]
Can you check with dependency walker which files (if any) are missing on your pc?

**Comment by BrendanM-RSA** [comment]
Hi Paul. Yes I have tried dependency walker but I am not exactly confident in its output. So yesterday I took the plunge and built a new development environment in Win 7 for our legacy application. I was able to install V4.9.4.2 and the application appears to be OK except DrawLabel - that seems to hang the application. I see someone else has raised this before but your workaround does not solve it for me. I will dig a little deeper and revert

Call Map1.DrawLabel(Label, -Lon - 180 / Cells, Lat + 0.25, 0)

**Comment by pmeems** [comment]
Can you show some code with the DrawLabel that is not working for you? If possible with the data that you already loaded? I will check if this is still a problem with the current development version.

**Comment by BrendanM-RSA** [comment]
I posted it on https://github.com/MapWindow/MapWinGIS/issues/39

**Comment by pmeems** [comment]
I'm closing this question because the original question is more or less solved.
Off-list Charlie and I have been working on this and the new installer ships with a Delphi tab file.
