### ISSUE TITLE
Layer Control

### ISSUE THREAD

**Issue by palmerj** [MapWindow/MapWinGIS#110]
I'm scoping out using the ActiveX OLE control for a Powerbuilder project. I see at the moment there is no layer control with the ActiveX OLE control which would be very good to have. Other users would need write one in their development platform which interfaces with the MapWindow control. The functionality needs in this additional control is:

* View layer list with symbology for layer
* Toggle the layer on or off
* Toggle labels on or off.
* Layer groups.

Is there any interest in this?

**Comment by pmeems** [comment]
Hi Jeremy,

Adding a layer control to the ActiveX control might be very useful for developers using MapWinGIS in their own application.
We do have an extensive layer control in MapWindow5, written in C#.

Do you mean you can make this layer control in C++ and add it to MapWinGIS?
If so, please do. Make a pull request and we will merge your code.
Do start with the code in the developer branch. It has recently been upgraded from VS2013 to VS2015.

**Comment by palmerj** [comment]
> Do you mean you can make this layer control in C++ and add it to MapWinGIS?

No make it part of the OCX control and then allow it to be added to other development projects that support ActiveX controls.

> If so, please do. Make a pull request and we will merge your code.
Do start with the code in the developer branch. It has recently been upgraded from VS2013 to VS2015.

Ok thanks.

**Comment by pmeems** [comment]
I created https://mapwindow.atlassian.net/browse/MWGIS-157 for this, so we don't forget.
