### ISSUE TITLE
Unable to Rotate Point Features Placed using Font Files

### ISSUE THREAD

**Issue by Keshannagari** [MapWindow/MapWinGIS#111]
We are using TTF font file to place the symbols as point features. We are unable to rotate the individual symbol because there is a option like 'angle' where we modify it the it is been reflecting for the complete features on the particular layer. So we request you to provide a option where we can update the angle for individual symbol. same as ESRI Environment.

There is and option like Point Feature Ft.Rotate() to rotate individual but it is not working.

**Comment by jerryfaust** [comment]
I will have a look.

**Comment by pmeems** [comment]
I've created https://mapwindow.atlassian.net/browse/MWGIS-123 for this

**Comment by jerryfaust** [comment]
Reviewing outstanding issues, I retested this one, since a number of features have been resolved that were related to the use of GDI+. The following code snippet (in VB.NET) is working, and can be specified within the DefaultDrawingOptions or the DrawingOptions within a Category.

```
With sf.DefaultDrawingOptions
    .PointType = tkPointSymbolType.ptSymbolFontCharacter
    .FontName = "Arial"
    .PointCharacter = 65 'A'
    .PointSize = 24
    .PointRotation = 45
End With

```
