### ISSUE TITLE
PointInShapefile (and related functions) returning incorrect results

### ISSUE THREAD

**Issue by pipzuk** [MapWindow/MapWinGIS#113]
I've seen this error over the years and though it was time it was reported as it's now becoming mission critical. My code is in VBA (Excel) and I'm using data with OSGB projection. If I try and geocode coordinates it usually works fine and returns the correct shapeindex, just occasionally it's wildly wrong - altering the x-y coordinates slightly solves the problem, but a blanket change then causes different coordinate pairs to fail instead.

Here's a shapefile and a spreadsheet with minimal code to illustrate the problem, all the points are definitely in shape index 5 even though the ocx puts most of them in shape 20. To the non-expert eye I'm thinking rounding errors or a test condition slipping through the net. Slightly unrelated is that the whole thing seems to fail if I don't cache the shapefile. I also find that if the coordinates are held in variant variables it fails much more often unless I use cDbl to force it to be a double.

To use: put the shapefile somewhere, edit the Excel cell to say where it is and hit "go", the code will then find out the index for the coordinate and the eight one metre away in all directions. The code is idiotically simple so I'm sure I'm not doing anything wrong. (32 bit Excel, current 32 bit ocx)

[GeocodeBug.zip](https://github.com/MapWindow/MapWinGIS/files/2194272/GeocodeBug.zip)

**Comment by pipzuk** [comment]
[Additional.zip](https://github.com/MapWindow/MapWinGIS/files/2195614/Additional.zip)

Here's a csv list of lots of points that don't seem to work correctly - and an image showing them plotted on the base shapefile - there appears to be something of a pattern!

**Comment by pipzuk** [comment]
Some other pairs that geocode incorrectly - I do observe that the x coordinate doesn't contribute to the problem, any "x" that lies within the base shape will fail with any of the "y" values below...

433012, 437870
433012, 437871
433012, 437872
433012, 437873

It's also interesting to note that precision does figure, a "y" of 437871.5 will geocode correctly. Unfortunately it's not as simple as adding a small decimal offset to each value, some fractional coordinates do fail.

I don't have the skills to figure out what's wrong with the source code but I can offer a kludge to get around the problem. It may be that it only happens for OSGB coordinates, and/or VBA applications but here's a VBA function that returns the correct result - unless the point is right on a shape boundary. Also, of course, this more than doubles the processing time.

```
Function OSGBPointInShapefile(Sf As MapWinGIS.Shapefile, x As Double, y As Double) As Integer
Const DELTA = 1.00000001 'The smaller the better - so long as it does the job!
Dim Results1 As Integer
Dim Results2 As Integer

  Results1 = Sf.PointInShapefile(x, y)
  Results2 = Sf.PointInShapefile(x, (y * DELTA))
  If Results1 <> Results2 Then 'Not the same, bad result so move the y coordinate a tiny bit
    Results1 = Sf.PointInShapefile(x, (y * DELTA))
    Results2 = Sf.PointInShapefile(x, (y * DELTA))
    If Results1 <> Results2 Then
      OSGBPointInShapefile = -2 ' -1 is error code for not found so -2 for error condition
      Exit Function
    End If
  End If
  OSGBPointInShapefile = Results1
End Function
```

**Comment by jerryfaust** [comment]
Hello @pipzuk 

I did a preliminary test using the spreadsheet and data you provided.  Just as a simple alternative, I iterated all shapes, doing a PointInShape test rather than the PointInShapefile test, and every point was found to be in shape 5, as you have indicated they should be.  As a next step, I'll review the differences in the source code between the PointInShape vs the PointInShapefile methods.  I should be able to step through the code so see where it is breaking down.

I've got a few other irons in the fire, so it may be a few days.

Regards.
Jerry.

**Comment by jerryfaust** [comment]
For the record, here's the modified code for the spreadsheet.

```
Private Sub CommandButton1_Click()
Dim sf As New MapWinGIS.Shapefile
Dim i As Integer
  sf.Open [Shapefile]
  sf.BeginPointInShapefile 'doesn't work at all without this
  For i = 1 To [testdata].Rows.Count
    '[testdata].Cells(i, 4) = sf.PointInShapefile([testdata].Cells(i, 1), [testdata].Cells(i, 2))
    For shp = 0 To sf.NumShapes - 1
        If sf.PointInShape(shp, [testdata].Cells(i, 1), [testdata].Cells(i, 2)) Then
            [testdata].Cells(i, 4) = shp
            GoTo NextI
        End If
    Next
NextI:
  Next i
  sf.EndPointInShapefile
  sf.Close
End Sub

```

**Comment by pipzuk** [comment]
Thanks for looking into it for me Jerry, I'm running through 700,000 records which takes 2.5 hours using my "fix" - I'll see how yours fares! (slightly longer - but not by much - and less risky).

I'm wondering if the issue is connected with this?
[https://mapwindow.atlassian.net/browse/MWGIS-118?filter=-4](https://mapwindow.atlassian.net/browse/MWGIS-118)

Cheers

Phil

**Comment by pmeems** [comment]
I see this JIRA issue was created: https://mapwindow.atlassian.net/browse/MWGIS-136
Not sure if it was fixed or not. I have asked Jerry about it.

**Comment by jerryfaust** [comment]
This issue has been resolved by [MWGIS-118](https://mapwindow.atlassian.net/browse/MWGIS-118), and [MWGIS-136](https://mapwindow.atlassian.net/browse/MWGIS-136) will remain open to address further optimizations and standardization of the geometry methods in the library.
