### ISSUE TITLE
Image Visibility

### ISSUE THREAD

**Issue by joe-go12** [MapWindow/MapWinGIS#114]
Hello,
I Added to the map many images, if i have 2 images with the same position and i zoom in to the images , the one with the layer on top stays, and the image with the bottom layer disappears ( visible = false).

how can i make all the all layers always visible??
i tried dynamic visibility but did not work.

**Comment by pmeems** [comment]
Sorry for the late reply.

Can you show me the code you're using to add the images?
It should be possible to have multiple images on top of each other.

**Comment by joe-go12** [comment]
Yes it is possible, i added many images on top of each other, but the problem is that when i zoom in, the images in the bottom becomes invisible, and when i zoom out it appears again.

**Comment by pmeems** [comment]
You might want to look at the DownsamplingMode
https://www.mapwindow.org/documentation/mapwingis4.9/group__image__visualization.html#gad5d85520a27370130f4bf95048f8047f and the UpsamplingMode

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
