### ISSUE TITLE
Shape collisions

### ISSUE THREAD

**Issue by ultraTCS** [MapWindow/MapWinGIS#116]
Hi, I was seeking the means for the API to hide one shape for the case that it touches or intersects with another shape from a different layer.

I know that I can test the intersection quite easily; however, I would then have to apply different drawing options (category) to the shape to hide it.

I was hoping that there was a collision type property for shapes. Does this exist?

Any insight is helpful.

TIA,
LT

**Comment by jerryfaust** [comment]
I'm not aware off hand of a collision detection, but assuming that you have a means of checking for collision when the shape is added or edited, you could do something like the following:
1. add a field to the shape Table, a boolean, something like Collides
2. in the layers DefaultDrawingProperties, set Visible = True
3. add a Category with the Expression "[Collides] = -1" (or True, or VARIANT_TRUE, depending on language)
4. in that same Category, set Visible = False

When you detect collision, set the Collides property to True, and on the next redraw, it should not appear.

Note that I am entering this response from my head.  I've coded similar things, but your solution may vary slightly from what I am suggesting.

Regards.
