### ISSUE TITLE
MapWinGIS does not compile in VS2017

### ISSUE THREAD

**Issue by saadb** [MapWindow/MapWinGIS#118]
I have pulled the develop branch from github 
and added the gdal from GISinternals for VS2017
I have setup the correct VC++ tool set to V141, and upgraded the MApWinGIS project in VS2017

I followed the video for compiling the release/win32
I get the following two errors
Error	C4839	non-standard use of class 'ATL::CA2CAEX<128>' as an argument to a variadic function (compiling source file Tiles\Http\HttpProxyHelper.cpp)	MapWinGIS	c:\dev\projects\mapwingis\support\include\atlhttp\atlperf.inl	2421	
Error	C2248	'ATL::CA2CAEX<128>::CA2CAEX': cannot access private member declared in class 'ATL::CA2CAEX<128>' (compiling source file Tiles\Http\HttpProxyHelper.cpp)	MapWinGIS	c:\dev\projects\mapwingis\support\include\atlhttp\atlperf.inl	2421	

The fix can be done, I think, but I would like to see if the errors I see can be replicated by someone else.

**Comment by jerryfaust** [comment]
Hello @saadb 
MapWinGIS is currently set up to build in VS2015 (see https://mapwindow.atlassian.net/browse/MWGIS-119).

**Comment by saadb** [comment]
I understand that.
I was just curious about seeing if I could use the latest gdal for VS2017 from GISInternals
and testing the idea of using one development studio (2017) community edition

Do you see migrating to VS2017 any time soon?

**Comment by jyyyjy** [comment]
It could b compiled in VS2017, just  use vs2015 sdk, that is vc140, for extra libs, use QGIS 2018's libs.

**Comment by saadb** [comment]
I know that, but it can not compile with vc141, that is the challenge. Why are you referring to QGIS that is a different project.

**Comment by jyyyjy** [comment]
That is a little trick, QGIS includes almost all the requried head files and libs and dlls.

**Comment by pmeems** [comment]
I created https://mapwindow.atlassian.net/browse/MWGIS-156 for this.
The following weeks we will be trying to compile MapWinGIS with VS2017, without any tricks like using the VS2015 SDK ;)

For now I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
