### ISSUE TITLE
DrawLableEx dont work

### ISSUE THREAD

**Issue by bouvin87** [MapWindow/MapWinGIS#12]
Hello. I cant draw labels on my axmap. See codesnippet. The label wont apear on the map.

```
AxMap1.ClearDrawing(recept_punkt_lager)`
recept_punkt_lager = AxMap1.NewDrawing(MapWinGIS.tkDrawReferenceList.dlSpatiallyReferencedList)
Dim e1 As Double = 65000.200
Dim n1 As Double  = 56000.300
AxMap1.DrawLabelEx(recept_punkt_lager, "Test", e1, n1, 0)
```

**Comment by Moesulor** [comment]
Hi bouvin87,
i use a public  sub for labeling features ( i copied the base code once from an introduction (author Daniel P. Ames) and modified it a bit. That one works for me ( I'm passing the shapefile, layerhandle and the fieldnumber where the wished label is form another Sub))
```
Public Sub Labellayer(sf As MapWinGIS.Shapefile, fieldnum As Integer, layerhandle As Integer)
 Dim LabelText As String
 Dim LabelColor As Long
 Dim ShapeNum As Integer
 Dim x As Double
 Dim y As Double
 
 
 Call sf.Labels.Clear
 Call Form_frm_MOtest.Karte1.Redraw
 
 LabelColor = RGB(25, 255, 255)
    For ShapeNum = 0 To sf.NumShapes - 1
      LabelText = sf.CellValue(fieldnum, ShapeNum)
      x = sf.Shape(ShapeNum).Point(0).x
      y = sf.Shape(ShapeNum).Point(0).y
     Call sf.Labels.AddLabel(LabelText, x, y, 0.1, -1)
    Next
    
End Sub
```

**Comment by pmeems** [comment]
@bouvin87: Do you still need help with labeling after @Moesulor his reply?
If not I will close this issue.

**Comment by bouvin87** [comment]
No, i add labels in a shapefile instead. Thanks.

2017-05-18 13:29 GMT+02:00 Paul Meems <notifications@github.com>:

**Comment by pmeems** [comment]
I'm glad it is solved for you.
