### ISSUE TITLE
Can't Install/Import on Delphi

### ISSUE THREAD

**Issue by sergioalejanpro** [MapWindow/MapWinGIS#120]
Hello, I'm trying to install and use the Activex in Delphi (XE4) but there are some errors when installing through the import component wizard:

**_Types of actual and formal var parameters must be identical_**   and   **_Identifier Redeclared: Result_**  

Both errors appears on the following  functions:

```
function TShapefile.SelectShapes
function TShapefile.SelectByShapefile
function TShapefile.FixUpShapes2
function TTable.Query
function TTable.Calculate
function TExpression.Calculate
function TExpression.CalculateForTableRow2
```

I have tried with the last two 32 bit versions (4.9.6.1 and 4.9.5.0) but same result...

**Comment by pmeems** [comment]
We had some issues with Delphi in the past and another Delphi user created an updated .pas file:
https://github.com/MapWindow/MapWinGIS/tree/develop/src/InnoSetup
Could you try that version and let us know?

**Comment by sergioalejanpro** [comment]
Yes, that did the trick... Thanks !!!
