### ISSUE TITLE
Arrows on end on lines? 

### ISSUE THREAD

**Issue by rossmclean** [MapWindow/MapWinGIS#122]
Hi. 
I'm using 
TheMap.DrawLineEx(layer, X1, Y1, X2, Y2, Thinkness, Colour)
to draw line on a drawing layer, is there any way to have an arrow head at the end or mid point of the drawn line? Maybe add a symbol on another layer? 
Ive had a look around but could not see anything....
Thanks
Ross

P.s is there a better place to ask these questions? Seem like this is more of a bug/issue list...

**Comment by jerryfaust** [comment]
Hello @rossmclean 

What you probably need to do is to draw endpoints on the line using a shapefile layer DrawPoint method.  Unfortunately, I don't think you can do it on the maps Drawing Layer (using DrawPointEx), which only draws points as pixels or rectangles.

When using a shapefile layer, you can specify symbols in the [DefaultDrawingOptions](https://www.mapwindow.org/documentation/mapwingis4.9/class_shape_drawing_options.html). You could, for example, use a 'font' type symbol, picking out an appropriate arrowhead from a font.

A couple other notes: As you probably know, each shapefile is a distinct shape type.  So you will have to draw the lines in one layer and the endpoints in another layer.  Secondly, you would have to determine the angle of rotation for the arrowheads, using the angle of the first two points of the line and the last two points of the line.  I'm sorry it's not very straightforward, unless someone else knows an easier way.

Regards.
Jerry.

**Comment by rossmclean** [comment]
Hi @jerryfaust 
Thanks for the reply, and sorry to thanking so long to get back to you. 

What you have suggested is excatly what my thoughts where, so thanks. My mind boggles abit at the angle rotation part of the arrows :-))) best get my trig out!

Many thanks for the support
Ross

**Comment by jerryfaust** [comment]
@rossmclean 

FYI, in the latest 'develop' version of the code (and likely the next release) we've just added a GetAngle function to the Utils class.  You can pass in two point objects (from the point collection of your polyline) and it returns the angle exactly as you need it to specify the Shape.Rotate property.

The points are considered 'from' and 'to' in determining the direction of the arrow, so in your case, you would specify Point(1), Point(0) for the angle of the starting arrow, and Point(numPoints - 2), Point(numPoints - 1) for the angle your ending arrow.

Regards.
Jerry.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
