### ISSUE TITLE
Unable to Open ESRI Basemaps in MapwinGis.

### ISSUE THREAD

**Issue by Keshannagari** [MapWindow/MapWinGIS#123]
Hi all,

I have tried to open the below ESRI base map in MapwinGis using OGR documentation and other ways too but it is unable to open. Please help me how to open ESRI basemaps in MapwinGis.

Basemap URL's :- https://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer 
https://services.arcgisonline.com/arcgis/rest/services 

Kindly do the needful.

**Comment by jerryfaust** [comment]
Here is how I did it.  Note that a recent addition allows you to specify the copyright information, which I just copied from their website for the World_Imagery. And you will need the 'develop' branch to do this, unless you use http only (no https) and omit the copyright.

```
AxMap1.Tiles.Providers.Add(tkTileProvider.ProviderCustom, "ESRI",
   "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{zoom}/{y}/{x}.png",
   tkTileProjection.SphericalMercator, , ,
   "Esri, DigitalGlobe, GeoEye, i-cubed, USDA FSA, USGS, AEX, Getmapping, Aerogrid, IGN, IGP, swisstopo, and the GIS User Community")
AxMap1.Tiles.ProviderId = tkTileProvider.ProviderCustom
AxMap1.Redraw3(tkRedrawType.RedrawSkipAllLayers, True)

```
And you can replace "World_Imagery" in my example with other maps, such as "World_Street_Map", "World_Topo_Map", or "World_Boundaries_and_Places".  **You should verify their copyright and licensing requirements for each of these maps.**

**Comment by Keshannagari** [comment]
@jerryfaust thank you so much it really worked out for me. Once again thank you so much for your timely help.

**Comment by nguyenthetan1995** [comment]
Hello every body! I am student, the firs
[image: image.png]
t times, i build Mapwingis, but i saw some error like this! can you help
me! please

Vào Th 4, 10 thg 10, 2018 vào lúc 16:10 Keshannagari <
notifications@github.com> đã viết:

**Comment by Keshannagari** [comment]
Hi @jerryfaust  i have successfully loaded ESRI base maps into mapwingis map but the problem is in resolutions of the base maps in zoom, While in arc-map we have observed that  based on the zoom they are using different types of World Imagery services(Please find the attached snapshot). So they are getting high resolution images on map.

URL used;- http://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{zoom}/{y}/{x}.png

So how can we use the Low Resolution 15m Imagery , High Resolution 60m Imagery, High Resolution 30m Imagery on our mapwingis.

Please find the attached images for clear information.

**Arc Map Layers**

![world_imagery_layers](https://user-images.githubusercontent.com/34860871/48470584-d0d03d00-e817-11e8-8f84-779fca759d7a.png)

**ArcMap Image Clarity**
 
![arcmapimg](https://user-images.githubusercontent.com/34860871/48470773-57851a00-e818-11e8-87a2-f3d8d9f88a6d.jpg)

MapWinGis Image Clarity
![mapwingisimg](https://user-images.githubusercontent.com/34860871/48470796-6bc91700-e818-11e8-8704-e4ee34063b70.jpg)

**Comment by nguyenthetan1995** [comment]
I see a problem in mapwingis 4.9.6.0  when i open the project *.mwxml .
[image: image.png]
how to fix it

Vào Th 4, 14 thg 11, 2018 vào lúc 15:50 Keshannagari <
notifications@github.com> đã viết:

**Comment by jerryfaust** [comment]
@nguyenthetan1995 
I saw your same comments on the Google+ community.  Please continue to use the Google+ community or create a new GitHub Issue rather than adding your comments to this separate issue #123.  I would like to close this issue.

**Comment by jerryfaust** [comment]
Closing this Issue since the original issue has been resolved.  The follow-on issue, #129 will stay open.
