### ISSUE TITLE
Use in signed application

### ISSUE THREAD

**Issue by AndyCaignie** [MapWindow/MapWinGIS#125]
Is there a possibility to use the AxInterop.MapWinGIS.DLL and Interop.MapWinGIS.DLL in an application that is signed with a strong name key file?
I now get the error "'Could not load file or assembly 'AxInterop.MapWinGIS, Version=4.9.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'"
Unfortunately it is not possible to unsign the application.
I have tried the x86 and x64 version, and both do not work
Thx in advance

**Comment by pmeems** [comment]
I'm not familiar with signing. Googling I found this post with some links: https://social.msdn.microsoft.com/Forums/vstudio/en-US/dc8850cb-7a3d-401b-b6c8-ff498d5ab32b/how-to-add-strong-name-for-a-thirdparty-assembly?forum=csharpgeneral
Does it help you?

**Comment by AndyCaignie** [comment]
Deassemble and then reassemble doesn't work, some classes are missing afterwards

**Comment by jerryfaust** [comment]
Check out this link.  It looks like you could reregister and sign the ocx.
https://stackoverflow.com/questions/796945/should-interop-assemblies-be-signed

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
