### ISSUE TITLE
Drawing Arc

### ISSUE THREAD

**Issue by seepanaraj** [MapWindow/MapWinGIS#126]
Can someone help me to draw an arc using mapwingis?

**Comment by seepanaraj** [comment]
Why nobody is responding to my issue?

**Comment by jerryfaust** [comment]
Hello @seepanaraj 

I'm not sure that I understand what you are asking.

Are you asking if MapWinGIS is able to store a true 'arc' geometry, as in a Bézier Curve?  It cannot.  It will store a polyline geometry as a collection of points.  With enough points, it can simulate a true curve.

Or are you asking about a map tool that is capable of 'drawing' curved lines?

**Comment by seepanaraj** [comment]
How to simulate a true curve?

**Comment by seepanaraj** [comment]
Code to simulate curve using polyline geometry plz

**Comment by pmeems** [comment]
At this moment MapWinGIS cannot draw curves because we internally use the Shapefile object to represent vector data. The shapefile object is not capable of curves.

I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
