### ISSUE TITLE
CQL / ECQL query  on WmsLayer

### ISSUE THREAD

**Issue by krvax** [MapWindow/MapWinGIS#127]
Hi all,

is it possible to add a CQL query as a WmsLayer parameter?

**Comment by pmeems** [comment]
I'm not sure. I haven't tried it. 
Could you try it and let us know? If it doesn't work we can make a feature request.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
