### ISSUE TITLE
Unable to View ESRI basemaps clearly in Mapwingis zoom level

### ISSUE THREAD

**Issue by Keshannagari** [MapWindow/MapWinGIS#129]
#123 

Hi @jerryfaust  i have successfully loaded ESRI base maps into mapwingis map but the problem is in resolutions of the base maps in zoom, While in arc-map we have observed that  based on the zoom they are using different types of World Imagery services(Please find the attached snapshot). So they are getting high resolution images on map.

URL used;- http://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{zoom}/{y}/{x}.png

So how can we use the Low Resolution 15m Imagery , High Resolution 60m Imagery, High Resolution 30m Imagery on our mapwingis.

Please find the attached images for clear information.

**Arc Map Layers**

![world_imagery_layers](https://user-images.githubusercontent.com/34860871/48470584-d0d03d00-e817-11e8-8f84-779fca759d7a.png)

**ArcMap Image Clarity**
 
![arcmapimg](https://user-images.githubusercontent.com/34860871/48470773-57851a00-e818-11e8-87a2-f3d8d9f88a6d.jpg)

MapWinGis Image Clarity
![mapwingisimg](https://user-images.githubusercontent.com/34860871/48470796-6bc91700-e818-11e8-8704-e4ee34063b70.jpg)

**Comment by jerryfaust** [comment]
Hello @Keshannagari 

I've been reviewing this, and I don't yet know why you are experiencing that.  The area-of-interest that I am looking at is getting the same level of detail as the ArcGIS Imagery (both in ArcMap and the Web browser).  Even so, I am not getting the clarity you are getting from ESRI.

One thing to try is specifying the full range of available zoom levels to MapWinGIS.  The ArcGIS website indicates that there are 24 zoom levels available to the World_Imagery, so on the call to Add the Tile Provider, I am specifying the parameters 0 and 23 (for MinZoom and MaxZoom, see the code snippet below).

I doubt it will change anything, but you can try it and see if that helps.  Even after I specify this, as soon as I get to level 20, I no longer get any images, and instead see the "Map data not yet available" tiles.  I'll keep looking further, and if you discover anything, please let me know.

```
AxMap1.Tiles.Providers.Add(tkTileProvider.ProviderCustom, "ESRI",
"https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/{zoom}/{y}/{x}",
tkTileProjection.SphericalMercator, 0, 23,
"Esri, DigitalGlobe, GeoEye, i-cubed, USDA FSA, USGS, AEX, Getmapping, Aerogrid, IGN, IGP, swisstopo, and the GIS User Community")

```

**Comment by Keshannagari** [comment]
@jerryfaust 
Thank you for your quick and helpful response.

**Comment by pmeems** [comment]
This might also be related to the properties [DownsamplingMode](https://www.mapwindow.org/documentation/mapwingis4.9/group__image__visualization.html#gad5d85520a27370130f4bf95048f8047f) and [UpsamplingMode](https://www.mapwindow.org/documentation/mapwingis4.9/group__image__visualization.html#ga85fc9fc8a33691982ff7e7df7bbe21ae) of the Image class.

I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
