### ISSUE TITLE
Image reprojection

### ISSUE THREAD

**Issue by jirigcs** [MapWindow/MapWinGIS#13]
Hi All,

Can MapWinGIS overlay layers with different CRS? I found that I can reproject each vector layer from its original CRS (usually stored in prj file) to some common CRS (ie. "Pseudo-Mercator") before depicting them in my map window. My problem is that I have not found the reprojecting feature for rasters. Does anybody know some algorithm or procedure how to reproject rasters in MapWinGIS?

Thank you,
Jiri

**Comment by pmeems** [comment]
When you look at MapWindow5 (which is using MapWinGIS for its mapping) the user gets prompted when he wants to open any layer with a different projection. The layer will be reprojected on the fly.

When you need this in your own application you can have a look at the source code of MapWindow5.
Perhaps better to rebuild MW5 you should consider writing a plug-in for MW5 instead.
This plug-in only needs to do your custom code and will use the rest of MW5.
We have a template plug-in that will get you up to speed.

**Comment by pmeems** [comment]
Closing this old question.
