### ISSUE TITLE
Tile to Tile mismatch of base maps on shape files.

### ISSUE THREAD

**Issue by Keshannagari** [MapWindow/MapWinGIS#130]
I have some shape files on which i have loaded base maps like Open streets maps or ESRI base maps.
Where i have observed that there is a mismatch in between tile to tile (might be gaps). Please find the projection system of the shape files used and also am attaching the shape file directly.

Projection:- PROJCS["NAD83_Pennsylvania_South_ftUS",GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["standard_parallel_1",40.96666666666667],PARAMETER["standard_parallel_2",39.93333333333333],PARAMETER["latitude_of_origin",39.33333333333334],PARAMETER["central_meridian",-77.75],PARAMETER["false_easting",1968500],PARAMETER["false_northing",0],UNIT["Foot_US",0.30480060960121924]]

Open street maps loading code :-        
axmap1.Tiles.ClearCache(tkCacheType.Disk);
                axmap1.Tiles.UseCache[tkCacheType.Disk] = true;
                axmap1.Tiles.set_DoCaching(tkCacheType.Disk, true);
                axmap1.Tiles.set_MaxCacheSize(tkCacheType.Disk, 100.0);
                axmap1.Tiles.ClearCache(tkCacheType.Disk);
                tkTileProvider objProv = new tkTileProvider();
objProv=tkTileProvider.OpenStreetMap;
axmap1.TileProvider=objProv;
axmap1.Redraw3(tkRedrawType.RedrawSkipAllLayers, true); 

Sample Shape file :- 
[Test_Data.zip](https://github.com/MapWindow/MapWinGIS/files/2599198/Test_Data.zip)

Tile to Tile Mismatch image : 
![openstreetmaps](https://user-images.githubusercontent.com/34860871/48767253-56eaf880-ecdc-11e8-9a5e-c3447abca92b.jpg)

Kindly help me to match the tiles of base maps on provided shape file.

**Comment by pmeems** [comment]
This is expected because the OSM Tiles are in WebMercator and your shapefile is in `NAD83_Pennsylvania_South`. Because you open this shapefile in MWGis the projection of the map is also set to `NAD83_Pennsylvania_South`. The tiles have a different projection and are transformed on the fly.
This transforming causes the misalignment. 
Either use tile server which provides the tiles in the same projection as your shapefile or reproject your shapefile to EPSG:3857

**Comment by Keshannagari** [comment]
@pmeems 
Thanks for the reply. Can we change tile server projection as shape file projection. If yes could you please provide the links or snippet.

**Comment by pmeems** [comment]
Tiles are pre-built so you first need to find a tile server that serves the tiles in your projection.
Here's more about tiles and its projections: https://www.mapwindow.org/documentation/mapwingis4.9/class_tiles.html

When adding a custom tile server you can set the projection the tiles are in. At this moment only two projections (https://www.mapwindow.org/documentation/mapwingis4.9/_enumerations_8cs.html#a24c2cabdbc954f7d542a9c246aff918c) are available: Spherical Mercator (the default) and Amersfoort. We can add your projection as well if you like.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
