### ISSUE TITLE
cmIdentify fail to fire ShapeIdentified event

### ISSUE THREAD

**Issue by XiaoZhong233** [MapWindow/MapWinGIS#131]
hi i am tring to fire ShapeIdentified  by axMap1.CursorMode == tkCursorMode.cmIdentify
i didn;t work
here is my code 

> axMap1.CursorMode == tkCursorMode.cmIdentify
> axMap1.ShapeIdentified += (s, e) =>
>             {
>                 MessageBox.Show("alert");
>             };

**Comment by jerryfaust** [comment]
@XiaoZhong233 
When you add a layer that you want to be identifiable, are you setting the [Shapefile.Identifiable](https://www.mapwindow.org/documentation/mapwingis4.9/class_shapefile.html#ad1d431d9ea3168d398713d40bbb289ff) property?

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
