### ISSUE TITLE
Select by polygon gives incorrect validation error for a triangular selection (i.e. 3 points)

### ISSUE THREAD

**Issue by robhoney** [MapWindow/MapWinGIS#134]
Hi,

I've been trying to use the select by polygon selection mode and have found that it fails when you only choose 3 points (i.e. 3rd point is a Ctrl-click - a triangle). It generates a ShapeValidationFailedEvent, with the message, "Shape contains too few points for specified shape type." (tkNOT_ENOUGH_POINTS_FOR_SHAPE_TYPE) - which is not true of course - a triangle is definitely a poly gon ;).

The problem can be seen in MapWindow 5 too.

Rob H

**Comment by jerryfaust** [comment]
Thank you @robhoney 

I just stepped through that code, and it looks like it's always 1 point behind when the user tries to close the polygon.  I will get a fix checked in for the next release.  If you need it sooner than that, you can watch for the fix and then get/build the latest 'develop' branch.

Regards.
Jerry.

**Comment by jerryfaust** [comment]
I have created Atlassian [Issue MWGIS-138](https://mapwindow.atlassian.net/projects/MWGIS/issues/MWGIS-138) to track the progress.

**Comment by pmeems** [comment]
This should be fixed in the latest version.
Please reopen if it isn't.
