### ISSUE TITLE
MapWinGIS_TLB

### ISSUE THREAD

**Issue by Jymbul** [MapWindow/MapWinGIS#141]
I am having trouble getting the new MapWinGIS inro Delphi XE5.

I have tried bringing in the supplied "MapWinGIS_TLB.pas" file but there are errors highlighted in the code.

I get this:

"_Unit "_MapWinGIS_TLB.pas" references the "Visual Component Library" framework, but the project currently has no framework assigned. Do you want to enable the "Visual Component Library" framework for this project?
(Not enabling the proper framework may require unit scoping, ambiguities, and linkage to framework binaries to be handled manually)
---------------------------
Yes   No   Cancel   
---------------------------_"

I select "_Yes" then I get a compile/build error on the "begin" line in  the following function
"function TShapefile.SelectShapes(const BoundBox: IExtents; Tolerance: Double; 
                                 SelectMode: SelectMode; var result: OleVariant): WordBool;
begin
  Result := DefaultInterface.SelectShapes(BoundBox, Tolerance, SelectMode, result);
end_;_"

I would be very grateful if anyone has an answer to this.

Best regards
James

**Comment by pmeems** [comment]
Hi James,

Can you repost this question on our new forum at https://mapwindow.discourse.group/
I will ask the supplier of the pas-file to have a look at it.

**Comment by Jymbul** [comment]
Hi Paul

Thanks for letting me know.  Certainly will do.

Best regards
James D Nelson

**Comment by pmeems** [comment]
This question is moved to https://mapwindow.discourse.group/t/mapwingis-tlb-pas-problems-with-delphi-xe5/38
