### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by YitianJiang** [MapWindow/MapWinGIS#142]
Can I add a polygon to the map while I can see the map loaded from openstreetmap ?
why these examples  like CreatePolygonShapefile.cs and PolygonsWithHoles.cs **don't have a "map backgound "**?  
I can't see the map, only polygon on the screen.

**Comment by pmeems** [comment]
Yes you can, but then you need to set a projection and select a tile server, like explained  here: https://www.mapwindow.org/documentation/mapwingis4.9/getting_started.html

And can you ask questions at our new forum: https://mapwindow.discourse.group/c/mapwingis

I'm closing this question.
