### ISSUE TITLE
Memory consumption more in Mapwingis 5.0.0.0 while Using Drawing functions.

### ISSUE THREAD

**Issue by Keshannagari** [MapWindow/MapWinGIS#143]
Hi 
First of all Thank you for the latest update MapWinGis v5.0.0.0.
But we have observed that while using latest version in drawing Functionalities like DrawLineEx(), DrawCircleEx(), DrawPolygonEx(), memory consumption is being more. But in MapWinGIS v4.9.6.1 for the same functionalities memory consumption was very much less.
So we have degraded our version back to MapWinGIS v4.9.6.1. 
Kindly rectify the above issue so that we can upgrade back to the latest version MapWinGis v5.0.0.0.

**Comment by pmeems** [comment]
Can you show us some code how you are testing it, so we can reproduce?
Looking at the release notes I don't see any specific changes for the drawing functions:
https://mapwindow.atlassian.net/secure/ReleaseNote.jspa?projectId=10003&version=10400

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
