### ISSUE TITLE
Mapwingis.ocx WinXP

### ISSUE THREAD

**Issue by MOSSMONACO** [MapWindow/MapWinGIS#145]
I believe that ver 4.9.3.5 is the last version that will register on winXP sp3 32 bit.
Does anyone have a link to get that old version...
Thanks in anticipation!

**Comment by paulmeems-waterwatchfoundation** [comment]
No need to ask the same question (https://github.com/MapWindow/MapWinGIS/issues/144) twice.
MapWinGIS v4.9.4.2 (https://github.com/MapWindow/MapWinGIS/releases/tag/v4.9.4.2) is very old and might work on WinXP as well.

Please post new questions on our new forum at https://mapwindow.discourse.group/

**Comment by MOSSMONACO** [comment]
I've tried 4.9.4.2 ....it wont register. I have about 80 pc's running XP so updating to win 10 would be expensive, hence my interest in the older versions.

**Comment by pmeems** [comment]
I just downloaded the codeplex archive and it has some old installers:
https://github.com/MapWindow/MapWinGIS/releases/tag/v4.9.3.6
I will upload more old installers.
