### ISSUE TITLE
UTF-8 Encoded Labels

### ISSUE THREAD

**Issue by ultraTCS** [MapWindow/MapWinGIS#15]
I just posted same query on CodePlex - reposting here as I am unsure if that forum is active. Apologies for duplication.

I see here evidence of unicode support in labels [here](https://mapwindow.atlassian.net/browse/MWGIS-13); however we cannot get them displayed properly on a map.

We would like to know the current support and limitations for UTF-8 encoded labels in MapWinGIS 4.9.4.2.

Thanks in advance.

**Comment by pmeems** [comment]
Do you have a sample data set so I can test?

**Comment by ultraTCS** [comment]
Hello Paul,

Thanks for your quick response.

I’ve attached the shape file _waterways.shp_ (had to append .docx extension to attach). The .png file is what it looks like when we load the shape file into our application. 

The following code is to UTF-8 encode the cell values from  the table of the shape file. After second MultiByteToWideChar  call, the Korean characters are correctly seen when debugging. Passing the encoded text to MapWinGIS::Label PutText(…) doesn’t seem to render properly. We’ve tested MapWindow5 application with same shape file and the MapWindow5 application doesn’t recognize Korean characters either (see second .png attached). 

<code>
     _variant_t cellVal = shapeFile->GetCellValue(realFieldIndex, i);

     _bstr_t bstr = _bstr_t(cellVal);

     int length = MultiByteToWideChar(CP_UTF8, 0, bstr, bstr.length(), NULL, 0);

     std::wstring wstr;

     wstr.resize(length);

     MultiByteToWideChar(CP_UTF8, 0, bstr, bstr.length(), &wstr[0], length);


     if (numLabels >= numShapes && i < numLabels)
     {
        shapeFile->GetLabels()->GetLabel(i, 0)->PutText(wstr.c_str());
        …
     }
</code>

Thanks again.

![map_window_waterways_shp](https://cloud.githubusercontent.com/assets/24417284/24296501/bc146826-1075-11e7-9504-317769d80495.PNG)

![waterways_shp](https://cloud.githubusercontent.com/assets/24417284/24296502/bc16c26a-1075-11e7-9cec-f4b80271b6a1.PNG)

[waterways.shp.docx](https://github.com/MapWindow/MapWinGIS/files/868026/waterways.shp.docx)

**Comment by sleschinski** [comment]
Hi, judging by source code Label.put_Text converts Unicode to ANSI (OLE2CA
macro). So the display most likely will depend on the current Windows code
page (should be Korean as well). Also additional encoding seems to be
unnecessary in this case since GetCellValue returns BSTR wrapped in
Variant, and Label.put_Text expects this same same BSTR. But I can't advice
the proper way to pass it, haven't written in C++ for quite some time.

https://github.com/MapWindow/MapWinGIS/blob/master/src/COM%20classes/LabelClass.cpp

Regards,
Sergey

**Comment by ultraTCS** [comment]
Hi Sergey, thanks for your input.

Code Pages are not a viable option at this time. Are you suggesting that the Labels.put_Text API is such that Unicode is not currently supported?

@pmeems Can you confirm this is the case? Are there alternative options to display the text?

Thanks.

**Comment by pmeems** [comment]
You need to zip your .shp, .shx and .dbf file and attach it.
I can't use just the .shp file.

**Comment by ultraTCS** [comment]
@pmeems sorry about that
[waterways.zip](https://github.com/MapWindow/MapWinGIS/files/868644/waterways.zip)

**Comment by pmeems** [comment]
I've just opened the shapefile in MW5 and I can't display the proper labels either:
![image](https://cloud.githubusercontent.com/assets/12067729/24331791/af7c49ea-123b-11e7-922e-18866e2a94c4.png)
But when I open the .dbf-file in OpenOffice Calc it can't show the text correctly as well:
![image](https://cloud.githubusercontent.com/assets/12067729/24331797/d40099ce-123b-11e7-996d-ed1785863b7a.png)
So it really seems a machine issue, making it very hard to debug and fix.

As Sergey mentioned, in the code Unicode is converted to ANSI which doesn't help either.
At this moment we're short on C++ knowledge in this project. 
Please let me know if you do know how to solve this.

**Comment by ultraTCS** [comment]
Well we are building the ocx from source so I removed the conversion in the put_Text API and it displays the labels with the encoding.

**Comment by pmeems** [comment]
What is the exact change you made?
I replaced
`_label->text = OLE2CA(newVal);`
with 
`_label->text = newVal;`

But I still have these labels:
![image](https://cloud.githubusercontent.com/assets/12067729/24510069/6454a68a-1568-11e7-96de-bc48dd7e6de3.png)

**Comment by ultraTCS** [comment]
Well that is odd Paul, as that is the exact change made to the interface. See my results below.
I will follow up if we see any issues once the update is committed to the team here, as it is only in my development configuration at this time.

![capture](https://cloud.githubusercontent.com/assets/24417284/24512595/fb2c9e22-153c-11e7-9666-46eb0a1bd86a.PNG)

**Comment by pmeems** [comment]
I have no C++ knowledge at all, but it looks like it has to do something with the Windows Code Pages like Sergey suggested.
I'll keep the change for a while and if I don't find other problems I'll keep the change since it looks like to solve part of the problem.

**Comment by ultraTCS** [comment]
Agreed, I don't think this is a long-term solution or even a full solution. Bottom line is it works for us for the moment.

The OLE2CA macro Sergey referenced is used quite frequently in the source; so that is also something to consider.

**Comment by pmeems** [comment]
I've just committed this change since I didn't found any errors.
I'm closing this issue.

**Comment by pmeems** [comment]
I'm working on https://mapwindow.atlassian.net/browse/CORE-199 which is about issues with Russian labels.
I've made some changes showing the labels in proper Russian and the changes also solved this issue with the Korean labels:
![image](https://user-images.githubusercontent.com/12067729/28417925-2afa6592-6d5a-11e7-93ea-b78c5f9cdbd4.png)
