### ISSUE TITLE
Failed to read image buffer!

### ISSUE THREAD

**Issue by zcwbnu** [MapWindow/MapWinGIS#151]
My program reported an error My program reported an error :Failed to read image buffer. I want to  know under what circumstances this error message will appear?

![微信图片_20190325224821](https://user-images.githubusercontent.com/18117662/54929803-18e33700-4f51-11e9-960a-4ac71b3adb5f.jpg)

**Comment by jerryfaust** [comment]
I don't see that specific error message in the source code, although it may be built on-the-fly.  If you could provide some context from your source code, we may be able to narrow it down.

Thank you.

**Comment by pmeems** [comment]
@zcwbnu As requested by Jerry could you post the code and attach the file you are trying to read?

And since this is a question or help request, can you repost on our forum: https://mapwindow.discourse.group/c/mapwingis
