### ISSUE TITLE
Error while building with VS2015 or VS2017

### ISSUE THREAD

**Issue by frank2x460** [MapWindow/MapWinGIS#153]
When compiling on VS 2015 or VS 2017 the following error occurs:

Fehler	C3861	"inserter": Bezeichner wurde nicht gefunden.	MapWinGIS	D:\Apps\MapWinGIS-master\src\Tiles\TileManager.cpp	533	

in English:

Error	C3861	"inserter": identifier not found	MapWinGIS	D:\Apps\MapWinGIS-master\src\Tiles\TileManager.cpp	533	

What to do?

**Comment by jerryfaust** [comment]
I checked the line of code; the 'inserter' is a part of the c++ Standard Library.  So if it cannot be found within either IDE, I wonder if there is something not fully set up or installed on your build machine?

Regards.
Jerry.

**Comment by frank2x460** [comment]
Hello Jerry,

after adding 
 #include <iterator>
in the file "TileManager.cpp"
and using the libs, headers and binaries from
release-1900-gdal-2-3-3-mapserver-7-2-1.zip and
release-1900-gdal-2-3-3-mapserver-7-2-1-libs.zip,
the project compiles properly in VS 2015 as well as in VS 2017!
The output is exact the same as the files in your installer package 5.0.1!
No we can research our problems with the WMS interface.

Thanks for your efforts!

Best Regards,
Frank

**Comment by pmeems** [comment]
I just posted a video showing how you can compile MapWinGIS using VS2017:
https://youtu.be/x1J6xJno9kM
