### ISSUE TITLE
5.0.1 not working 100% with VB6

### ISSUE THREAD

**Issue by BrendanM-RSA** [MapWindow/MapWinGIS#155]
I have been using MapWinGIS for a number of years with Vb6. Decided to upgrade to 5.0.1. On one of my more simpler projects the new MapWinGIS seesm to work but nit 100%.

There are some issues

**To Reproduce**
Create a VB6 project, blank form with Map1 on it. Form code as below:

Private sf1 As New MapWinGIS.Shapefile
Private Sub Form_Load()
  ' sf1 does not show any properties in the VB6 IDE
  Call sf1.CreateNewWithShapeID("", SHP_POLYGON)
  Call Map1.AddLayer(sf1, True)
  
  ' this crashes
  'Map1.Extents = sf1.Extents
End Sub

**Issues**
- In the IDE if you have a breakpoint on the End Sub then sf1 has no properties. Screen grab atatched
![No properties for sf1](https://user-images.githubusercontent.com/32435731/55775232-b170cf80-5a98-11e9-8576-f5b94beb0516.JPG)

- Accessing sf1.extents crashes. Screen grab attached
![Extents crash](https://user-images.githubusercontent.com/32435731/55775237-b33a9300-5a98-11e9-8d13-479f5a0527c7.JPG)

**Desktop (please complete the following information):**
 - OS: Win 7
 - Browser Chrome
 - Version MapWinGIS 5.0.1

**Comment by jerryfaust** [comment]
Hello @BrendanM-RSA 

I'm sorry but I'm not able to reproduce this, coded exactly as you have.
- What service pack is installed for VB (I'm running SP4).
- I presume that you added the Map to the toolbox window, then added it from the toolbox?
- It's actually complaining about the Map extents rather than the Shapefile extents.
- I'm not sure what you mean by 'sf1 does not have any properties in the VB6 IDE'. Are you describing something that was unexpected?

Here's a screen shot after stepping past the Map1.Extents setting.  I'm able to query both the Shapefile extents and the Map extents (don't ask me why they differ - may have something to do with a buffer).

So at the moment, I'm not sure what to think.  Can you try some other operations?  Maybe we can get more clues.
 
![image](https://user-images.githubusercontent.com/30758167/55776802-c0349380-5a52-11e9-8799-c8329095a126.png)

**Comment by BrendanM-RSA** [comment]
Runing VB6 SP6

Map was added to toolbox and then to the form as you said.

sf1 no properties - at your breakpoint at End Sub if you add a Watch to sf1 - then I get no properties listed. As per my original screen grab

Only thing that I can think of is that this PC had the old MapWinGIS on it. I initially ran the 5.0.1 installer on top of it. When I saw the errors I uninstalled 5.0.1 (which cleared c:\dev) and manually cleaned the registry of all MapWinGIS entries. Then re-installed 5.0.1

The map1 object onb my form is shwoing its verison as 5.0.1 so I am happy it has found the OCX

Here is my VB6 project
[Proj.zip](https://github.com/MapWindow/MapWinGIS/files/3057455/Proj.zip)

**Comment by BrendanM-RSA** [comment]
Re-open

**Comment by frank2x460** [comment]
Same or similar Problem here, after update from 4.9.3 but different errormessage:
![grafik](https://user-images.githubusercontent.com/34651007/55870423-d47aac80-5b88-11e9-88ca-6c5125df1615.png)
De-/installation and cleaning registry with no success.
What to do further.

VB6 SP6
Windows 10 PRO (1703)

**Comment by frank2x460** [comment]
Sorry, the "SET" Instruction was wrong, now same errormessage:
![grafik](https://user-images.githubusercontent.com/34651007/55872080-620bcb80-5b8c-11e9-860f-1e4729792e1b.png)
No problems with 4.9.5!

**Comment by BrendanM-RSA** [comment]
If you have a MapWinGIS ShapeFile in VB6 can you see the runtime properties of it when you create a Watch for it in the IDE?

**Comment by frank2x460** [comment]
The extents object shows no properties (xmin,ymin,.....) when creating a watch!

**Comment by BrendanM-RSA** [comment]
Without doing a test we can probably surmise that in the VB6 runtime IDE no object properties can be viewed in the Watch window

**Comment by jerryfaust** [comment]
Hello @BrendanM-RSA , @frank2x460 ,

I'm not sure what's going on.  We have an older app that first moved to MapWinGIS at 4.9.x.  I've recently updated to 5.0.1, still with no problem.  Here's a screenshot just after assigning the Extents.  It does appear that the Watch window, at least the the Extents, is worthless.  At any rate, we'll have to try to figure out what's different...  One thing that comes to mind is that I build MapWinGIS on this machine from the source code (I didn't run the installer).  The COM registration _should_ be identical.  I'll see if I can find a machine that has VB6 that I can run the installer on, to see if that makes the difference...
![image](https://user-images.githubusercontent.com/30758167/55898743-1818ea80-5b78-11e9-8002-8ca56db3ecc9.png)

Regards,
Jerry.

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWinGIS/releases) could you create a new issue?
For now, I close this old issue.
