### ISSUE TITLE
Transparent Image from WMS hides other image-Layer

### ISSUE THREAD

**Issue by frank2x460** [MapWindow/MapWinGIS#156]
When adding a transparent image (png) from an WMS Service (layer position 10 (top))
and adding a additional image layer on layer position 0 (bottom) the image on layer 0 is covered by the image on layer 10. All the layers between (1-9, point or polyline layers) are no covered!

When adding Tiles from a Tileserver (e.g. OSM) the Tiles can be seen too!

Why is the second image covered by the transparent image an cannot be seen?

MapWinGis 5.0.1

**Comment by pmeems** [comment]
Thanks Frank for reporting this.

I will need to investigate this more closely.

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWinGIS/releases) could you create a new issue?
For now, I close this old issue.
