### ISSUE TITLE
Failure to read data from ogrlayer.getBuffer() Method!

### ISSUE THREAD

**Issue by wangxiya** [MapWindow/MapWinGIS#157]
I open dataset fileGDB, and I get layers and fields information of each layer. But when I want get data of layer, It always return empty shapefile!

in pascal:
aLayer := aDatasource.GetLayer(aLayerIndex, False);
aLayerFeatureCount := aLayer.FeatureCount[True];
aLayer.DynamicLoading := False;
aLayer.MaxFeatureCount := aLayerFeatureCount + 100;
FFileShp := aLayer.GetBuffer;
for I := 0 to FFileShp.NumShapes - 1 do
  ...

I debug in vc2015, the GetBuffer seem work correct, But FFileShp.NumShapes is zero!

**Comment by wangxiya** [comment]
or my code is wrong ？
Has someone help me?
thanks!

**Comment by pmeems** [comment]
Can you share a sample GDB so we can debug?
I'm missing in your code how you are connecting to the GDB-file, but at first sight I don't see anything wrong. 
But I must say, I don't have experience with GDB-files.

Perhaps you can also use [AddLayerFromDatabase()](https://www.mapwindow.org/documentation/mapwingis4.9/group__map__layer__management.html#ga3672fae9774e0bbb917ab23e13855ebe)

**Comment by wangxiya** [comment]
When I open shape file (*.shp) with the same way, the FFileShp.NumShapes is zero too!  I watch the memory before and after getBuffer(),  the memory going up before getbuffer() and going down after getbuffer() rapidly!

**Comment by wangxiya** [comment]
My GDB file is huge! about 1G, it is not easy to share with internet! please use shp file! thanks !

**Comment by wangxiya** [comment]
My mistake,  aLayer is local variance, FFileShp is global variance of unit, when alayer release , the buffer is release too! 
thanks a lot for everyone!

**Comment by pmeems** [comment]
I need a few days to write some sample code for you.
I normally don't use `GetBuffer()` 
For shapefiles I use `sf.Open(....)` and `sf.NumShapes`
