### ISSUE TITLE
I want contribute my code of gdalinfo() and ogrinfo()

### ISSUE THREAD

**Issue by wangxiya** [MapWindow/MapWinGIS#158]
I have changed the code of ogrinfo and gdalinfo , to output message with json format. will someone want it?

**Comment by jerryfaust** [comment]
Yes.  All contributions are appreciated.  This would typically be done by creating a Pull Request against the 'develop' branch.  Would you do that?

**Comment by wangxiya** [comment]
I use RapidJson package to output json, Shall I push the rapidjson to develop branch?

**Comment by wangxiya** [comment]
> Yes. All contributions are appreciated. This would typically be done by creating a Pull Request against the 'develop' branch. Would you do that?

I try pull the develop branch , and I update shape.cpp and ogrLayer.cpp, but github reply to me :
Permission to MapWindow/MapWinGIS.git denied to wangxiya.
What shall I do?

**Comment by pmeems** [comment]
> I try pull the develop branch , and I update shape.cpp and ogrLayer.cpp, but github reply to me :
> Permission to MapWindow/MapWinGIS.git denied to wangxiya.
> What shall I do?

Is this still an issue? I saw you made pull request #161 

And regarding json export of gdalinfo. This is already possible with [gdalinfo](https://gdal.org/gdalinfo.html) Do we really need RapidJson for this as well?
