### ISSUE TITLE
The potential risk of shape.importfromwkt()

### ISSUE THREAD

**Issue by wangxiya** [MapWindow/MapWinGIS#159]
OLE2A(str) has limit of length of str, it is 4k, when I import a multipolygon from wkt, Sometime the length of wkt will break 4k。

code：
STDMETHODIMP CShape::ImportFromWKT(BSTR Serialized, VARIANT_BOOL *retVal)
{
	AFX_MANAGE_STATE(AfxGetStaticModuleState())
	*retVal = VARIANT_FALSE;

	USES_CONVERSION;
	CString ser = OLE2A(Serialized);

	OGRGeometry* oGeom = NULL;
	char* buffer = ser.GetBuffer();

suggest：
	char* pBuf = _com_util::ConvertBSTRToString(Serialized);

	char *pszBuffBack = pBuf;

	OGRGeometry* oGeom = NULL;
	OGRErr err = OGRGeometryFactory::createFromWkt(&pBuf, NULL, &oGeom);
	delete[] pszBuffBack;

**Comment by pmeems** [comment]
Thanks for taking the time to report this.

You can make a pull request against the develop branch.
We will investigate it and merge it.
