### ISSUE TITLE
Compiler Warning in Visual Studio 2017- C#

### ISSUE THREAD

**Issue by tolgasertel** [MapWindow/MapWinGIS#16]
Hi there,
I'm trying to run a project in C#(Visual Studio 2017) with MapWinGIS v4.9.4.2. The project seems to work correctly, but I have several instances of the following warning:

Processing COM reference "MapWinGIS" from path "C:\dev\MapWinGIS\MapWinGIS.ocx". At least one of the arguments for 'IShapeDrawingOptions.DrawRectangle' cannot be marshaled by the runtime marshaler. Such arguments will therefore be passed as a pointer and may require unsafe code to manipulate.

Thanks,
Tolga

**Comment by pmeems** [comment]
We are aware of these warning. 
We don't know how to fix them and since everything seems to work fine it has no priority.
Please let me know if you have C++ knowledge and do know how to fix these warnings.

**Comment by tolgasertel** [comment]
Hi,
I have C++ knowledge. I checked my c# Code and i didnt find any clue for the cause of that warning. Most probably, the problem came from ocx. I think, we should check ocx source code. What do u think?

**Comment by pmeems** [comment]
We know it is in the ocx.
Please have a look at the C++ code and let me know if you can fix these warnings.
Here's a video how to set-up your environment for MapWinGIS.
