### ISSUE TITLE
How can I load tiles non SphericalMercator?

### ISSUE THREAD

**Issue by trustuser** [MapWindow/MapWinGIS#162]
I add tile:
`Map.Tiles.Providers.Add(
      providerId,
      'MyLocalTile',
      'http://localhost?x={x}&y={y}&z={zoom}',
      SphericalMercator , 1, 28
    );
`
Position tile incorrect on then map; Tile is shifted a few kilometers.
` // select only  2 variants
type
  tkTileProjection = TOleEnum;
const
  SphericalMercator = $00000000;
  Amersfoort = $00000001;`

need wgs84Mercator

For example, except for me, it uses Yand ex maps and other services

**Comment by pmeems** [comment]
It is better to ask questions at our forum: https://mapwindow.discourse.group/

When you set the map projection to `wgs84Mercator` the tiles should be reprojected on the fly.
