### ISSUE TITLE
Thread cannot exit normally in MFC MDI mode!

### ISSUE THREAD

**Issue by zcwbnu** [MapWindow/MapWinGIS#164]
I create a new MFC multi-document program, which can normally exit.  Then dynamically add mapwingis control in view, I found program can't exit when closing the main frame window.

![微信图片_20190601224131](https://user-images.githubusercontent.com/18117662/58749930-6c788080-84be-11e9-9629-dfe0db612483.jpg)

**Comment by jerryfaust** [comment]
Inability to exit would tend to indicate that the map reference is not being released.  Are you releasing the Map reference at shutdown?

**Comment by zcwbnu** [comment]
@jerryfaust Yes, I deleted the variable “m_pMap”  and I found   the number of threads reduced by 1. Howerver，The program still has 6 threads(MFC UI threads)  and I can't close the 6 threads by Closing the window.  If I  didn't create the map control dynamically，MFC UI threads can exit normally.

I just created an empty MFC multi-document framework with VS2015 and added the following code.
CRect rc;
GetClientRect(&rc);
if(m_pMap->Create(L"CMap1",WS_CHILD|WS_VISIBLE|WS_BORDER,rc,this,IDC_MAP3))
{
   m_pMap->SetBackColor(RGB(0,0,0));
}

**Comment by zcwbnu** [comment]
I found threads exit normal after add a map layer. It's Very strange.

**Comment by jerryfaust** [comment]
It's interesting that you mention that.

I recently noticed an issue when loading the map, then closing without loading any layers, an Exception is thrown in `CMapWinGISApp::ExitInstance()`.  This only occurs in the Debug build.  I have fixed this bug (although I have not yet checked it in).

Are you running a Debug build of the Map OCX?  Perhaps it is related to this bug.

**Comment by zcwbnu** [comment]
This problem exists in both debug and release mode
