### ISSUE TITLE
Reproject WMS Image

### ISSUE THREAD

**Issue by frank2x460** [MapWindow/MapWinGIS#168]
Is it possible to reproject a WMS Image, which has been aquired from WMS Server with a different Geoprojection because the server does not supports our Projection?
Is it possible to save the image to disc?  The "save"-Method only saves the XML-File specified for the download!

**Comment by pmeems** [comment]
Sorry for not responding earlier. 
Did you ever get this to work?
Questions can best be asked on the forum: https://mapwindow.discourse.group/
