### ISSUE TITLE
how to use with VS2017

### ISSUE THREAD

**Issue by weskerjiang** [MapWindow/MapWinGIS#169]
I want to create an application with MapWinGIS using WinForm,i want add the ocx file into the toolbox,but it saies   MapWinGIS.ocx regiested failed.Then I tried using the command regsvr32,it succeed,but i still can't add it into the toolbox.So what should i do?
All i done with Administrator

**Comment by jerryfaust** [comment]
Hello @weskerjiang 

Did you build the OCX or did you run one of the installers from [here](https://github.com/MapWindow/MapWinGIS/releases)?

What version of the OCX are you using?

Thanks.

**Comment by weskerjiang** [comment]
> 
> 
> Hello @weskerjiang
> 
> Did you build the OCX or did you run one of the installers from [here](https://github.com/MapWindow/MapWinGIS/releases)?
> 
> What version of the OCX are you using?
> 
> Thanks.

Hello @jerryfaust 
I've download the file from https://github.com/MapWindow/MapWinGIS/releases.My version is v5.0.1,the file is MapWinGIS-only-v5.0.1.0-x64.exe

**Comment by jerryfaust** [comment]
Ok.  I believe the issue is with the 64-bit OCX.  Perhaps @pmeems can confirm this, but you need to put the 32-bit OCX on the development machine since Visual Studio can't load a 64-bit OCX.  You can then build a 64-bit exe, and run it on a machine that you've installed the 64-bit OCX.

**Comment by weskerjiang** [comment]
Thanks,I've solved this problem
