### ISSUE TITLE
display a map from a sqlite data base

### ISSUE THREAD

**Issue by Ryotchi** [MapWindow/MapWinGIS#17]
hi guys! 
thank you for the great work that you are doing.
am trying to display a map by using ogr from sqlite database file with no success. 
can you please post a full example how to do it
thank you

**Comment by pmeems** [comment]
Did you have a look at this: http://www.mapwindow.org/documentation/mapwingis4.9/class_ogr_datasource.html

What part do you have questions about?

**Comment by pmeems** [comment]
Closing this old question.
