### ISSUE TITLE
How to identify multiple shapes

### ISSUE THREAD

**Issue by weskerjiang** [MapWindow/MapWinGIS#170]
Hello!I want identify multiple shapes in one time,so i find AxMap has two events,[ShapeIdentified] and [ShapesIdentified].But when i identify shapes,it only get into the ShapeIdentified event.i've set the mode to [tkIdentifierMode.imAllLayers].So what should i do?Thanks!

**Comment by jerryfaust** [comment]
Hello.
I found a similar issue that was addressed on the MapWindow forum.  Check out this link and see if your question is answered.  In short, you can use the ShapeIdentified event, and within that event, ask for all selected Shapes.

[https://mapwindow.discourse.group/t/how-to-identify-a-shapefile-layer/155](https://mapwindow.discourse.group/t/how-to-identify-a-shapefile-layer/155)

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWinGIS/releases) could you create a new issue?
For now, I close this old issue.
