### ISSUE TITLE
Get DBF file inside the Chinese data content, display garbled code

### ISSUE THREAD

**Issue by ZiYou2333** [MapWindow/MapWinGIS#171]
I'm not using the database, I'm just accessing the local file, and I'm using get_cellvalue to get the value of the corresponding table in the property sheet, and when the value in the table is in Chinese, there will be random codes, and the random codes will appear when I get the value

**Comment by ZiYou2333** [comment]
`var cellvalues = sf.get_CellValue(i, shpIndex).ToString();`This is my code to get the contents of the table

**Comment by jerryfaust** [comment]
Hello @ZiYou2333 

Do you know if the strings are encoded in UTF-8 format (the default if no code page is provided)? or is there a CodePage file (.CPG) for the Shapefile you're reading?  If neither of these it true, you may need to provide a CodePage file, which is just
1. a text file having the same name as the shapefile, but with a CPG extension
2. that contains the code of the [code page](https://en.wikipedia.org/wiki/Code_page) indicating how the strings are stored

I can't say for sure if this is the solution to your problem, but it's a good place to start.

Regards.
Jerry.

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWinGIS/releases) could you create a new issue?
For now, I close this old issue.
