### ISSUE TITLE
does MapWinGIS support WMTS?

### ISSUE THREAD

**Issue by weskerjiang** [MapWindow/MapWinGIS#173]
I want to add a wmts service into the application,but i don't know how to add it.I find MapWindow only support wms

**Comment by pmeems** [comment]
WMTS is not (yet) implemented in MapWinGIS.
I see it is supported in GDAL: https://gdal.org/drivers/raster/wmts.html so it could be added.
All we need is a volunteer to implement it.

Please ask questions at our forum: https://mapwindow.discourse.group/ and keep GitHub for real issues.
