### ISSUE TITLE
Can mapwingis preprocess large images into tiles or caches?

### ISSUE THREAD

**Issue by zcwbnu** [MapWindow/MapWinGIS#175]
I have a 2 gb satellite image, mapwingis is very slow when  loading , can it be preprocessed to tile or cache by mapwingis？

**Comment by MiniminSSS** [comment]
Hi,bro,  problem solved?

**Comment by pmeems** [comment]
Sorry nobody got back to you before.
You can try to add overviews, those should load faster.
[Utils.GDALAddOverviews()](https://www.mapwindow.org/documentation/mapwingis4.9/class_utils.html#ac7352d6853354c6995c95e9c60804f77)

Please use our forum for future questions: https://mapwindow.discourse.group/
