### ISSUE TITLE
MapWinGIS control in Office documents

### ISSUE THREAD

**Issue by dpmcmlxxvi** [MapWindow/MapWinGIS#176]
Can a MapWinGIS control be embedded in an office document (e.g., Excel, Word, PowerPoint) to allow a user to interact with, for example, a map with multiple layers (e.g., shapefile, georeferenced raster)? The idea being to have a document with spatial data that is more interactive than a static image.

**Comment by pmeems** [comment]
Yes it can. That is the whole reason MapWinGIS is an ActiveX control.

I know it is used by a lot of users in Excel and Access.
After installing MapWinGIS the map control is available in the COM controls,
https://support.office.com/en-us/article/how-to-use-the-forms-controls-on-a-worksheet-in-excel-e7e33c0c-f080-4443-b565-d21b1bdbcf43

It is best to ask question in our forum: https://mapwindow.discourse.group/
