### ISSUE TITLE
MapWinGIS library in xamarin forms

### ISSUE THREAD

**Issue by cpalominoch** [MapWindow/MapWinGIS#177]
Dear,
Can the MapWinGIS library be used in xamarin forms to create shapefile?

Best regards.

Carlos Palomino

**Comment by jerryfaust** [comment]
Hello @cpalominoch 

MapWinGIS is strictly a Windows API-based OCX control.  Even if you could make it work on a Windows-based Xamarin Form, you would not be able to move it to any of the other Xamarin platforms.

If you're looking for an open-source map control that supports Xamarin, there are a few out there, with various levels of functionality.  One that I've looked at is called [Mapsui](http://mapsui.com/documentation/Home.html).  I'm not specifically endorsing it - I don't know a lot about it.  But I mention it as a reference.

Regards,
Jerry.
