### ISSUE TITLE
Custom tile  provider

### ISSUE THREAD

**Issue by Ryotchi** [MapWindow/MapWinGIS#18]
http://mapwingis.codeplex.com/discussions/656674
can anyone please answer to this issue.
best regards!

**Comment by pmeems** [comment]
Do you have similar issues?
Are you sure your URLs are correct?
Can you provide a working URL that is returning a tile?

**Comment by Ryotchi** [comment]
i have a similar issue, am trying to use mapserver as a localhost map but no succeed.

**Comment by pmeems** [comment]
Can you show me a working URL that is returning a tile?
When you paste this url in your browser you should see a tile.
It doesn't matter if I can't access it, it is just to check the syntax.

**Comment by ButtCrackBob** [comment]
There seems to be and issue with Custom Providers in Mapwingis 4.9.0.0.  I'm using Mapserver MS4W v3.2.2. I am unable to view or cache tile using the code
`providers.Add(providerId, "AprsProvider", "http://localhost:8080/maps/{zoom}/{x}/{y}.png", tkTileProjection.SphericalMercator, 0, 18);`

I've also noticed that
`axMap1.TileProvider = tkTileProvider.ProviderCustom;`
Does not change axMap1.TileProvider. Any assistance would be appreciated.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
