### ISSUE TITLE
GdiplusShutdown at it again

### ISSUE THREAD

**Issue by nextfullstorm** [MapWindow/MapWinGIS#180]
There is an application hang on exit if you use MapWinGIS in environment where you cannot control GDI+ initialization/finalization. For example, Delphi project: if there is an unit with mawingis AND GDI+ code, than app will hang on shutdown forever. Why? Because Delphi calls GdiplusStartup/Shutdown automatically and mapwingis calls it from DllMain (its strictly prohibited in docs), which calls causes deadlock on second GdiplusShutdown.

1. Create Delphi project "VCL Forms Application". I tested it on Delphi 10.2.
1. Add GDIPObj to uses section of main form unit.
2. Drop a TmwMap component on main form and ensure that MapWinGIS_TLB added to uses section.
3. That's it!
4. Build project, run, close app. Delphi debugger show app still running. We can see call stack if we press Pause Debug.

Test environment: Delphi 10.2, MapWinGIS 5.1, Windows 8.1/10 x64.

I've read long comment about GdiplusStartup/Shutdown in Map.cpp:723. Clearly it not works as it states and NotificationHook/Unhook doesn't help here (at least for me). I was able to fix it by bringing back old solution (GdiplusStartup in CMapView ctor, GdiplusShutdown in CMapView dtor) AND adding TileCacheManager::CloseAll(); before GdiplusShutdown. Latter is for fixing "issues with tile cache" as long comment states. I don't know what side effects it will made so should I make pr or am I just mistaken somewhere?

Test Delphi project here:
[mapwin-bug.zip](https://github.com/MapWindow/MapWinGIS/files/3783068/mapwin-bug.zip)

**Comment by mainxt** [comment]
Yes, I confirm... this problem has been present for a long time. Because of this I had to give up sharing MapWinGIS and DevExpress products (https://www.devexpress.com/). Process simply hangs and his account for kill manually. It was necessary to refuse while such mode of work...

**Comment by jerryfaust** [comment]
Hello.  So I just reviewed the MSDN article, your comments, and the current code with the long comment - so now I am a little more up-to-speed on the issue.  I will share my thoughts.

The proposed solutions in the MSDN article imply that startup/shutdown should only be called once, either by your application, OR by the DLL/OCX.   Since you say that Delphi automatically calls startup/shutdown, and your proposed solution will also have MapWinGIS always calling statup/shutdown (outside of DllMain/InitInstance),  Is that not a problem?  Unless you could then suppress the calls from Delphi?  or was it just a matter of removing the calls from DllMain/InitInstance?  Bear with me for not fully understanding.

From what (little) I understand, I think that I like your proposed solution.  And you're correct that we would just have to verify that there are no negative side-affects related to the Tile Cache.

Regarding other options, I would think that startup/shutdown within every function that uses GDI+ would incur too much overhead.  And so I think I would consider the option of exporting Startup/Shutdown functions from our API, allowing the caller to either call statup/shutdown within their application OR call the Startup/Shutdown methods in the OCX.

Regards,
Jerry.

**Comment by jerryfaust** [comment]
FOLLOW-UP:  I did a little testing.  MapWinGIS consists of two parts: the OCX, and an API that can be called independent of the OCX.  I did a quick test to verify, and if I create an application that does not contain the OCX, but still creates objects such as a Shapefile or an Image, the CMapView constructor is never called.  So if we move toward using CMapView to startup and shutdown GDI+, I will have to make sure that GDI+ gets initialized prior to any calls that might be called outside of the OCX.

**Comment by nextfullstorm** [comment]
Hello, Jerry.

> The proposed solutions in the MSDN article imply that startup/shutdown should only be called once, either by your application, OR by the DLL/OCX. 

Honestly, I didn't see where MSDN proposes solution to only call startup/shutdown ONCE. You can call startup/shutdown as many times as you like as long as you a) balance startup and shutdown b) don't call it from DllMain. You can call it from different threads, too.


> Since you say that Delphi automatically calls startup/shutdown, and your proposed solution will also have MapWinGIS always calling statup/shutdown (outside of DllMain/InitInstance), Is that not a problem? 

No, it's not a problem.


> Unless you could then suppress the calls from Delphi? 

No, we can't suppress it. I started from that - what if we're in environment where we can't control other calls to GDI+?


> or was it just a matter of removing the calls from DllMain/InitInstance? 

It is.


> Regarding other options, I would think that startup/shutdown within every function that uses GDI+ would incur too much overhead. 

Agree. The overhead not-so-big, but pointless.


> And so I think I would consider the option of exporting Startup/Shutdown functions from our API, allowing the caller to either call statup/shutdown within their application OR call the Startup/Shutdown methods in the OCX.

It's a breaking change. I agree again, but such change should be accompanied with big red warning in dev documentation. Considering this (, the fact that I didn't know about non-OCX part of API) and your follow-up I think of it as of lesser evil.

**Comment by jerryfaust** [comment]
Hello All.

Here is my current thinking and recommendation:
1. Implement the changes suggested by @nextfullstorm, moving the GDIPlus Startup and Shutdown back into the CMapView ctor/dtor.  I imagine this covers well over 90% of MapWinGIS usage.
2. There are a number of CoClasses that use GDI Plus, and that can be created without first creating the MapView.  However, most make no sense outside of the Map - most are drawing and labeling classes that are only created within the context of the map.
3. Those that may realistically be created standalone (for example, the Image class) can be evaluated independently, and each do their own GDI Startup and Shutdown in their respective ctors/dtors.

I have opportunity to put this in place and work with it for a month or so before my work needs to move toward production, and I can also set up an app to test the various CoClasses independently of the Map control.

I will move forward with this approach and let you know how it goes.  Please fee free to express any concerns or additional considerations.

Thank you,
Jerry.

**Comment by jerryfaust** [comment]
I should note here an update has been submitted that relates to this issue, specifically:
[MWGIS-205: GdiplusStartup/Shutdown should not be called in DllMain](https://mapwindow.atlassian.net/browse/MWGIS-205)

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWinGIS/releases) could you create a new issue?
For now, I close this old issue.
