### ISSUE TITLE
is v5.1.0 still instability ?

### ISSUE THREAD

**Issue by qq2898** [MapWindow/MapWinGIS#183]
https://github.com/MapWindow/MapWinGIS/releases shows
**Update Oct. 29 2019**
This version has some instability. A hotfix will be released within 10 days.

dose the hotfix has been released yet ?

**Comment by pmeems** [comment]
I've just published a v5.1.1 at https://drive.google.com/drive/folders/0B8UeIGgvyx2VQXRDVndvTUVlUFE?usp=sharing. It will act as a release candidate. Please use it, test it and let us know if you run into trouble.

When nothing new is reported I'll publish this version by the end of the week as the new stable version.

**Comment by pmeems** [comment]
I've promoted the release candidate as the new official new version (v5.1.1).
Get it at https://github.com/MapWindow/MapWinGIS/releases
