### ISSUE TITLE
mousedown event

### ISSUE THREAD

**Issue by james5126** [MapWindow/MapWinGIS#186]
hi i'm korean so i'm not good at English. Please understand it.
here is my problem. i created axMap1_MouseDownEvent and filled it like this.

private void axMap1_MouseDownEvent(object sender, _DMapEvents_MouseDownEvent e)
        {
            MessageBox.Show("i");
        } 

but it is not working! how can i solve the problem?

**Comment by pmeems** [comment]
Please post questions on our forum: https://mapwindow.discourse.group/

Have you enabled [SendMouseDown](https://www.mapwindow.org/documentation/mapwingis4.9/group__map__interaction.html#gabdd3a82d13432eef94d063439ea3de91) as mentioned in the [MouseDownEvent documentation](https://www.mapwindow.org/documentation/mapwingis4.9/group__map__events.html#ga73bb10449981208214063f48cc06fe03)

**Comment by james5126** [comment]
yeah i have done that following the examples.
but nothing happened

**Comment by pmeems** [comment]
Several SendMouse properties exist. Are you sure you've enabled the correct one?
Which version of MapWinGIS are you using and with what language? I assume C#.

**Comment by pmeems** [comment]
Question continues at https://mapwindow.discourse.group/t/mousedown-event-is-not-fired/352
