### ISSUE TITLE
CTiles::get_GridLinesVisible() returned parameter always VARIANT_TRUE

### ISSUE THREAD

**Issue by gdorval** [MapWindow/MapWinGIS#189]
**Describe the bug**
MapWinGIS **v5.1.1.1**

In **CTiles::get_GridLinesVisible()**, from Tiles.cpp at line 360 :
    *pVal = _manager.get_GridLinesVisible() ? VARIANT_TRUE : **VARIANT_TRUE**;

**To Reproduce**
1. Call CTiles::get_GridLinesVisible()
2. Verify the returned value

**Expected behavior**
    *pVal = _manager.get_GridLinesVisible() ? VARIANT_TRUE : **VARIANT_FALSE**;

**Comment by jerryfaust** [comment]
Thank you, @gdorval 

I'll submit the change.

Regards,
Jerry.

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWinGIS/releases) could you create a new issue?
For now, I close this issue.
