### ISSUE TITLE
Just upgraded from 4.8 and my shape files don't draw anymore... any ideas?

### ISSUE THREAD

**Issue by fairps** [MapWindow/MapWinGIS#19]
I use a custom base map from a TIFF file and then overlay it with a couple of layers that are SHP_POINT shape files.  The shape files are not rendering, but if I do a ZoomToMaxVisibleExtents() on the layer it will correctly zoom to the extents of the objects in the shape file for the layer even though I cannot see them.  Any help would be hugely appreciated!  I'd hate to have to fall back to 4.8 since this has many nice new features! 

Here is my code for adding the shape file layers:
```
			Shapefile sf = new Shapefile();
			sf.CreateNewWithShapeID("", ShpfileType.SHP_POINT);

			// Add Name attribute
			sf.StartEditingShapes(true, null);
			Field name = new Field() { Name = "Name", Type = FieldType.STRING_FIELD, Width = 20 };
			int nameIndex = sf.NumFields;
			sf.EditInsertField(name, ref nameIndex, null);
			sf.StopEditingShapes(true, true, null);

			// creating points and inserting them in the shape
			sf.StartEditingShapes(false, null);
			foreach (MapEquipmentDef well in layerDef.Equipment.Values)
			{
				MapWinGIS.Point pnt = new MapWinGIS.Point() { x = well.X, y = well.Y };

				Shape shp = new Shape();
				shp.Create(ShpfileType.SHP_POINT);

				int index = 0;
				shp.InsertPoint(pnt, ref index);

				int shpIndex = sf.NumShapes;
				sf.EditInsertShape(shp, ref shpIndex);
				sf.EditCellValue(nameIndex, shpIndex, well.DisplayName);

				well.LayerIdx = axMap1.NumLayers;
				well.ShapeIdx = shpIndex;
			}
			sf.Labels.Alignment = tkLabelAlignment.laBottomCenter;
			sf.Labels.AutoOffset = true;
			sf.Labels.AvoidCollisions = true;
			sf.Labels.FontBold = true;
			sf.Labels.FontSize = 9;
			sf.Labels.FontColor = Convert.ToUInt32(ColorTranslator.ToOle(layerDef.LabelColor));
			sf.Labels.FrameVisible = false;
			sf.GenerateLabels(nameIndex, tkLabelPositioning.lpCenter, false);

			sf.StopEditingShapes(true, true, null);

			sf.DefaultDrawingOptions.SetDefaultPointSymbol(layerDef.Symbol);
			sf.DefaultDrawingOptions.PointSize = layerDef.SymbolSize;
			sf.DefaultDrawingOptions.LineColor = Convert.ToUInt32(ColorTranslator.ToOle(Color.Black)); 
            sf.DefaultDrawingOptions.FillColor = Convert.ToUInt32(ColorTranslator.ToOle(layerDef.SymbolColor));
            sf.FastMode = true;

			// adds shapefile to the map
			layerDef.LayerIdx = axMap1.AddLayer(sf, true);
			axMap1.set_LayerName(layerDef.LayerIdx, layerDef.LayerName);
			axMap1.set_LayerVisible(layerDef.LayerIdx, true);

```

**Comment by fairps** [comment]
I even turned off all the validation stuff in hopes that might be why but no luck :-(
			new MapWinGIS.GlobalSettings
			{
				AllowLayersWithoutProjections = true,
				AllowProjectionMismatch = true,
				ShapeInputValidationMode = tkShapeValidationMode.NoValidation,
				ShapeOutputValidationMode = tkShapeValidationMode.NoValidation
			};

**Comment by fairps** [comment]
This is what it looks like under 4.8:
![image](https://cloud.githubusercontent.com/assets/27831128/25254271/59149630-25ea-11e7-8ef6-39af25fee468.png)

Under 4.9.4 all I see is the base map

**Comment by pmeems** [comment]
Can you attach the shapefile you've created? I will try to open it in MW5, which is also using MapWinGISv4.9

**Comment by fairps** [comment]
Thanks for the quick response Paul!   Through much trial and error I have found the problem... in my shape file code I had FastMode = true.  For some reason under the new version that causes the layer not to draw for me (maybe I'm missing something I should be doing?).  The shapefile objects are definitely there either way because I can zoom to them, but they don't draw if FastMode = true.

**Comment by Dv0rnik** [comment]
I've got the same problem in Delphi7! Function ShapeFillColor dosen't work. Can anybody give me an advice?

**Comment by pmeems** [comment]
@Dv0rnik Please don't hijack somebody else's thread. Create a new one.

We don't have a lot of support for Delphi. Some other users are struggling with Delphi as well.
To color a shape it is best to use a category. Have a look at these examples:
http://www.mapwindow.org/documentation/mapwingis4.9/_select_by_distance_8cs-example.html#a8
http://www.mapwindow.org/documentation/mapwingis4.9/_line_pattern_8cs-example.html#_a17
