### ISSUE TITLE
can't compile successfully,support library not give

### ISSUE THREAD

**Issue by yttina** [MapWindow/MapWinGIS#192]

**Comment by jerryfaust** [comment]
Hello @yttina 

Could you please provide more detail?  What version of the source code?  What is the compiler error?

Have you seen this [tutorial on building MapWinGIS](https://mapwindow.discourse.group/t/tutorial-compiling-mwgis-in-vs2017/118)?

Thank you,
Jerry.

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWinGIS/releases) could you create a new issue?
For now, I close this issue.
