### ISSUE TITLE
Troubles in connecting with Openstreet map

### ISSUE THREAD

**Issue by sxqHusky** [MapWindow/MapWinGIS#193]
Hi,we are now using mapwingis.But we found that our mapcontrol can't get connected to Openstreet map.So we can not see the map on the mapcontrol.How could we deal with this question in order to show openstreet map on mapcontrol.Thanks a lot.

**Comment by pmeems** [comment]
We get regular questions about OSM. It seems they are restricting access.
You could use [StartLogTileRequests()](https://www.mapwindow.org/documentation/mapwingis4.9/class_global_settings.html#a900a8677dfcc080f2f1d64566b7582e3) to log the requests and see what is happening.

Also, questions can be asked best on our forum: https://mapwindow.discourse.group/

This question might also be helpfull for you: https://mapwindow.discourse.group/t/openstreetmaps-and-openhumanitarianmap-loading-very-slow/513/2

**Comment by sxqHusky** [comment]
Thanks for your help, I have changed my code,however I still can't see the openstreetmap online, here is my code, how should I chenge them.(C# VS2012)


using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using MapWinGIS;
using AxMapWinGIS;
using System.IO;
using System.Diagnostics;

namespace WindowsFormsApplication1
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            GlobalSettings gs = new GlobalSettings();
            gs.StartLogTileRequests("F:\\temp", true);
            axMap1.TileProvider = tkTileProvider.OpenStreetMap;
            axMap1.Projection = tkMapProjection.PROJECTION_WGS84;

        }
    }
}

**Comment by pmeems** [comment]
You also need boundaries. Either by loading a layer (shapefile) or setting the extents.
Please have a look at the [Getting Started page](https://www.mapwindow.org/documentation/mapwingis4.9/getting_started.html).

**Comment by sxqHusky** [comment]
sorry bro, I still can't see the openstreet map, however, I can see my shapefile on the map control.
![result](https://user-images.githubusercontent.com/49707849/79851632-2d199200-83f8-11ea-9c53-2086e830d261.png)

here is the code
InitializeComponent();
            axMap1.Projection = tkMapProjection.PROJECTION_WGS84;
            axMap1.TileProvider = tkTileProvider.OpenStreetMap;
            axMap1.KnownExtents = tkKnownExtents.keChina;
            axMap1.Tiles.AutodetectProxy();

            string fileName = "F:\\temp\\buileding.shp";
            int layerHandle = axMap1.AddLayerFromFilename(fileName, tkFileOpenStrategy.fosAutoDetect, true);

            GlobalSettings gs = new GlobalSettings();
            gs.StartLogTileRequests("F:\\temp", true);

**Comment by pmeems** [comment]
Your shapefile is in the correct projection? Can you share that file? If so don't forget to add the .shp, .shx, .dbf and .prj files

**Comment by sxqHusky** [comment]
yes, the projection is wgs1984, here is the shape file. I have only .shp and .shx. 
[builedings.zip](https://github.com/MapWindow/MapWinGIS/files/4509718/builedings.zip)

**Comment by sxqHusky** [comment]
and could you please give me a demostration about how to display openstreetmap on mapcontrol,thanks alot.

**Comment by pmeems** [comment]
When I open your layer in MapWindow5 I can see it loads and it is near China but in the ocean:
![image](https://user-images.githubusercontent.com/12067729/79865024-c3d75600-83da-11ea-92c5-51d78d18441f.png)
Is that expected? If not then you probably have the shapefile in a different projection. Without the .prj file it is hard to tell.

Which version of MapWinGIS are you using and did you do the steps on the getting started page?
And what is logged in the tiles logfile?

**Comment by sxqHusky** [comment]
Sorry bro,I was delayed by several interviews.
Actually the true location is near ShangHai( a beautiful city in China), I did do the same steps on the getting started page, my MapWinGIS version is 5.0.0.0. 
I think it must be the problem of my version. Because I have just donwload the MapWindow(5.5.0.0), it can get connected to the openstreetmap.

**Comment by pmeems** [comment]
Using the latest version is always a good idea.
OSM changed last year from HTTP to HTTPS. That might be the reason for your problems with the tiles.
I'm glad it is solved now. I'm closing this issue.
Please ask new questions on the forum
