### ISSUE TITLE
Clickable marker on the map 

### ISSUE THREAD

**Issue by Kayumiy** [MapWindow/MapWinGIS#194]
**Forum**
Please use our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis) if you have questions or remarks.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Hello,

I used this example script  [ToolTip.cs](https://www.mapwindow.org/documentation/mapwingis4.8/_tool_tip_8cs-example.html)  2 in order to make clickable marker on the map. However, it does not work when cursor goes to over the marker.
I checked previous questions, it did not work.
Can anybody help me solve this issue?

Thanks a lot

**Comment by pmeems** [comment]
As written in the template: "Please use our MapWinGIS forum if you have questions or remarks."
If you re-ask the question on the forum and let us know what part is working and what not, then we can help you.
