### ISSUE TITLE
where is the latest help document for MapWinGIS?

### ISSUE THREAD

**Issue by qq2898** [MapWindow/MapWinGIS#196]
the latest document is for v4.9.3 ?

**Comment by pmeems** [comment]
Please ask questions on the forum: https://mapwindow.discourse.group/

The latest version of the documentation is on https://www.mapwindow.org/documentation/mapwingis4.9/
The URL is a bit misleading. You can see the version history at https://www.mapwindow.org/documentation/mapwingis4.9/version_history.html
