### ISSUE TITLE
missing gdal_priv.h

### ISSUE THREAD

**Issue by TongZhai** [MapWindow/MapWinGIS#20]
Try to build solution, but got the following message in VS 2015:

`Error	C1083	Cannot open include file: 'gdal_priv.h': No such file or directory	MapWinGIS	C:\dev\github\MapWinGIS\src\Control\GlobalVars.h	8`

**Comment by TongZhai** [comment]
actually, the following header files are also missing:
```
geos_c.h
ogr_geometry.h
ogr_spatialref.h
```

**Comment by pmeems** [comment]
Please have a look at this video: https://www.youtube.com/watch?v=WVQaFsil0bY
You need to download the headers and binaries for GDAL first.

**Comment by TongZhai** [comment]
Actually, Paul, I went ahead got the gdal's git repo and got those headers (I put them manually inside the 'Control' folder), now it is complaining this missing 'geos_c.h'. This header file is not in gdal repo and it is not in MapWinGIS repo either... where can I find it?

Thanks for the link, I will certainly watch it.

**Comment by pmeems** [comment]
Did you get the GDAL stuff from gisinternals.com.
If you did you should have 'geos_c.h' because I have this file as well.

**Comment by TongZhai** [comment]
Yes, after I used the GDAL libraries/DLLs from gisinternals.com, it all worked. Please close this issue. Thanks.
