### ISSUE TITLE
Couldn't compile MapWinGIS project with VS community 2015

### ISSUE THREAD

**Issue by TongZhai** [MapWindow/MapWinGIS#21]
Microsoft seems to discontinue the VS community 2013 software, hence I am trying to compile this project using the VS community 2015 software. I followed the instruction to use GDAL library from gisinternals.com, and did a couple of small changes in the Tools.h and TileManager.cpp, it got past compilation, but failed during linking with the following message:
```
Error	LNK2038	mismatch detected for '_MSC_VER': value '1800' doesn't match value '1900' in DrawingRectangle.obj	MapWinGIS	C:\dev\github\MapWinGIS\src\SpatialIndex-mw.lib(DiskStorageManager.obj)	1
```	
I think this is due to GDAL libs being compiled with VS2013 (1800), could we start petition to GDAL people to offer 1900 version of the libs? also could this project be updated to be compiled with VS2015?

**Comment by pmeems** [comment]
It has been asked already: https://github.com/gisinternals/buildsystem/issues/84
I requested a status update.
