### ISSUE TITLE
DrawPolygon Crash in MFC

### ISSUE THREAD

**Issue by LiGuojun1990** [MapWindow/MapWinGIS#211]
m_Map.ClearDrawings();
	long handle = m_Map.NewDrawing(mapWindow::PROJECTION_WGS84);

	double projx[5], projy[5];
	CRect rect;
	GetClientRect(&rect);
	m_Map.PixelToProj(0, 0, projx, projy);
	m_Map.PixelToProj(rect.Width() / 2, 0, projx + 1, projy + 1);
	m_Map.PixelToProj(rect.Width() / 2, rect.Height() / 2, projx + 2, projy + 2);
	m_Map.PixelToProj(0, rect.Height() / 2, projx + 3, projy + 3);
	m_Map.PixelToProj(0, 0, projx + 4, projy + 4);
	
	SAFEARRAYBOUND bound;
	bound.lLbound = 0;
	bound.cElements = 5;
	SAFEARRAY *psaX = SafeArrayCreate(VT_R8, 1, &bound);
	SAFEARRAY *psaY = SafeArrayCreate(VT_R8, 1, &bound);
	for (int i = 0; i < 5; i++)
	{
		long ind = i;
		SafeArrayPutElement(psaX, &ind, projx + i);
		SafeArrayPutElement(psaY, &ind, projy + i);
	}

	VARIANT varX, varY;
	VariantInit(&varX);
	VariantInit(&varY);
	varX.vt = VT_ARRAY | VT_R8 | VT_BYREF;
	varY.vt = VT_ARRAY | VT_R8 | VT_BYREF;

	varX.pparray = &psaX;
	varY.pparray = &psaY;

	m_Map.DrawPolygonEx(handle, &varX, &varY, 5, RGB(0, 0, 255), TRUE, 100);  // crash!!!

	m_Map.Redraw();

**Comment by LiGuojun1990** [comment]
Map_DispatchMap.cpp line 190 
"DISP_FUNCTION_ID(CMapView, "DrawPolygonEx", dispidDrawPolygonEx, DrawPolygonEx, VT_EMPTY, VTS_I4 **VTS_VARIANT VTS_VARIANT** VTS_I4 VTS_COLOR VTS_BOOL VTS_UI1)"  --> 
"DISP_FUNCTION_ID(CMapView, "DrawPolygonEx", dispidDrawPolygonEx, DrawPolygonEx, VT_EMPTY, VTS_I4 **VTS_PVARIANT VTS_PVARIANT** VTS_I4 VTS_COLOR VTS_BOOL VTS_UI1)"

**Comment by jerryfaust** [comment]
Hello @LiGuojun1990 

I see the differences in the function definition; although I don't see it in source control history.  Where did the second definition come from, that shows pointers to the Variants (VTS_PVARIANT)?

Regards,
Jerry.

**Comment by LiGuojun1990** [comment]
I mean VTS_VARIANT  should be corrected to VTS_PVARIANT. >_<

**Comment by LiGuojun1990** [comment]
I mean VTS_VARIANT  should be corrected to VTS_PVARIANT. >_<
