### ISSUE TITLE
can not run application with debug

### ISSUE THREAD

**Issue by songxiang** [MapWindow/MapWinGIS#213]
I created a window program with vs2017, and then added a mapcontrol according to the tutorial (tutorial address: https://www.mapwindow.org/documentation/mapwingis4.9/getting_started.html). It can run normally when debugging, but it fails when I copy all the files under debug to other computers. The error message is: Error module name: KERNELBASE.DLL, version 10.0.19041.1151

**Comment by jerryfaust** [comment]
Have you installed the msvc Debug dlls on the other machine?  The MapWinGIS installer will only install the Release runtime.  You might find them here?
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\14.16.27012\debug_nonredist\x86

Or you could do a Release build and put those files on the other machine.

Regards,
Jerry.

**Comment by songxiang** [comment]
Thanks!!! The program can run normally when MapWinGIS is installed and registered on the other machine.
