### ISSUE TITLE
May invalid SpatialIndex file(.mwd\.mwx) cause shape file not display correctly.

### ISSUE THREAD

**Issue by ningfc** [MapWindow/MapWinGIS#216]
I have a shape file here -> [Export_OutputCopy.zip](https://github.com/MapWindow/MapWinGIS/files/7553382/Export_OutputCopy.zip)
I add this file to MapWIndow5 and didn't display correct, may be spatial index file not generate incorrect, because it will be display correct after delete the *.mwd file, and if restore the *.mxd before, the problem back again.

**Comment by pmeems** [comment]
I just tested with the dev-version and that version shows this result with the original mwd and mwx files:
![image](https://user-images.githubusercontent.com/12067729/154512785-d856160e-d560-4ff8-8620-9b0864756481.png)
And this result without them:
![image](https://user-images.githubusercontent.com/12067729/154513185-5cf41fbb-b379-475c-890b-971330b78f0d.png)

So something is definitively wrong.

I created https://mapwindow.atlassian.net/browse/MWGIS-303 for this an will try to fix this.
