### ISSUE TITLE
Line patterns with markers do not work properly

### ISSUE THREAD

**Issue by frank2x460** [MapWindow/MapWinGIS#218]
Hello,

since Version 5.2.4 creating linepattern with markers does not work predictable, sometimes the markers appear, sometime they do not.
I verified it with the mapwingis examples app (see attachment) . The error occurs even with the newest version 5.3.0. Using 5.1.1.1 everything is fine.
Please have a look at the code.

Thanks
Frank
![error_linepattern_with_markers](https://user-images.githubusercontent.com/34651007/150493321-4ab2357f-6864-446b-bd90-cdb30798cdc2.jpg)

**Comment by pmeems** [comment]
This is further discussed at the forum: https://mapwindow.discourse.group/t/line-patterns-with-markers-do-not-work-properly/1217

The issue has been logged at https://mapwindow.atlassian.net/browse/MWGIS-255

**Comment by jerryfaust** [comment]
The change has been submitted to the 'develop' branch, and MWGIS-255 has
been marked as 'Done'.

Thank you, Frank.
