### ISSUE TITLE
how to add geometry filed from sql server 2014 to layers

### ISSUE THREAD

**Issue by nikolaspapa** [MapWindow/MapWinGIS#22]
pleas help me to read a data from sql server geometry data field

**Comment by pmeems** [comment]
Did you look at some of the API documentation, like http://www.mapwindow.org/documentation/mapwingis4.9/class_file_manager.html#a6454319829fa91ed7e2c453fcc769827

**Comment by pmeems** [comment]
Do you still have questions or can we close this issue?

**Comment by pmeems** [comment]
Closing this old question
