### ISSUE TITLE
Selecting Shapes (Access2000/VBA)

### ISSUE THREAD

**Issue by Moesulor** [MapWindow/MapWinGIS#23]
Hi there,

Im actually developing an interactive map in combination with an existing database/table. Im sorry i have to say that im still learning VBA - but i would really appreciate some help.
I made it that i can choose some shapefile to load into the map. Im able to label features and change the layout. Furthermore its possible to go through the linked Recordsets and autozoom to the corresponding shape.

What i now want to do is 
 - select a shape (and change the layout of selected one)
 - jump to the corresponding record of the table (which is datasource of the form)

I did not figure out how to select a shape via mouseclick. Changing the Cursormode to cmSelection seems to be not enough (Im able to select all shapes via code (`Form_frm_MOtest.Karte1.GetObject(0).SelectAll`).

Access gives me a MouseDown and MouseUp options for an interaction with mouse, but a messagebox does not appear with following code:
```
Private Sub Karte1_MouseDown(ByVal Button As Integer, ByVal Shift As Integer, ByVal x As Long, ByVal y As Long)
 MsgBox("Halleluja")
```
Well but nothing happens there when im clicking. When im using `Private Sub Karte1_DblClick()` the messagebox appears, but i dont have variables to work with...

**Comment by Moesulor** [comment]
It's so easy when you know.. I just have to enable the event via  `Karte1.SendMouseUp = True`

**Comment by pmeems** [comment]
I'm glad you figured it out.
You should also be able to set these settings in the property panel of the map control.
