### ISSUE TITLE
Mousedown/up-event -> selecting shape (VBA/Access2000)

### ISSUE THREAD

**Issue by Moesulor** [MapWindow/MapWinGIS#24]
Hello there.
Im trying to find out how to select a shape via mouseclick. Actually i decided to use the Mouseup-Event - but now im stuck in transferring the coordinates to the void AxMap.PixelToProj (I'm not even sure that this is the right way).
Anyway - with `Private Sub Karte1_MouseUp(ByVal Button As Integer, ByVal Shift As Integer, ByVal x As Long, ByVal y As Long)` i get the mouseposition in relation to the control's origin ("[...] coordinate of mouse cursor position in pixels relative to control's origin.") as a long integer.
To do` AxMap.PixelToProj ` i need to input a double of some other source then quoted about.

Someone could give me tip how i could solve this better?

This is the whole code of my Sub (which doesnt work ;)):
(
```
Private Sub Karte1_MouseUp(ByVal Button As Integer, ByVal Shift As Integer, ByVal x As Long, ByVal y As Long) 
  Dim sf As MapWinGIS.Shapefile
  Dim i As Integer
  Dim Pixx, Pixy, Prox, Proy As Double
  
  Set sf = Form_frm_MOtest.Karte1.Shapefile(0)
  Pixx = CDbl(x)
  Pixy = CDbl(y)
  
  Debug.Print ("Pixx=" & Pixx & "/" & "Pixy=" & Pixy)
  
  If Karte1.CursorMode = tkCursorMode.cmSelection Then
    Debug.Print (Button & " " & Shift & " " & x & " " & y)  '<-this one works
    Call Karte1.PixelToProj(Pixx, Pixy, Prox, Proy)
    Debug.Print (Prox & "/" & Proy)
      'If sf.PointInShapefile(x, y) = True Then
      
     ' End If
  End If
  'Call ZoomToShapeByClick
End Sub
```

**Comment by Moesulor** [comment]
Well night slept and now im one step closer.
Changed some things in the code and its transfers now the Coordinates to the right type(Lat &Lng).
I thought i would just have to use `PointinShape(file)`  and call `ZoomToShape` now - but it doesnt work properly because the PointInShape(file) does not find a shape for the Coordinates converted (I checked the Output Coordinates manually and they definitly fit into a polygon).
Here is my Code againwith option 1(PointInShapeFile) and option 2(PointInShape):

```
Private Sub Karte1_MouseUp(ByVal Button As Integer, ByVal Shift As Integer, ByVal x As Long, ByVal y As Long) '"Button" definiert die Maustaste, "Shift"= shift oder ctrl gedrückt
  Dim sf As MapWinGIS.Shapefile
  Dim handle As Integer
  Dim Pixx As Double
  Dim Pixy As Double
  Dim Degx As Double
  Dim Degy As Double
  Dim Shapeind As Integer
  Dim i As Integer
   
  
  If Karte1.CursorMode = tkCursorMode.cmSelection Then
    Set sf = Form_frm_MOtest.Karte1.Shapefile(0)
    Pixx = CDbl(x)
    Pixy = CDbl(y)
    handle = Form_frm_MOtest.Karte1.AddLayer(sf, True)
  
    'Debug.Print (Button & " " & Shift & " " & x & " " & y)
    Call Karte1.PixelToDegrees(Pixx, Pixy, Degx, Degy)
    Debug.Print (Degx & "/" & Degy)
    
    
      'First Option:
    'Shapeind = sf.PointInShapefile(Degx, Degy)
    'Debug.Print Shapeind
    '  If Shapeind > -1 Then
    '    Call Karte1.ZoomToShape(handle, Shapeind)
    '    Else
    '    MsgBox ("No Shape found! Shapeindex: " & Shapeind)
    '  End If
      
      
      'Second option:
    'For i = 0 To sf.NumShapes - 1
    '  If sf.PointInShape(i, Degx, Degy) = True Then
    '    Call Karte1.ZoomToShape(handle, i)
    '    Debug.Print i
    '    Exit Sub
    '  End If
    '  Debug.Print i
    'Next i
  End If

End Sub
```

**Comment by pmeems** [comment]
Does zoomToSelected not help you:
http://www.mapwindow.org/documentation/mapwingis4.9/group__map__interaction.html#ga4a459d070c6d8e68cad73b179a63bb41

You can also try this:
```
axMap1.ShapeIdentified += new AxMapWinGIS._DMapEvents_ShapeIdentifiedEventHandler(this.axMap1_ShapeIdentified);
axMap1.CursorMode = tkCursorMode.cmIdentify;
private void axMap1_ShapeIdentified(object sender, AxMapWinGIS._DMapEvents_ShapeIdentifiedEvent e)
{
    axMap1.ZoomToShape(e.layerHandle, e.shapeIndex);
}
```
I tested it in a small app and it is working.

**Comment by pmeems** [comment]
This example might also help:
http://www.mapwindow.org/documentation/mapwingis4.9/_remove_shape_8cs-example.html
It is deleting a shape after selecting, but you can rewrite it to select and zoom to the shape.

**Comment by pmeems** [comment]
Closing this old question
