### ISSUE TITLE
TilesAreInCache cant find?

### ISSUE THREAD

**Issue by bouvin87** [MapWindow/MapWinGIS#25]
Downloaded the latest version but i cant use this? Is there any other way to tell if the tile is loaded?

**Comment by bouvin87** [comment]
I tried to download version 4.9.1 there the function is but in 4.9.4.3 the function is remove. Why? How can i use a simular function?

**Comment by pmeems** [comment]
I'm looking into this. I'll get back to you on this.

**Comment by pmeems** [comment]
TilesAreInCache was removed when support for WMS was added.
You can now use the method map.LoadTilesForSnapshot(): http://www.mapwindow.org/documentation/mapwingis4.9/class_ax_map.html#a8b07f48dcda5d78818a6f5cfabf7e234 and the event TilesLoaded: http://www.mapwindow.org/documentation/mapwingis4.9/group__map__events.html#ga30aa5d8a6e0953c3b8b5d3f8b721edfb
We don't have any sample code (yet). If you want you can send me your working code and I'll add it to the documentation.

**Comment by bouvin87** [comment]
I dont think this will help me know when the tiles are loaded or not. Couse if the tiles are already loaded the TilesLoaded event wont fire.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
