### ISSUE TITLE
End select by polygon

### ISSUE THREAD

**Issue by guenlm** [MapWindow/MapWinGIS#27]
How can I finish a selectbypolygon in VBA Access to have the event SelectBoxFinal ? It work's with cmSelection but I don't find the good way to use SelectByPolygon (I tried right click, CTRL+click...no success...) Thank's a lot.

**Comment by pmeems** [comment]
Did you already set SendSelectBoxFinal to True.
Here's an C# example how to use the select  box:
http://www.mapwindow.org/documentation/mapwingis4.9/_select_box_8cs-example.html

**Comment by guenlm** [comment]
Hi, thank's for the answer but yes, SendSelectBoxFinal=true...and I tried to follow the example...

**Comment by guenlm** [comment]
Hello
Is-it possible to have en example in VBA ACCESS for the identifer tool with multiple layers (mapwingis.identifier, chooselayer, identifiermode=imSingleLayer) and selectbypolygon because it doesn't works for me..?
thank's a lot
Guen

**Comment by guenlm** [comment]
it seems that identifier.ActiveLayer does not exist in VBA ACCESS with the latest version of mapwingis.ocx

**Comment by pmeems** [comment]
Could you check the latest version, published yesterday: https://github.com/MapWindow/MapWinGIS/releases

If it is still not working we need to look closer.

**Comment by guenlm** [comment]
sorry I opened another issue for the same subject... (you can delete it). but... 
I still have the problem with the last version 4.9.5.0.
identifier.ActiveLayer doesn't exist in VBA so I can't give the handle of active layer which is used with the identifier tool...
I always have LayerHandle=-1 and shapeIndex=0 with AxMap_ShapeIdentified
and selectbypolygon still doesn't work on VBA...
Is somebody have an example of such code in VBA ?
Thank's.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
