### ISSUE TITLE
Drawing on a Drawing Layer that has been removed does not generate an error

### ISSUE THREAD

**Issue by MarkCupitt** [MapWindow/MapWinGIS#29]
I have this code

```
Dim Map_Nav As New AxMap
Map_Wind_Handle = Map_Nav.NewDrawing(tkDrawReferenceList.dlScreenReferencedList)
Dim utils As New Utils
Map_Nav.DrawLineEx(Map_Wind_Handle, 400, 400, 500, 500, 10, utils.ColorByName(tkMapColor.Blue))
Map_Nav.MoveLayerTop(Map_Wind_Handle)
Map_Nav.Refresh()
Map_Nav.Redraw()
```

The info for the window is: -		System.Drawing.Rectangle{X = 0 Y = 0 Width = 920 Height = 894}	

The line refuses to show on the layer

Would really appreciate any help, the coordinates given do fall in the window bounds, IM sure Im missing something obvious .. but cannot see it ..

**Comment by MarkCupitt** [comment]
This is directly related to #28 .. my problem was the ClearDrawing was removing the layer but no error generated drawing to a nonexistent drawing layer.

So this code immediately after drawing on the layer was giving

```
            Dim b = Map_Nav.LastErrorCode
            Dim c = Map_Nav.get_ErrorMsg(Map_Nav.LastErrorCode)
```

```
b=1202
c="No Error"
```
If the layer was destroyed, then there should be an error generated ..

**Comment by pmeems** [comment]
Did you have a look at the examples mentioned here: http://www.mapwindow.org/documentation/mapwingis4.9/group__map__drawing__layers.html#gacbd4270e2ee82c97def2d169f54bb518

**Comment by MarkCupitt** [comment]
Yes, I used them .. If I just add the layer I can draw, if I clear the layer, then it will not draw. Drawing on a nonexistant layer (after clearing it) returns error code 1202 with Description "No Error"

**Comment by pmeems** [comment]
Is this still an issue with the latest version of MapWinGIS?

I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)

**Comment by jerryfaust** [comment]
This is no longer an issue with the latest code.  When drawing to a removed (Cleared) drawing layer, the call returns -1, as it should, and the error code/string indicates an invalid layer handle.
