### ISSUE TITLE
Documentation files not available?

### ISSUE THREAD

**Issue by dgreenewalt** [MapWindow/MapWinGIS#3]
I can't find documentation files for MapWinGIS.  I would also like to see new features and fixes for the latest release.  I have tried the web site, CodePlex, and don't see anything on GitHub.  Where should I look for information/discussion.

**Comment by pmeems** [comment]
Did you look at http://www.mapwindow.org/documentation/mapwingis4.9/index.html

**Comment by dgreenewalt** [comment]
Thanks Paul, got it.  The link from MapWinGIS.com wasn't working and I didn't know where to look on github.  Is this the discussions section or just for issues?

**Comment by pmeems** [comment]
GitHub doesn't seems to have a discussion section. You can use this section for discussions as well. 'Real' issues will be copied to https://mapwindow.atlassian.net/secure/Dashboard.jspa
