### ISSUE TITLE
DrawLabelEx causes System.AccessViolationException

### ISSUE THREAD

**Issue by MarkCupitt** [MapWindow/MapWinGIS#30]
I have the following Code that causes an Uhandled Exception on the Map_Nav.Refresh() (VS2015)

```
Dim Map_Nav as new AxMap
Map_Wind_Handle = Map_Nav.NewDrawing(tkDrawReferenceList.dlScreenReferencedList)
Map_Nav.DrawLabelEx(Map_Wind_Handle, "Wind: 150/30", ox2, oy2, 90)
Map_Nav.refresh()
```
(ox2, oy2 are screen coordinates that are in the current Map Window)

Error issues by VS2015:

```
An unhandled exception of type 'System.AccessViolationException' occurred in System.Windows.Forms.dll

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

I am totally stuck .. Is there something I am missing?

**Comment by MarkCupitt** [comment]
I see #5 was closed without a solution and is the same issue, as well #12 was reported but they used a shapefile to add the labels so it appears to be unresolved.

**Comment by pmeems** [comment]
Is this still an issue with the latest version of MapWinGIS?

I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)

**Comment by jerryfaust** [comment]
I have confirmed that this is no longer an issue.
