### ISSUE TITLE
Cannot merge two PointM shapefiles

### ISSUE THREAD

**Issue by ghost** [MapWindow/MapWinGIS#31]
Hi,

I'm trying to merge 2 simple points shapefile. The shapefiles are of type "PointM". I've attached a ZIP file containing the same dataset but in PointM format and Point format. [PointM_vs_Point.zip](https://github.com/MapWindow/MapWinGIS/files/1136944/PointM_vs_Point.zip)

The merge works well with the Point format, but crashes with the PointM format. The error is: 

> An unhandled exception of type 'System.AccessViolationException' occurred in System.Windows.Forms.dll
> 
> Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Here's the code I run inside a C# console application. You can use the shapefiles provided with this post to replicate.

```
string shp1 = @"C:\Users\kevin.cote\Desktop\DATASET\shp1_point_m\SHP1_POINT_M.shp";
string shp2 = @"C:\Users\kevin.cote\Desktop\DATASET\shp2_point_m\SHP2_POINT_M.shp";
//string shp1 = @"C:\Users\kevin.cote\Desktop\DATASET\shp3_point\SHP3_POINT.shp";
//string shp2 = @"C:\Users\kevin.cote\Desktop\DATASET\shp4_point\SHP4_POINT.shp";

string output = @"C:\Users\kevin.cote\Desktop\DATASET\output\output.shp";

Shapefile sf_shp1 = new Shapefile();
sf_shp1.Resource(shp1);

Shapefile sf_shp2 = new Shapefile();
sf_shp2.Resource(shp2);

Shapefile new_sf = sf_shp1.Merge(false, sf_shp2, false);
new_sf.SaveAs(output);
```

What is causing this error ?

**Comment by pmeems** [comment]
I can confirm the crash.
I've created a new issue at https://mapwindow.atlassian.net/browse/MWGIS-69
When I have some time I'll have a look at it.

**Comment by pmeems** [comment]
This has been fixed in the new installer.
Get if from https://github.com/MapWindow/MapWinGIS/releases
