### ISSUE TITLE
Building MapWinGIS with Visual Studio 2015

### ISSUE THREAD

**Issue by dhuantes** [MapWindow/MapWinGIS#32]
I just successfully built a 64 bit MapWinGIS.ocx with Visual Studio 2015 and was able to register it.   Is there an updated set of documentation of how to do this....  Specifically I'm not sure I got all the gdal dependencies.  Seems like everyone that does build gdal does so with their specific needs.  I built it with curl, geos, libjpeg, libpng, tiff, and zlib.  Not sure this is sufficient for all MapWindow supported file formats.    I also downloaded and/or built everything in the C:\dev\MapWinGIS\support\build\HowToBuild.txt.  If there is not an update document, I'll look at building something.  I was hoping to CMake everything but not every project provides CMake support.  Thank you.

**Comment by pmeems** [comment]
We normally use the pre-build binaries from gisinternals.com because it is quite difficult to compile GDAL yourself.
The HowToBuild.txt is probably a bit out-dated by now. Please update it.

**Comment by dhuantes** [comment]
I was hoping to do the same but gisinternals.com latest version was compiled with VS2013.  Is there a good set of data files that I could test with MapWindow to make sure that everything I need is in MapWinGIS.ocx?

**Comment by pmeems** [comment]
We have a data repo on Codeplex you can use:
http://gisdata.codeplex.com/SourceControl/latest
In the MapWinGIS repo we also have a small C# app called Unittests which is a bit more than just unit tests and it will test some MapWinGIS functions and also has a small form which some options.
If needed you can add more tests.

**Comment by weskerjiang** [comment]
hello,may i ask how to build MapWinGIS with VS2015? i download the GDAL release-1900 version and put it in the v140 folder,but still failed

**Comment by pmeems** [comment]
Did you already watch this video tutorial: https://www.youtube.com/watch?v=WVQaFsil0bY

**Comment by pmeems** [comment]
Closing this old question.
