### ISSUE TITLE
Russian is not supported

### ISSUE THREAD

**Issue by Waleryth** [MapWindow/MapWinGIS#33]
Hello! Sorry for my English. Do you speak Russian?
I'm trying to create labels on the map from my Shapefile, but it turned out that the encoding of the Russian language is not supported.
It is also not possible to create character categories by attribute from the database.
Did this:
`var gs = new GlobalSettings();
 gs.OgrStringEncoding = tkOgrEncoding.oseUtf8;`
The result did not.
What can I do?

**Comment by Waleryth** [comment]
![123](https://user-images.githubusercontent.com/30282010/28352636-66e235f8-6c79-11e7-99de-26acf03fee41.png)

**Comment by pmeems** [comment]
Can you attach a sample shapefile (.shp, .dbf & .shx) so we can reproduce?

**Comment by Waleryth** [comment]
Shapefile in zip file
[shp.zip](https://github.com/MapWindow/MapWinGIS/files/1158532/shp.zip)

**Comment by pmeems** [comment]
I've created https://mapwindow.atlassian.net/browse/CORE-199 for this.
When we have time we will have a look at it.

**Comment by Waleryth** [comment]
How do I get the updated MapWinGIS.ocx?
With changes to CORE-199
Thank you!

**Comment by Waleryth** [comment]
How do I get the updated MapWinGIS.ocx?
With changes to CORE-199
Thank you!

**Comment by pmeems** [comment]
I'm not yet finished with this. I first need confirmation that my fix is correct, from an experienced C++ developer since I'm a newbie with C++. I've asked Sergey to have a look.
And I need to look at the categories as well because they don't work yet.
After that, I can send you a new version or you have to wait for the next official release.

**Comment by Waleryth** [comment]
Hello!
Thank you for solving the problem [https://mapwindow.atlassian.net/browse/CORE-199](https://mapwindow.atlassian.net/browse/CORE-199) - it is working!

I again compiled the MapWinGis project with your fixes and the ShapeFile label is working fine!
But, when I connect data from the SQL Server, the encoding of the Russian does not work again.

Encoding ShapeFile - works!
![1](https://user-images.githubusercontent.com/30282010/28521956-d323417c-7097-11e7-8e94-05624ba65bd9.png)


Encoding SQL server - does not work!
![2](https://user-images.githubusercontent.com/30282010/28521810-21a51614-7097-11e7-960f-f721662f3846.png)

**Comment by Waleryth** [comment]
How do I get the updated MapWinGIS.ocx?
With changes to CORE-199
Thank you!

**Comment by pmeems** [comment]
We're working on a beta release. Within a week we should have published it.
Or else you can compile the project yourself. All changes are in the development branch.

**Comment by pmeems** [comment]
Did you noticed we have published a new installer for MapWinGIS: https://github.com/MapWindow/MapWinGIS/releases
