### ISSUE TITLE
Change FillColor Shape in VBA

### ISSUE THREAD

**Issue by mmmakka** [MapWindow/MapWinGIS#35]
All, 

I use Excel and VBA with the latest version of MapWinGIS. 

I like to show different shapes (cities, polygon regions) in different colors and at the same time I like to set the transparency of the fill color. 
Although I can iterate through all shapes, I do not succeed in changing the FillColor of the different shapes, with different colors per shape. I tried almost everything I can imagine but with no success. I keep getting all sorts of error messages going from "needs object", to "method does not support this method". 

1) Methods like ShapeFillColor do not longer exist I think. 
2) solutions with ShapefileCategories block on the part when I want to add the category , e.g. "ctOrange = sf.Categories.Add(strOrange)" 
3) I even forgot the last one ;) 

Does anyone have an idea what I am doing wrong? Or even better, does anyone have an example how this can work?

Kind regards 
Mark

**Comment by pmeems** [comment]
Hi Mark,

With sf.DefaultDrawingOptions you can set the fill transparency. Please have a look at http://www.mapwindow.org/documentation/mapwingis4.9/class_shapefile.html#ab50d2c01b4848368852ea87cbcf6e5d4

This example also might help you understand the concept of the categories better:
http://www.mapwindow.org/documentation/mapwingis4.9/_add_category_range_8cs-example.html

**Comment by pmeems** [comment]
Closing this old question.
