### ISSUE TITLE
Labels or Legend for uniquevalues in Categories/scheme colour

### ISSUE THREAD

**Issue by angelmarichal** [MapWindow/MapWinGIS#36]
Good afternoon everyone:
I am using the latest version of Mapwingis with VBA, to represent polygon in regions with different colors, with the help of Categories and Schemas. As these zones correspond to shapes that are all together, they appear well differentiated with their color.

This code works:
**X= OBJETO.AddLayerFromDatabase("PARCELAS.DBF", "SELECT * FROM PARCELAS", True)
OBJETO.LayerName(CAPA) = "PARCELARIO"
Set SF = Visor.Shapefile(CAPA)
SF.DefaultDrawingOptions.FillType = ftStandard 
SF.Categories.Generate 2, ctUniqueValues, 0 
SF.Categories.ApplyExpressions
SF.Labels.GenerateCategories 2, ctUniqueValues, 0
Set esquema = New ColorScheme
esquema.SetColors2 tkMapColor.Yellow, tkMapColor.red
SF.Categories.ApplyColorScheme tkColorSchemeType.ctSchemeGraduated, esquema**

![categories](https://user-images.githubusercontent.com/30799640/29087765-f9dccdfa-7c6e-11e7-80fc-f7487418e4ba.png)
1- I need to generate labels, and to be able to put the name of the zone (value of field nº2) in the center of each one, I mean, to put in a unique name of the colored zones. A single label for each category,

2- Another alternative that the state tries to implement is to use a legend, but I do not know if it is possible to make it compatible with the application of categories.

I am new to this and would appreciate a lot of guidance on the issues, since I work in VBA and it is not easy for me to get examples with code.

Thank you very much in advance, and excuse my English.

Angel

**Comment by pmeems** [comment]
How far did you get with your application?
Do you still need help with these questions?
Here's an example about adding labels: http://www.mapwindow.org/documentation/mapwingis4.9/_generate_labels_manually_8cs-example.html

A legend is more complicated.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
