### ISSUE TITLE
Selection

### ISSUE THREAD

**Issue by Waleryth** [MapWindow/MapWinGIS#37]
Hello!
I want to selection objects on the map with a polygon, but I do not get anything.
If I do **tkCursorMode.cmSelection** - then everything works.
```
            Map.CursorMode = MapWinGIS.tkCursorMode.cmSelection;
            Map.SendSelectBoxFinal = true;
```
**tkCursorMode.cmSelectByPolygon** -  it does not work for me.
How can I do it?
Thank you!

**Comment by pmeems** [comment]
For references, an example of how to use a selectbox:
http://www.mapwindow.org/documentation/mapwingis4.9/_select_box_8cs-example.html

When you go to http://www.mapwindow.org/documentation/mapwingis4.9/_enumerations_8cs.html#a988ad29d268eb5a035739d90080581d3
You'll see 

> cmSelectByPolygon: Selects shapes of a single vector layer with the interactively drawn polygon. AxMap.ChooseLayer event must be handled to select the layer.

I did a quick search in the MW5 source code but can't see why it shouldn't work.
Have you selected a layer? Can you share a bit more code?

**Comment by Waleryth** [comment]
Hello!
I develop my application based on MapWinGIS to view a large amount of data on a map. I need to implement a selection of objects on the map. I selected objects using 
`MapWinGIS.tkCursorMode.cmSelection; 
`
I was able to implement them.

But sampling with
`MapWinGIS.tkCursorMode.cmSelectByPolygon`
 I do not know how to do it.
Tell me how can I do this?

I sent out my example of the program! Look here please!
[Selection1.zip](https://github.com/MapWindow/MapWinGIS/files/1276016/Selection1.zip)

I used MapWinGIS.ocx and MWLite.Symbology.dll on NetFrameork 4.0.
Thank You!

**Comment by pmeems** [comment]
I missed your reply. 
Do you still have this question?

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
