### ISSUE TITLE
Legend control in VBA form for MapWinGIS 4.9.3: References?

### ISSUE THREAD

**Issue by angelmarichal** [MapWindow/MapWinGIS#38]
Good afternoon:

I am trying to use the Legend control on a Microsoft Access 2007/2010 form. I try to add references of  MapWinInterfaces.dll to the project, but it is not possible.

I wanted to know if there is any way to use in MapWinGIS 4.9.3, the Legend control (as in previous versions), and if not, some alternative formula to incorporate a similar operation to the example SplitByAttribute.cs, but that allows to mark and unmark Layers / selections.
Thank you very much, and best regards.

Ángel

**Comment by pmeems** [comment]
MapWinInterfaces.dll is for MW4 and is very old.
What do you want to do? Can't it be solved using a plug-in?

If a plug-in is not an option you can have a look at the small demo application that is in the MapWinGIS repository. Its code is available at https://github.com/MapWindow/MapWinGIS/tree/develop/demo

**Comment by angelmarichal** [comment]
Thank you very much for your response, Paul.

The only thing I want to do is to be able to work with a legend component, as in MW4. Incorporate a control into an Access form, and control the layers and categories, display and hide them (checking and unchecking them), and deploy them as if in a tree if possible. My knowledge is not very advanced, but I would like to be able to do it in VBA with a control (if it exists) or by programming, and tell me where I can concretely achieve something like that.

Thank you very much again.

Angel

**Comment by pmeems** [comment]
We don't ship a separate legend control anymore. You can have a look at the demo how it was implemented and rewrite it for VBA.

**Comment by pmeems** [comment]
I'm closing this old question.
