### ISSUE TITLE
axMap.DrawLabel problem

### ISSUE THREAD

**Issue by pmeems** [MapWindow/MapWinGIS#39]
_From @jan-sv on September 12, 2017 9:42_

[Form1.cs.txt](https://github.com/MapWindow/MapWindow5/files/1295446/Form1.cs.txt)
![error1](https://user-images.githubusercontent.com/31884101/30318824-d7ba63d2-97b6-11e7-8f69-b31f28114931.jpg)
I am using precompiled MapWinGis version 4.9.4.2 with Delphi7, Vs2013 VB and VS2013 C#
I have attached C# example
When I comment line with DrawLabel statement , all is Ok.  when uncomment this line, project crashes.

_Copied from original issue: MapWindow/MapWindow5#16_

**Comment by pmeems** [comment]
I can confirm the crash.
I created https://mapwindow.atlassian.net/browse/MWGIS-79 for this.

**Comment by pmeems** [comment]
I've committed a fix.
The problem is that the code is checking the number of shapes on the map for scaling of the labels.
It didn't expect to have a map without any shapes. 
As a workaround, you can add a dummy shapefile layer with just a point.

**Comment by BrendanM-RSA** [comment]
Paul I have tried the workaround with no success. Here is a VB snippet to reproduce .... uncomment the last line

Dim SF1 As New Shapefile
Dim SH As MapWinGIS.Shape

Private Sub Form_Load()
    Map1.Projection = PROJECTION_WGS84
    Map1.Latitude = 0
    Map1.Longitude = 0
    Map1.CurrentZoom = 10
    
    ' add layer
    Call SF1.CreateNewWithShapeID("", SHP_POLYGON)
    Call Map1.AddLayer(SF1, True)
    
    ' create triangle poly
    Set SH = New MapWinGIS.Shape
    SH.Create (SHP_POLYGON)
    Call SH.AddPoint(0, 0)
    Call SH.AddPoint(1, -3)
    Call SH.AddPoint(-1, -3)
    Call SH.AddPoint(0, 0)
    SF1.DefaultDrawingOptions.FillColor = vbRed
    Call SF1.EditAddShape(SH)
    
    ' add drawing layer and circle with its own label
    Call Map1.NewDrawing(dlSpatiallyReferencedList)
    Call Map1.DrawCircle(0, 0, 0.1, vbYellow, True)
    'Call Map1.DrawLabel("ABC", 0, 0, 0)
    
    Map1.Redraw
End Sub

**Comment by pmeems** [comment]
I converted the VB code to C# and used it on the dev version:

            axMap1.Projection = tkMapProjection.PROJECTION_WGS84;
            axMap1.Latitude = 0;
            axMap1.Longitude = 0;
            axMap1.CurrentZoom = 10;

            // Add drawing layer and circle with its own label
            axMap1.NewDrawing(tkDrawReferenceList.dlSpatiallyReferencedList);
            var utils = new Utils();
            axMap1.DrawCircle(0, 0, 0.1, utils.ColorByName(tkMapColor.Yellow), true);
            axMap1.DrawLabel("ABC", 0, 0, 0);

This is the result:
![image](https://user-images.githubusercontent.com/12067729/32698249-85661ec0-c7a2-11e7-99aa-94aa202157d1.png)

This dev version will be release within a week as a beta.
Can you wait that long?

**Comment by BrendanM-RSA** [comment]
Sure that is not a problem. I presume that will be a full build with a Windows installer?

As a workaround I was thinking of using the SF.Labels.AddLabel method.

**Comment by pmeems** [comment]
Yes, it will be a full Windows installer.
SF.Labels.AddLabel should also work as a workaround.

**Comment by BrendanM-RSA** [comment]
Thanks. Already replaced all the Drawings like boxes and labels with a SF poly & labels. Perfect workaround. Did you see my suggestion on the WMSLayer in the new issue?
