### ISSUE TITLE
the ordinal 4445 not found in the DLL libcurl.dll

### ISSUE THREAD

**Issue by prostor777** [MapWindow/MapWinGIS#4]
Thank You for the excellent components. Help to fix the failure.
Previously I used the version 4.8.8. when migrating to version 4.9.4.2 began to receive the error. "the ordinal 4445 not found in the DLL libcurl.dll"

**Comment by pmeems** [comment]
How are you using MapWinGIS? In C++, C#?
Did you run the latest installer from GitHub? Did you run the installer as an Admin?
Are you using some specific code that is using libcurl?

Regards,
Paul

**Comment by prostor777** [comment]
I,m using Delphi XE2 as ActiveX component.
Installer - MapWinGIS v4.9.4.2-Win32. Windows 10Homex64
Error occurs when adding an ActiveX component on the form. No specific functions can not use, not even able to add a component

**Comment by pmeems** [comment]
We had in the past several Delphi users who needed to do some extra stuff to get MapWinGIS working in Delphi.

I see you also posted your question on CodePlex as an WorkItem: https://mapwingis.codeplex.com/workitem/26029
Perhaps you will get more help when you post it on CodePlex in the Discussion section.
