### ISSUE TITLE
OgrLayer editing in VBA

### ISSUE THREAD

**Issue by guenlm** [MapWindow/MapWinGIS#40]
Hello
Where I can find some examples of using shape editing on an OGR Layer in VBA (for Access) please ? I found some stuff on C++ but I don't manage to do the same thing in VBA...
Thank's
Guen

**Comment by pmeems** [comment]
Did you have a look at http://www.mapwindow.org/documentation/mapwingis4.9/index.html
The examples are in C#, but should easily be converted to VB(A).

**Comment by guenlm** [comment]
Yes Y saw all these examples but I am not able to translate them in VBA ...sorry... I saw the Shape Editor Class but I don't know how I can use it...in VBA...
If somebody had already done this job...thank's a lot !

**Comment by pmeems** [comment]
It's been over a decade ago since I use VBA.
But you can have a look at demo application. It is written in C# but it should give you some pointers how to use the functions of MapWinGIS.

**Comment by pmeems** [comment]
It's been a long time since the poster commented.
I'm closing this question.
