### ISSUE TITLE
Resizing map causes memory leak

### ISSUE THREAD

**Issue by ultraTCS** [MapWindow/MapWinGIS#41]
Hi, I'm using ocx v4.9.4.2.

Recently noticed big spikes in memory when resizing. I've reproduced this using MapWindow5.
Saw same issue reported here: https://mapwingis.codeplex.com/discussions/659779 and I've posted a follow-up to the original post.

I am building the ocx from source but have not yet investigated. Hoping it is a known issue with a known fix.

Thanks,
link

**Comment by pmeems** [comment]
I just tested it with MW5 (which is using the ocx) and I also see the increase of memory when I change the size of MW5 and thus the map control.
I've created https://mapwindow.atlassian.net/browse/MWGIS-87 for this.
We need to investigate this.

**Comment by jerryfaust** [comment]
A substantial GDI leak was detected in the RedrawLayers method, which is called on every resize operation, and a change is being submitted.

**Comment by ultraTCS** [comment]
Great news, thx Jerry.
