### ISSUE TITLE
PointInShapefile

### ISSUE THREAD

**Issue by IslandHydro** [MapWindow/MapWinGIS#42]
PointInShapefile(X,Y) returns a number which indicates the index of shapes within which a test point is situated.  This appears to return a single index.  How can I determine if the X,Y point falls within more than one shape?

**Comment by pmeems** [comment]
How do you mean? Within a shapefile you should not have shapes on top of each other. So the point cannot be in more than 1 shape.

**Comment by IslandHydro** [comment]
Why would you not have overlapping shapes?    Depending on the data displayed, it is perfectly reasonable to have overlying shapes.

**Comment by pmeems** [comment]
I just looked at the code and it stops when it has found a shape.
The method bool Shapefile.PointInShape(int ShapeIndex, double x, double y):
http://www.mapwindow.org/documentation/mapwingis4.9/group__shapefile__optimizations.html#gab2d91ceb77321117ceccaf8686188f67 is also available.

You could first do a SelectShapes(): http://www.mapwindow.org/documentation/mapwingis4.9/group__shapefile__selection.html#ga67c36f870d2db98b2c8515f43ef62ac3 with a large enough to find some shapes in the neighborhood of your point. Next, you check these shapes with PointInShape.
Perhaps you can first use PointInShapefile and use the extent of the found shape to find the other shapes.
That should work.

**Comment by jerryfaust** [comment]
This is in VB.NET, but something like this should work.

```
Public Function ShapesContainPoint(Layer As Shapefile, x As Double, y As Double, ByRef shapeIndexes As Object) As Boolean
    Dim ext As New Extents
    ' effectively a point-based extent
    ext.SetBounds(x, y, 0, x, y, 0)
    ' if True, shapeIndexes will be an array of shape indexes
    Return Layer.SelectShapes(ext, 0, SelectMode.INTERSECTION, shapeIndexes)
End Function
```

**Comment by IslandHydro** [comment]
Thanks Jerry, I'll give that a try.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
