### ISSUE TITLE
Feature request: WMSLayers extra parameter in base URL

### ISSUE THREAD

**Issue by BrendanM-RSA** [MapWindow/MapWinGIS#44]
I have got my application working well against 2 WMS services. One of the issues I came across was that the 1 WMS system needed an extra parameter passed to it. So a GetCapabilities would look like this:

http://506CMR/WMS/wms.asp?WMS=WorldMap&WMTVER=1.0.0&REQUEST=GetCapabilities

I needed the WMS=WorldMap parameter passed always. There is no way to do this in the current version of MapWinGIS because the base URL is always appended with a "?" and then GetCapabilities or GetMap etc. Then you get 2x "?" in the URL that goes to the WMS and it fails. So currently the base URL cannot contain any parameters of its own.

As a suggestion why don't you check if there is already a "?" in the base URL and then if it is present then use a "&" with GetCapabilities or GetMap for the extra parameters. So then my base URL would be:

http://506CMR/WMS/wms.asp?WMS=WorldMap

**Comment by pmeems** [comment]
I've created https://mapwindow.atlassian.net/browse/MW5CORE-205 for this.
When time permits I'll have a look.
Of course you can also provide a patch.

**Comment by mathijs-dumon** [comment]
Closing as indicated in Jira this is solved: https://mapwindow.atlassian.net/browse/MW5CORE-205
