### ISSUE TITLE
Non-square image does not centre on map correctly

### ISSUE THREAD

**Issue by BrendanM-RSA** [MapWindow/MapWinGIS#45]
I load a symbol image like this:

sf2.DefaultDrawingOptions.AlignPictureByBottom = False option
Set CT = sf2.Categories.Add("Base Station")
CT.DrawingOptions.PointType = ptSymbolPicture
Set img = New MapWinGIS.Image
img.Open App.Path & "\Layers\Base Station.png", , True
CT.DrawingOptions.Picture = img

The PNG image is 60 pixels wide and 85 pixels high. When it loads the image with CT.DrawingOptions.Picture then in the img properties the height and width are swapped around. This causes the image not to be centered on its mass when its is later placed on the map.

Here you can see the 2 values swapped around.

![image](https://user-images.githubusercontent.com/32435731/32726941-775f7a42-c883-11e7-94f0-9623513eac6d.png)

The img.extents seems to be correct:

![image](https://user-images.githubusercontent.com/32435731/32727000-ab2549c4-c883-11e7-8ce2-b5eb634c0192.png)

Obviously the workaround is to make sure one has a square image and not a rectangular one.

**Comment by jerryfaust** [comment]
Hello.
I stepped through the load of a PNG, and sure enough found an inadvertent swap of values.  I will see about getting a fix into the upcoming release.
Thanks.

**Comment by pmeems** [comment]
I created https://mapwindow.atlassian.net/browse/MWGIS-89 for this issue.

**Comment by jerryfaust** [comment]
The fix has been submitted.

**Comment by pmeems** [comment]
The fix is in the new installer.
Get if from https://github.com/MapWindow/MapWinGIS/releases
