### ISSUE TITLE
Multipolygon will exchange to polygon

### ISSUE THREAD

**Issue by wangxiya** [MapWindow/MapWinGIS#46]
I create shape, then importfromwkt. This is a multipolygon. But after import to shape, the multipolygon will exchange to polygon. I debug the code, I found the code in OgrConverter::GeometryToShape method:
for(long iRing = 0; iRing < nRings; iRing++ )	
		{
			oRing = papoRings[iRing];

			long ringPointsCount = oRing->getNumPoints();
			
			if (ringPointsCount > 0)
			{
				shp->InsertPart(count, &iRing, &retval);

				for (long i = 0; i < ringPointsCount; i++)
				{
					ComHelper::CreatePoint(&pnt);
					pnt->put_X(oRing->getX(i));
					pnt->put_Y(oRing->getY(i));
					if (isM)	pnt->put_M(oRing->getZ(i));
					else		pnt->put_Z(oRing->getZ(i));
					shp->InsertPoint(pnt, &count, &retval);
					pnt->Release();
					pnt = NULL;
					if (retval)
						count++;
				}
			}
		}

  when I use release mode compile, "if (ringPointsCount > 0) "pass, but " for (long i = 0; i < ringPointsCount; i++)"  can't run to "ComHelper::CreatePoint(&pnt);"
 it is strange！
 when I use debug mode  compile ，It debug correct！

Maybe I ignore something important？？？

**Comment by pmeems** [comment]
Can you share your code and the WKT? So we can have a look as well.
Which version of MapWinGIS are you using?

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
