### ISSUE TITLE
error:MSB3073 when build the MapWinGIS

### ISSUE THREAD

**Issue by weskerjiang** [MapWindow/MapWinGIS#48]
hello,i've done like the video on youtube with vs2013,GDAL 1800(x86 version),everything like the video,but the vs2013 shows the error 
error MSB3073: command “if Win32 == Win32 setx  MapWinGISBin32 E:\Administrator\Documents\Visual Studio 2013\Projects\MapWinGIS\src\bin\Win32\ 
if Win32 == x64 setx  MapWinGISBin64 E:\Administrator\Documents\Visual Studio 2013\Projects\MapWinGIS\src\bin\Win32\
:VCEnd” exits，code is 1。	
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	132	5	MapWinGIS

i use admin to open vs2013 and read the http://www.mapwindow.org/documentation/mapwindow5/compile.html
and set 'Register output' to No,it shows this error
if i set 'Register output' to YES,it shows "per-user ........"

so what's wrong with it?TKS

**Comment by pmeems** [comment]
Looking at this link (https://stackoverflow.com/questions/17075279/how-do-i-fix-msb3073-error-in-my-post-build-event) it seems the error means it can't find the files in needs to copy.
Have you checked the files exist? Perhaps you need to build twice? 
And are you running VS as admin? You should.

**Comment by pmeems** [comment]
I've just published a new installer for MapWinGIS.
Get if from https://github.com/MapWindow/MapWinGIS/releases

Using that installer might stop the need for building it on your own.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
