### ISSUE TITLE
 error MSB8011: Failed to register output

### ISSUE THREAD

**Issue by chaiwatt** [MapWindow/MapWinGIS#50]
I try to build mapwingis ocx follow vid 'MW5+MapWinGIS Build' (https://www.youtube.com/watch?v=WVQaFsil0bY). But I  got problem during building process (vs2013, admin mode)

Error 4 error MSB8011: Failed to register output. Please try enabling Per-user Redirection or register the component from a command prompt with elevated permissions.	C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	
1620  5 MapWinGIS.

So, I try to solve as below.

1. Run visual studio in administrator mode.
2. Change another computer.
3. Change windows (10 and 7).
4. Try other visual studio version (2017,2015 with matched gdal).
5. Disable user account control (Local security policy => Security options =>  User Account control : Run all administrator.... )

All these actions still getting the same error. So I try to skip ocx register by changed a properties (Linker => Register output => No). Then, I can built but fail on manual register. Pls help what I'm doing wrong, thanks.

here is screenshot
https://ibb.co/n45s3R
https://ibb.co/cvH5OR
https://ibb.co/mwBocm

**Comment by pmeems** [comment]
When you can compile without registering it means the compilation was successful.
When you can't register it means you are missing some dependencies.
Finding out which dependencies is very tricky. I use dependency walker for that.

**Comment by chaiwatt** [comment]
Dear pmeems, Thanks.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
