### ISSUE TITLE
New installer for MapWinGIS.

### ISSUE THREAD

**Issue by pmeems** [MapWindow/MapWinGIS#51]
Yesterday I created a new installer for MapWinGIS.
Please try it. Get if from https://github.com/MapWindow/MapWinGIS/releases

If you run into trouble you can post it here. We'll try to get back to you as soon as possible.

For the next few weeks we'll be working on updating the documentation and after that, we'll work on creating a new version of MapWindow5.

**Comment by chaiwatt** [comment]
Love your features update. Seem almost question was solved. But just found some bug,
- Old demo example still included. This example does not work on new release. 

(Error: System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'). 

Btw, not sure to effect to mapwindows which use same file.

- GoogleSatellite and GoogleHybrid provider does not render but Googlemap and GoogleTerrain work fine.

Other work great...

**Comment by BurkhartS** [comment]
Looks nice so far.
There seem to be some differences in the visualisation of geometries.
My first impression is that the map rendering is faster (maybe the loading of wms-layers via ogr is faster?).
Great work!

BUT: The legend doesn't work anymore. As soon as I add a layer to the legend the legend blanks out.
(So I had to switch back to 4.9.4.2)

Burkhart

**Comment by pmeems** [comment]
@BurkhartS Can you add a screenshot from the legend? And which legend are you talking about? The one in MW5?

**Comment by BurkhartS** [comment]
Hi Paul,
Yes, its the legend from MW5 (is there another around?).
I'll send you a screenshot in a few days. It is just 'crossed out'.

Burkhart

**Comment by pmeems** [comment]
When you are using MW5 you should not download and install the installer for MapWinGIS.
This is just the mapping component and is for people that create their own application using MapWinGIS.

We will publish a new maintenance release for MW5 soon with the latest MapWinGIS version, that will also solve the legend issue.

**Comment by BurkhartS** [comment]
Hi Paul,

okay, I was wrong (I believe).
I use the legend from MWLite (MWLite.Symbology.LegendControl.Legend).
I've taken a screenshot of the error. The Legend looks alright until I try to load a Layer into the Legend.
(How to send the screenshot??)
(Another issue: installing the new version on my citrix-client broke the citrix agent...)

Cheers
Burkhart

**Comment by pmeems** [comment]
Hi Burkhart,
I have not recompiled and published MWLite.
I'll see if I can do that shortly.

Your remark about the installer is more disturbing. Can you explain a bit more, so we can try to modify the installer to not break your citrix agent.

**Comment by BurkhartS** [comment]
Hi Paul,
regarding my installer-problem, I can't say anything helpful (as I am no administrator here).
I can just say, that after installing I couldn't start my citrix virtual desktop anymore and the administrator said, that the citrix-agent was broken. Maybe I can try and get more information about this, but it will take some time...

Cheers
Burkhart

**Comment by zontick** [comment]
Try MapWinGIS-only-v4.9.5.0-Win32.exe in windows7 x64 and MapWinGIS.ocx was not registered automatically. I registered it manually. I think it's because the installer wants to register 32х .осх through 64x Regsvr32.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
