### ISSUE TITLE
Web Map Service (WMS) with the ocx of mapwingis

### ISSUE THREAD

**Issue by cpalominoch** [MapWindow/MapWinGIS#53]
Dear.
Please What is an example code to use Web Map Service (WMS) with the ocx of mapwingis?

Best regards.

Carlos Palomino.

**Comment by pmeems** [comment]
Just to clarify:
MapWinGIS and the ocx are the same. MapWindow5 or MW5 is the .NET application that is using MapWinGIS.

At this moment we don't have an example with WMS. We are currently updating the documentation. I'll put it on the list to add a WMS example.

**Comment by BurkhartS** [comment]
Hi Carlos,
you can add WMS-layers via ogr.
I've done this in VB.NET. I've shown some code that should be helpful in another thread (don't know how to make a link here). Sure you will find it.

Cheers
Burkhart

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
