### ISSUE TITLE
hidden projection

### ISSUE THREAD

**Issue by imjoerock** [MapWindow/MapWinGIS#55]
Dear Sir, I'm new in mapwingis. I would like to know that can I invible map projection after projected(Eg. toggle between hide and show). I search around but not found solution. Thanks.

**Comment by pmeems** [comment]
I don't understand your question. Do you want to show/hide the map control?
And what about the projection?
A map has one projection, this is set by code or read from the first layer that is added.

**Comment by imjoerock** [comment]
Sorry for my language. I need to hide map display after projection is added. Let's say I have one layer on bing background map. I need to hide map background, Show only that layer. Is it possile, thanks.

**Comment by imjoerock** [comment]
Sorry for my language. I need to hide map display after projection is added. Let's say I have one layer on bing background map. I need to hide map background, Show only that layer. Is it possile, thanks.

**Comment by pmeems** [comment]
I think you mean you want to hide the tile layer (Bing)? If so you can set the Tile provider to None:
http://www.mapwindow.org/documentation/mapwingis4.9/class_ax_map.html#a5a038b77550b5f653818967a626981e6

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
