### ISSUE TITLE
Need add polygon on specific layer.

### ISSUE THREAD

**Issue by imjoerock** [MapWindow/MapWinGIS#56]
Hi pmeems/all. Appreciated advice to add polygon on layer (need, https://ibb.co/gQxRum). I'm not sure what I did wrong beacuse polygon does not display on the map. I did as below.

1. Add projection.
```
        private void btncreateprojection_Click(object sender, EventArgs e)
        {
            axMap1.Projection = tkMapProjection.PROJECTION_GOOGLE_MERCATOR;
            axMap1.TileProvider = tkTileProvider.OpenStreetMap;
            axMap1.KnownExtents = tkKnownExtents.keUSA;
        }
```
2. create layer
```
        private void btnAddlayer1_Click(object sender, EventArgs e)
        {
            Shapefile sfPolygon = new Shapefile();
            sfPolygon.CreateNewWithShapeID("", ShpfileType.SHP_POLYGON);
            Shape shp = new Shape();
            sfPolygon.EditAddShape(shp);
            axMap1.AddLayer(sfPolygon, true);
        }
```
3. add polygon on map using drawpolygonex.
```
        private void btnAddpolygon_Click(object sender, EventArgs e)
        {
            double[] x = new double[4];
            double[] y = new double[4];
            x[0] = 674620;
            x[1] = 676986;
            x[2] = 676986;
            x[3] = 674620;
            y[0] = 1516444;
            y[1] = 1516444;
            y[2] = 1518284;
            y[3] = 1518284;
            object xObj = x;
            object yObj = y;
            axMap1.DrawPolygonEx(0, ref xObj, ref yObj, 6, 20, true);
        }
```

Thank you very much. Sorry for short description, coz my english is not good.

**Comment by pmeems** [comment]
In `btnAddlayer1_Click()` you add an empty shape without any points.
Please have a look at this example: http://www.mapwindow.org/documentation/mapwingis4.9/_create_polygon_shapefile_8cs-example.html

For `btnAddpolygon_Click` have a look at
http://www.mapwindow.org/documentation/mapwingis4.9/_shapefile_to_drawing_layer_8cs-example.html#a22

In both cases, you need to call AxMap.Redraw: http://www.mapwindow.org/documentation/mapwingis4.9/class_ax_map.html#ae1939d284e4959f137357b0ba9336632

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
