### ISSUE TITLE
Unable to USE WMS Layer in MapwinGIS

### ISSUE THREAD

**Issue by Keshannagari** [MapWindow/MapWinGIS#57]
Problem while trying to load WMS layer into MapWinGIS. Someway i tried to use in Dotspatial where it is working fine and  why can't i use the same in MapWinGis.
How to Use WMS layer in MapWinGIS

**Comment by pmeems** [comment]
DotSpatial and MapWinGIS are unrelated. Please show the code you are using.

**Comment by Keshannagari** [comment]
MapWinGIS.WmsLayer test = new MapWinGIS.WmsLayer();
            test.BaseUrl = "http://ovc.catastro.meh.es/Cartografia/WMS/ServidorWMS.aspx";
            test.Epsg = 23029;
            test.Layers = "Catastro";
            test.Format = "image/png";
            test.DoCaching = true;
            int getbK = axWmp.mapCntrl.AddLayer(test, true);
I have used the above code to load WMS layer where 'getbK' is returned with 0. But unable to visualize data on Map.

**Comment by BurkhartS** [comment]
Try to load the wms-layer via XML-file as described in the [OGR-documentation.](http://www.gdal.org/frmt_wms.html).
I've done this in a VB.NET-project reading the WMS-Parameters from a database, I write them into a temprorary XML-file that I load as image.

Maybe this gets you on the right track:

```
Dim cmd As New Npgsql.NpgsqlCommand
    cmd.CommandType = CommandType.Text
    cmd.Connection = Basis_Form.PGconnection
    cmd.CommandText = "SELECT wms_id, layername, wms_version, server_url, imageformat, layers, " & _
                        "ulx, uly, lrx, lry, sizex, sizey, usetransparency, transparencycolor, " & _
                        "transparencypercent  " & _
                        "FROM zebsis_gdal_wms  " & _
                        "WHERE wms_id = @wmsid;"
    cmd.Parameters.AddWithValue("@wmsid", wms_id)
    Dim da As New Npgsql.NpgsqlDataAdapter
    da.SelectCommand = cmd
    Dim ds As New DataSet
    Try
      da.Fill(ds)
    Catch ex As Npgsql.NpgsqlException
      MsgBox(ex.Message & vbCrLf & ex.Hint, MsgBoxStyle.Critical, "Database-Error! (" & System.Reflection.MethodBase.GetCurrentMethod.Name & ")")
    End Try

    Dim dt As New DataTable
    dt = ds.Tables(0)
    Dim dr As DataRow
    dr = dt.Rows(0)

    Dim tempFolder As String = My.Computer.FileSystem.SpecialDirectories.Temp
    'Write XML-Definition of Layer in temporary file
    With dr
      Dim file As System.IO.StreamWriter
      file = My.Computer.FileSystem.OpenTextFileWriter(tempFolder & "\zebsis_wms.xml", False, System.Text.Encoding.ASCII)
      file.WriteLine("<GDAL_WMS>")
      file.WriteLine("  <Service name=""WMS"">")
      file.WriteLine("    <Version>" & CStr(.Item("wms_version")) & "</Version>")
      file.WriteLine("    <ServerUrl>" & CStr(.Item("server_url")) & "</ServerUrl>")
      file.WriteLine("    <SRS>EPSG:25832</SRS>")
      file.WriteLine("    <ImageFormat>image/" & CStr(.Item("imageformat")) & "</ImageFormat>")
      file.WriteLine("    <Layers>" & CStr(.Item("layers")) & "</Layers>")
      file.WriteLine("  </Service>")
      file.WriteLine("  <DataWindow>")
      file.WriteLine("    <UpperLeftX>" & CStr(.Item("ulx")) & "</UpperLeftX>")
      file.WriteLine("    <UpperLeftY>" & CStr(.Item("uly")) & "</UpperLeftY>")
      file.WriteLine("    <LowerRightX>" & CStr(.Item("lrx")) & "</LowerRightX>")
      file.WriteLine("    <LowerRightY>" & CStr(.Item("lry")) & "</LowerRightY>")
      file.WriteLine("    <SizeX>" & CStr(.Item("sizex")) & "</SizeX>")
      file.WriteLine("    <SizeY>" & CStr(.Item("sizey")) & "</SizeY>")
      file.WriteLine("  </DataWindow>")
      file.WriteLine("  <AdviseRead>true</AdviseRead>")
      file.WriteLine("  <VerifyAdviseRead>false</VerifyAdviseRead>")
      'file.WriteLine("  <OfflineMode>true</OfflineMode>")
      file.WriteLine("  <Cache>")
      file.WriteLine("    <Depth>4</Depth>")
      file.WriteLine("    <Path>" & tempFolder & "\gdalwmscache</Path>")
      file.WriteLine("  </Cache>")
      file.WriteLine("  <MaxConnections>5</MaxConnections>")
      file.WriteLine("  <Projection>EPSG:25832</Projection>")
      'file.WriteLine("  <OverviewCount>10</OverviewCount>")
      file.WriteLine(" </GDAL_WMS>")

      file.Close()

      'Load Layer from temporary XML-file
      Dim im As New MapWinGIS.Image
      im.Open(tempFolder & "\zebsis_wms.xml", MapWinGIS.ImageType.PNG_FILE, False)
      'I load the data via a legend, you could also load it directly into the mapwindow
      Dim i As Integer = Basis_Form.Legend1.Layers.Add(im, True)

      If i = -1 Then
        MsgBox("Layer not loaded")
      Else
        If CBool(.Item("usetransparency")) = True Then 
          im.SetTransparentColor(CUInt(.Item("transparencycolor")))
        End If
        im.TransparencyPercent = CDbl(.Item("transparencypercent")) 
        Basis_Form.Legend1.Layers.Item(i).Name = CStr(.Item("layername"))
        Basis_Form.Legend1.Layers.Item(i).Tag = CInt(.Item("wms_id"))
        Basis_Form.Legend1.Layers.Item(i).Visible = visible
       
      End If
    End With
```

Hope you get it running. This works so far. I'm not really happy with the caching and performance, but thats another story.

Cheers
Burkhart

**Comment by Keshannagari** [comment]
We have made same format using the OGR Documentation we are succeeded to load WMS layer but unable to view the data.
We have tried different options like updating various attributes in xml tags as well as in the code but not succeed to view the data in the loaded WMS layer

            MapWinGIS.Image img1 = new MapWinGIS.Image();
            img1.Open(@"D:\temp_wms.xml", MapWinGIS.ImageType.GIF_FILE, false);
            img1.Brightness = 0 / 20.0f;
            img1.Contrast = 20 / 20.0f;
            img1.Saturation = 20 / 20.0f;
            img1.Hue = 0;
            img1.Gamma = 20 / 20.0f;
            img1.TransparencyPercent = (byte)255;
            img1.UseTransparencyColor = true;
            img1.SetTransparentColor(utils.ColorByName(MapWinGIS.tkMapColor.White));
            int a = commonVariables.legendObj.Layers.Add(img1, true);
            AxLibCnt.mapObj.set_LayerDynamicVisibility(a,false);
            legendObj.Layers.ItemByHandle(a).Name = "test";
            legendObj.Layers.ItemByHandle(a).Tag = "test";
            legendObj.Layers.ItemByHandle(a).Visible = true;

Please find the attached txt for xml with tags containing the WMS details which we made using OGR Documentation.
[TestWMS.txt](https://github.com/MapWindow/MapWinGIS/files/1611887/TestWMS.txt)

We have use the above code & have tried different options like updating various attributes in xml tags as well as in the code but not succeed to view the data in the loaded WMS layer
Please help us to view the data

**Comment by BurkhartS** [comment]
Hi,
the first thing I've seen is: Your xml-document requests the service as *.png and you add it as *,gif.
Can you access and visualize this layer in (e.g.) QGIS?
I've edited your xml-file. I wouldn't include any tiled-map-service related parameter as long as you do not request a tiled-map service.
Maybe you could try this xml.
I can't test it because of our special safety structure...
You could also try to test your xml-file via ogrinfo.

Cheers
Burkhart
[TestWMS2.txt](https://github.com/MapWindow/MapWinGIS/files/1622667/TestWMS2.txt)

**Comment by Keshannagari** [comment]
Finally we have done it by modifying the XML with so many iterations. But now the problem comes here that the WMS layer is so much slow in working environment. But in MAPWINDOW5 its quite fast what would be to reason to make it fast as MAPWINDOW5

**Comment by BurkhartS** [comment]
Its difficult to give any advice on performance-issues, as it depends heavily on your datasource.
It is a good idea to start with the caching-parameters in your xml-file (do you use caching? If not, I would seriously recommend it!). It can also speed up data if you change the image-format (e.g. jpeg instead of tiff/png?).

**Comment by pmeems** [comment]
MW5 is using BruTile (https://github.com/BruTile/BruTile) to cache the requests.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
