### ISSUE TITLE
Unable to Rotate Font using angle

### ISSUE THREAD

**Issue by Keshannagari** [MapWindow/MapWinGIS#58]
Trying to rotate Font image in MapwinGis where it should read a value from it assigned values and update the angle of the font based on it.

**Comment by pmeems** [comment]
Can you show the code you are using?

**Comment by Keshannagari** [comment]
Hi pmeems,

We are using below code to rotate but not able to succeed.             

MapWinGIS.Shape pointShape = new MapWinGIS.Shape();
pointShape.Create(MapWinGIS.ShpfileType.SHP_POINT);
pointShape.AddPoint(x, y);
pointShape.Rotate(cellOrigin.x,cellOrigin.y,90);

**Comment by pmeems** [comment]
I don't understand. You are talking about rotating a font image, but your code is rotating a point.
Rotating just a point doesn't make sense: https://www.mapwindow.org/documentation/mapwingis4.9/class_shape.html#a26089fcec63454d98b3170aa7aedfeeb
Do you mean you want to rotate a label: https://www.mapwindow.org/documentation/mapwingis4.9/class_label.html#ac2f882c2affce46643bc0ab476704241

**Comment by jerryfaust** [comment]
Hello @Keshannagari 
I did a little testing of this particular function, and there's a problem with the pointer references, so it is not returning the modified x and y.
The following line of code does not get the rotated x and y:
   pointShape.get_XY(0, x, y)
As a temporary work-around, try this to get your rotated point:
    MapWinGIS.Point pt = pointShape.get_Point(0);
pt.x and pt.y should have the correct (rotated) point position.

Let me know if that works.
Thanks.

**Comment by Keshannagari** [comment]
@pmeems 
We are trying to rotate a font. Using rotate function but the font is not changing. If you want to provide us the concerned code we can. But our overall issues about font. We can rotate image,label but not font.

**Comment by Keshannagari** [comment]
@pmeems 
We are using TTF font file to place the symbols as point features. We are unable to rotate the individual symbol because there is a option like 'angle' where we modify it the it is been reflecting for the complete features on the particular layer. So we request you to provide a option where we can update the angle for individual symbol. same as ESRI Environment.

**Comment by pmeems** [comment]
It seems this has been fixed: https://mapwindow.atlassian.net/browse/MWGIS-123

I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
