### ISSUE TITLE
Black image with Big Tiff file

### ISSUE THREAD

**Issue by anhhna** [MapWindow/MapWinGIS#6]
Thank You for the excellent components. Please help me to fix this issue.

I had a Tiff file, about 468mb, 
https://drive.google.com/file/d/0B8Q2ZOp7YgmHZ3VrOUFYSFZfb2c/view?usp=sharing

I opened it with MapWindow-v5.1.1.28898 x86 MapWinGIS 4.9.4.2, the tif Image just show black
https://drive.google.com/file/d/0B8Q2ZOp7YgmHa1lQS2VnZW9sR0E/view?usp=sharing (height 187m)

when I zoomed it in several times, it can show the Image
https://drive.google.com/file/d/0B8Q2ZOp7YgmHeUM4MEFZaEQ4ZEE/view?usp=sharing (height 20m)

I debuged into the MapWinGIS and I found that in the function GdalRaster::ReadBandData:
poBand->AdviseRead(xOffset, yOffset, width, height, xBuff, yBuff, GDT_Byte, NULL);
poBand->RasterIO(GF_Read, xOffset, yOffset, width, height, srcDataChar, xBuff, yBuff, GDT_Byte, 0, 0);
RasterIO function can not read any data to srcDataChar at 187m but at 20m it can

I dont know how to fix this problem, if you have any idea to fix this, plz help me, thank you so much!

**Comment by pmeems** [comment]
I just tried using your tiff-file and the MW5 and MapWinGIS versions from Trunk and I have no problems showing them.
![image](https://cloud.githubusercontent.com/assets/12067729/22084972/756691a4-ddd2-11e6-8780-57b7bff955e8.png)

I am using a newer version of GDAL like you do. Perhaps that is causing the difference.

In a few weeks I'll release a new installer, perhaps you can try then again.

**Comment by pmeems** [comment]
Since no response anymore I close this issue.
