### ISSUE TITLE
Map control extents issue

### ISSUE THREAD

**Issue by ramkiponnam** [MapWindow/MapWinGIS#62]
Hi ,
I am using new map control(4.9.5.0). When I am trying to get the map extents(mapcontrol.Extents) application raising below error.
**Method not found: 'MapWinGIS.Extents MapWinGIS._DMap.get_Extents()'.**

Could you please help me to overcome the above issue

Regards,
Rama Krishna

**Comment by pmeems** [comment]
I'm using C#. My axMap is set up. I have selected a known extent and can get the extent:

    _axMap1.Projection = tkMapProjection.PROJECTION_GOOGLE_MERCATOR;
    _axMap1.KnownExtents = tkKnownExtents.keNetherlands;
    Console.WriteLine(_axMap1.Extents.ToDebugString());

Please show some more of your code.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
