### ISSUE TITLE
PrefetchToFolder extension parameter

### ISSUE THREAD

**Issue by zontick** [MapWindow/MapWinGIS#63]
I used the function 
PrefetchToFolder (ext, iLevel, iTileProv, sDir, ".png", null); 
and it worked perfectly. But after upgrading to version 4.9.5.0. function began to save tiles without an extension. After returning to the old version, the function started working good again.
Is this a bug or I missed something?

**Comment by pmeems** [comment]
I've just created a very simple unit test and I can confirm the file is saved without any extension.
For clarity can you show your code? Especially how you implemented IStopExecution.
I've created https://mapwindow.atlassian.net/browse/MWGIS-108 for this bug.

**Comment by pmeems** [comment]
I've found the problem. The passed extension wasn't used. I fixed it in the develop branch.
I have never used the PrefetchToFolder method before. And I'm having trouble understanding it right.
Can you share your code snippet?

Thanks,
Paul

**Comment by pmeems** [comment]
Another user is requesting how to setup file caching: https://github.com/MapWindow/MapWinGIS/issues/64
If you can provide how you read and write the folder cache I will add it to the documentation.

**Comment by zontick** [comment]
For save tile part of code
```
long LatMin, LatMax, LonMin, LonMax;
            
LatMin = -50;            LatMax = 50;
LonMin = -50;           LonMax = 50;

Extents ext = new Extents();
ext.SetBounds(LatMin, LonMin, 0.0, LatMax, LonMax, 0.0);
int iMaxLevel = 9;
int iCount=0;
string sDir = @"H:\ms4w\Apache\htdocs\maptest";
int iProvId = (int)tkTileProvider.GoogleMaps;
for (int i = 1; i < iMaxLevel; i++)
{
    iCount = axMap1.Tiles.PrefetchToFolder(ext, i, iProvId, sDir, ".png", null);
    richTextBox1.AppendText(i.ToString() + " = " + iCount.ToString() + Environment.NewLine);
}
```


Code for load tiles   (ms4w must bee instaled before https://ms4w.com/)
```
TileProviders providers = axMap1.Tiles.Providers;
providerId = (int)tkTileProvider.ProviderCustom + 100;
providers.Add(providerId, "CustomTMSprovider", @"http://localhost/maptest/{zoom}/{x}/{y}.png", tkTileProjection.SphericalMercator, 1, 18);
axMap1.Tiles.ProviderId = providerId;
axMap1.Projection = tkMapProjection.PROJECTION_WGS84;
axMap1.GrabProjectionFromData = true;
axMap1.ZoomToTileLevel(2);
axMap1.Latitude = 0;
axMap1.Longitude = 0;
```

**Comment by GISRose** [comment]
I have tiles in a folder on C Disk, not in an sqlite file, the path is C:/map/Z{zoom}/{y}/{x}.png
i have tried this but did not work
TileProviders providers = axMap1.Tiles.Providers;
providerId = (int)tkTileProvider.ProviderCustom + 100;
providers.Add(providerId, "CustomTMSprovider", "file:///C://map//Z{zoom}//{y}//{x}.png", tkTileProjection.SphericalMercator, 1, 18);
axMap1.Tiles.ProviderId = providerId;
axMap1.Projection = tkMapProjection.PROJECTION_WGS84;
axMap1.GrabProjectionFromData = true;

is there any way to do it corectly ???

**Comment by zontick** [comment]
did you install a web server?
Your tiles mast bee in directory with web documents
\Apache\htdocs

instal this and try again https://ms4w.com/

**Comment by GISRose** [comment]
i do not want to use a web server, i want to use tiles directly from a folder.

**Comment by zontick** [comment]
I think you can not do it.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
