### ISSUE TITLE
How can I load local tms files?

### ISSUE THREAD

**Issue by zcwbnu** [MapWindow/MapWinGIS#64]
I can not access the internet ，so can I load local tms files?

**Comment by pmeems** [comment]
Do you have all tms files locally already or do you want to connect once to the internet, prefetch all and next time without internet use the cached version?

When you can connect the first time you can use AxMap.Tiles.Prefetch(): http://www.mapwindow.org/documentation/mapwingis4.9/class_tiles.html#a4d8a8ed485c218fa800c2330140f827b
This will fill a SQLite database with the tiles. This SQLite file can be distributed (copied) to other users.

**Comment by pmeems** [comment]
Another option is to use PrefetchToFolder (http://www.mapwindow.org/documentation/mapwingis4.9/class_tiles.html#a59f57c8df794993ab30af7028d72b317)
The user in https://github.com/MapWindow/MapWinGIS/issues/63 is using this. I've asked him for a code snippet.

**Comment by zcwbnu** [comment]
I selected GoogleSatellite  TileProvider ,however I can not see image.

**Comment by zontick** [comment]
You can see an example here

>  https://github.com/MapWindow/MapWinGIS/issues/63#issuecomment-360526830

**Comment by zcwbnu** [comment]
Do I need to install the MS4W first?

**Comment by zontick** [comment]
yes, for use saved tiles you must install MS4W first.

**Comment by zcwbnu** [comment]
Thank you ！ but I still can't setup file caching. This is my code, the folder has nothing.
        CTiles tiles;
	tiles = m_map.GetTiles();
	long LatMin, LatMax, LonMin, LonMax;           
	LatMin = -50.0;        
	LatMax = 50.0;
	LonMin = -50.0;   
	LonMax = 50.0;
	
	mapWindow::IExtentsPtr pExtents;
	pExtents = m_map.get_Extents();   
	//pExtents->SetBounds(LatMin, LonMin, 0.0, LatMax, LonMax, 0.0);
	double x1,y1,z1,x2,y2,z2;
	pExtents->GetBounds(&x1,&y1,&z1,&x2,&y2,&z2);
	long pj = m_map.get_Projection();
	int iMaxLevel = 9;
	int iCount=0;
	CString sDir = "C:\\MS4W\\ms4w\\Apache\\htdocs\\maptest";
	int iProvId = 6;//(int)tkTileProvider.GoogleMaps;
	for (int i = 1; i < iMaxLevel; i++)
	{
		iCount = tiles.PrefetchToFolder(pExtents, i, iProvId, sDir, ".png", NULL);
		//richTextBox1.AppendText(i.ToString() + " = " + iCount.ToString() + Environment.NewLine);
	}

**Comment by zontick** [comment]
I tried the code again, it works, I got tiles.
```
            double 
            LatMin = -50.0,
            LatMax = 50.0,
            LonMin = -50.0,
            LonMax = 50.0;
            Tiles tiles = new Tiles();
            // mapWindow::IExtentsPtr pExtents;
            // pExtents = m_map.get_Extents();
            //pExtents->SetBounds(LatMin, LonMin, 0.0, LatMax, LonMax, 0.0);
            //double x1, y1, z1, x2, y2, z2;
            Extents ext = new Extents();
            ext.SetBounds(LatMin, LonMin, 0.0, LatMax, LonMax, 0.0);
            int iMaxLevel = 9;
            int iCount = 0;
            string sDir = "C:\\maptest999";
            int iProvId = 6;//(int)tkTileProvider.GoogleMaps;

            for (int i = 1; i < iMaxLevel; i++)
            {
                iCount = tiles.PrefetchToFolder(ext, i, iProvId, sDir, ".png",null);
            }
```
Are you sure that the folder exists and the path to it is specified correctly? function does not create a folder

**Comment by zontick** [comment]
I did not understand this entry, what are you doing?
```
double x1, y1, z1, x2, y2, z2;
pExtents-> GetBounds (& x1, & y1, & z1, & x2, & y2, & z2);
```

**Comment by zontick** [comment]
I did not understand this entry, what are you doing? I think this is an error
double x1, y1, z1, x2, y2, z2;
pExtents-> GetBounds (& x1, & y1, & z1, & x2, & y2, & z2);

**Comment by zcwbnu** [comment]
I'm sure the folder exists and correctly .  I use GoogleMaps as TileProvider (my machine only shows openstreetmap and googlemap, the else TileProvider such as GoogleSatellite can't show .Is this reason? )

**Comment by zontick** [comment]
This is not a reason. Such work at all machines.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
