### ISSUE TITLE
 I can‘t get GoogleSatellite tiles！

### ISSUE THREAD

**Issue by zcwbnu** [MapWindow/MapWinGIS#67]
I use custom provider to get GoogleSatellite tiles like this, but always return false, can you help me?
bool b = providers.Add(providerId, "CustomTMSprovider", "http://mt0.google.cn/vt/lyrs=s&{x}&{y}&{z}", m_map.SphericalMercator, 1, 18);
Is the url  incorrect?
Thank you!

**Comment by pmeems** [comment]
Google no longer allows/supports direct retrieval of their tiles.

You can check by adding the numbers for X, Y and Z and paste the url in your browser.
If you can't get the tile using your browser then MapWinGIS cannot either.
