### ISSUE TITLE
Bug: Shapefile::get_ShapeSelected(...)

### ISSUE THREAD

**Issue by ultraTCS** [MapWindow/MapWinGIS#69]
Hello, 

I'd like to report a bug in Shapefile_Selection.cpp.
CShapefile::get_ShapeSelected(...) does not correctly assign *pVal to VARIANT_TRUE.
Locally I have modified line 296 as follows and tested with success:

`*pVal = (_shapeData[ShapeIndex]->selected() == true) ? VARIANT_TRUE : VARIANT_FALSE;`

Thanks,
LT

**Comment by jerryfaust** [comment]
Thank you for reporting that.  I'll submit the change.

**Comment by jerryfaust** [comment]
Fix has been submitted under JIRA ticket https://mapwindow.atlassian.net/browse/MWGIS-110.

**Comment by ultraTCS** [comment]
Great. Thanks Jerry.
