### ISSUE TITLE
AxInterop.MapWinGIS and Interop.MapWinGIS  not found

### ISSUE THREAD

**Issue by shai-benshimol** [MapWindow/MapWinGIS#7]
After i download all folders from repository, import to visual studio..

**Comment by pmeems** [comment]
Did you watch this video: https://www.youtube.com/watch?v=WVQaFsil0bY&t=285s
It explains what you need to do to get MapWinGIS running on your own machine.

It might also be easier to just run the installer: https://github.com/MapWindow/MapWinGIS/releases

**Comment by pmeems** [comment]
Since no new responses I close this issue.
