### ISSUE TITLE
Cancel Edition event

### ISSUE THREAD

**Issue by pierralex** [MapWindow/MapWinGIS#71]
Hello,
I need to close a window when cancelling edition of a polygon. So far i could not find a way to do that. Is there any?

Best,

**Comment by pmeems** [comment]
Can you show the code that is stopping the editing? Are you manually calling it?

**Comment by pierralex** [comment]
Sorry if my question was not clear. I meant cancelling the edition by pressing the escape key for example

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
