### ISSUE TITLE
Error open arcgis .mdb files with non-english filename

### ISSUE THREAD

**Issue by Dorofei4** [MapWindow/MapWinGIS#72]
I try to open shapes from Arcgis personal database .mdb 

```
if ShpOpenDlg.Execute(self.Handle) then begin
    s:=ShpOpenDlg.FileName;
    ds:= coOgrDatasource.create;
    R:=ds.Open(s);
    showmessage(Mapwin.ErrorMsg[MapWin.LastErrorCode]);
    for i:=0 to  ds.LayerCount do begin
        mapwin.AddLayer(ds.GetLayer(i,false),true);
    end;
    RefreshLegend();
    ActFullExtExecute(Sender);
end;
end;
```

If filename doesn't have russian characters - everything is ok, but if it contains russian characters, I receive an error "File not found". 
If i try to open .shp file with russian characters in filename everything is ok
Please help!
Alex Dor.  dorofeeva@bashneft.ru

**Comment by jerryfaust** [comment]
Hello @Dorofei4.  MapWinGIS incorporates the OSGeo GDAL/OGR library for support of non-Shapefile data sources.  Reviewing the GDAL/OGR implementation of Personal Geodatabases (ESRI MDB files), it looks like they do not support UNICODE filenames.  Their interface only accepts char* filename.

**Comment by jerryfaust** [comment]
Follow-up: I need to look a little deeper into this.  It may well be that GDAL supports UTF-8 formatted strings as the char* parameter.  MapWinGIS may have to be modified to pass on the specified filename in a manner similar to that of the Shapefiles.  @pmeems do you have thoughts or input on this?

**Comment by Dorofei4** [comment]
l explored gdal dll and found, that connection established through ODBC   "DRIVER=Microsoft Access Driver (*.mdb);DBQ=%s" .  Probably  in file ogrodbcdatasources.cpp  in gdal library. I think that  filename of mdb file is in  UNICODE , but ODBC driver wants  ANSCI. I am not shure. Any ideas how to solve the problem?

**Comment by pmeems** [comment]
Reading this page http://www.gdal.org/drv_pgeo.html I don't see anything mentioned about UNICODE.
Can you share your file? I can check with gdalinfo.exe if gdal can open it. If GDAL can open it, we need to fix it in MapWinGIS.

**Comment by Dorofei4** [comment]
[АБВ_example.zip](https://github.com/MapWindow/MapWinGIS/files/1766179/_example.zip)
I tried to rewrite in bynary dll  the string DRIVER=Microsoft Access Driver (*.mdb);DBQ=%s    by
DRIVER=Microsoft Access Driver (*.mdb);DBQ=d:\АБС.mdb and run my program. File opened successfully   and  all shapes  displayed in map window.

**Comment by Dorofei4** [comment]
I think problem may be in file GdalHelper.cpp in function
GDALDataset* GdalHelper::OpenOgrDatasetW(CStringW filenameW, bool forUpdate, bool allowShared)
In this string  (CStringA filenameA = Utility::ConvertToUtf8(filenameW);) we convert filenameW to UTF8, but Microsoft access ODBC drive whants  ASCII.

**Comment by pmeems** [comment]
We've made a lot of UNICODE changes in the latest versions of MapWinGIS.
Can you check with the recent version of MapWinGIS is you still have this problem?

I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
