### ISSUE TITLE
SnapShot3

### ISSUE THREAD

**Issue by ultraTCS** [MapWindow/MapWinGIS#74]
Can someone please confirm that a snapshot does _not_ account for the properties of the shapes in a shapefile.

For instance: A snapshot of a point type with point size 8 results in a png showing a smaller sized point. Similarly a snapshot of a polyline type with dashed line results in a png showing solid line style.

If so, any indication that this limitation will be addressed?

I'm using the SnapShot3 API in 4.9.4.2.

Thanks,
LT

**Comment by jerryfaust** [comment]
Hello @ultraLT.

I just tested to confirm, I DO get the dashed line style in the snapshot.  Perhaps something else is going on.  (I am running 4.9.4.5).  I have noticed that line styles don't always behave when the line width is 1 or less.  I was originally using a line width of 2, but it had to be at least 1.1 to display properly.

Jerry.

**Comment by ultraTCS** [comment]
Hi Jerry, ok...do you mind trying point shape? Are you using Snapshot3? (I guess all snapshot variations use snapshot_core anyway tho).

Thanks again.

**Comment by jerryfaust** [comment]
Here's a snip of my test application (on the left) and my Snapshot capture (in the right window), showing a dashed line and a  48 pt pentagon.  In my particular case, I'm capturing the entire extent, as follows:

```
    ' get map extents
    Dim box As Extents = AxMap1.Extents()
    ' capture the image
    If TypeOf box Is IExtents Then
        Dim img As Image = AxMap1.SnapShot(box)
        If img IsNot Nothing Then
            Dim iptr As IntPtr = New System.IntPtr(img.Picture.Handle)
            PrintPreview.PictureBox1.Image = Bitmap.FromHbitmap(iptr)
            PrintPreview.ShowDialog(Me)
        End If
    End If
```
I wonder if the width you are specifying in ShapShot3 is effectively scaling down the image and losing the detail.  Can you send a code snippet?  As a test, you could perhaps just make a call to SnapShot to get a full scale image, and see if you get the detail.

![image](https://user-images.githubusercontent.com/30758167/37054749-89c7d490-2134-11e8-9d0c-40f62ad88bca.png)

**Comment by ultraTCS** [comment]
Thanks Jerry. Not an issue with snapshot. Just an implementation issue.

I was using a fixed width resulting in an incorrect ratio of map units per pixel of image for x, y axes.
