### ISSUE TITLE
Identify tool

### ISSUE THREAD

**Issue by guenlm** [MapWindow/MapWinGIS#75]
Hello
I am sorry but I still have a problem with the identifier tool since version 4.9.3 on vba Access.
I tried to use the identifier class but the ActiveLayer doesn't exist in VBA so I can't give the handle of active layer which is used with the identifier tool...
I always have LayerHandle=-1 with AxMap_ShapeIdentified and shapeIndex=0...
I tried the last version 4.9.5.0
Thank's.

**Comment by pmeems** [comment]
Looking at the documentation: http://www.mapwindow.org/documentation/mapwingis4.9/class_identifier.html#details
I see ActiveLayer is a property. So most likely in VBA you need to prefix get_ and set_ making get_ActiveLayer.
Does this work for you?

**Comment by guenlm** [comment]
No it doesn't work. I dont' have this property (as you can see on the screenshot)
![identifier](https://user-images.githubusercontent.com/12870078/37080475-abc3f2c4-21e6-11e8-87f0-4fabd121bc56.PNG)
With the property get_ and set_ in others objects, I have to take off get_ and set_ in VBA.
thank's

**Comment by pmeems** [comment]
Sorry for not getting back to you.
Did you ever got it working?

I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
