### ISSUE TITLE
LOCAL MAPS OFFLINE

### ISSUE THREAD

**Issue by pachoduran** [MapWindow/MapWinGIS#77]
Hi, please help me.  take the tiles png of my city, need can offline work but don't function. (sorry, my English is very bad)

The code is:

```
        Dim x As Double = 39
        Dim y As Double = 140
        Dim span As Double = 5

        Dim ext As New Extents
        ext.SetBounds(x - span, y - span, 0.0, x + span, y + span, 0.0)
        AxMap.Tiles.PrefetchToFolder(ext, 8, 0, "D:/pacho/PRODUCTOS/Mapa", ".png", Nothing)
        providers = AxMap.Tiles.Providers
        providerId = tkTileProvider.ProviderCustom + 1
        providers.Add(providerId, "MyProvider", "D:/pacho/PRODUCTOS/Mapa/{zoom}/{x}/{y}.png", tkTileProjection.SphericalMercator, 8, 17)

        AxMap.Tiles.ProviderId = providerId

        AxMap.Projection = tkMapProjection.PROJECTION_WGS84

        AxMap.GrabProjectionFromData = True
        AxMap.ZoomBehavior = tkZoomBehavior.zbUseTileLevels
        AxMap.ZoomToTileLevel(8)
```

Thanks.

Bye

**Comment by pmeems** [comment]
A bit more info might help.

- Do you get an error? 
- Do the png files exist?
- Try implementing the Application callback to get progress and errors: https://www.mapwindow.org/documentation/mapwingis4.9/class_global_settings.html#ac01309d06b2dc9c11019a8c8589da3c8
- Also implementing StartLogTileRequests() might help you finding the problem: https://www.mapwindow.org/documentation/mapwingis4.9/class_global_settings.html#a900a8677dfcc080f2f1d64566b7582e3

**Comment by pachoduran** [comment]
Hi, thaks for your response.

- no error
- YEs, all png is in this directory

**Comment by pachoduran** [comment]
Hi, take some problem with create Icallback

i do:

Class Callback
    Inherits ICallback


    Private m_label As ToolStripStatusLabel = Nothing

    Public Sub New(ByVal label As ToolStripStatusLabel)
        m_label = label
        If label Is Nothing Then Throw New NullReferenceException("No reference to the label was provided")
    End Sub

    Sub New()
        ' TODO: Complete member initialization 
    End Sub

    Public Sub [Error](ByVal KeyOfSender As String, ByVal ErrorMsg As String)
        Debug.Print("Error reported: " & ErrorMsg)
    End Sub

    Public Sub Progress(ByVal KeyOfSender As String, ByVal Percent As Integer, ByVal Message As String)
        m_label.Text = Message & ": " + Percent & "%"
        Application.DoEvents()
    End Sub
End Class

in line " Inherits ICallback"  the classes can only inherit from other classes


Help me, thanks

**Comment by pmeems** [comment]
`ICallback` is an interface, so you need to [implement](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/interfaces/) it, not inherit it.

I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
