### ISSUE TITLE
ShapeEditor and adding points

### ISSUE THREAD

**Issue by pierralex** [MapWindow/MapWinGIS#78]
Hello all,
I am trying to edit a polyline using shape editor. I would like to add points to my polyline. How can i do that (both manually and through code)?
Thanks,

**Comment by pierralex** [comment]
I found the answer for manual edition (double click) but i still did not find how to do that through code (event fired through another window).

**Comment by pmeems** [comment]
Shapes have parts and parts have points. You can add points to a part.
Here's an example how to manually create a polygon:
https://www.mapwindow.org/documentation/mapwingis4.9/_create_polygon_shapefile_8cs-example.html
Here's some more info about editing shapes: https://www.mapwindow.org/documentation/mapwingis4.9/group__shapefile__editing.html

The difficulty to add a point to an existing polygon is the order of the points. First, you need to find the closest existing point, using sf.GetClosestVertex (https://www.mapwindow.org/documentation/mapwingis4.9/group__shapefile__selection.html#ga43e6c5f88c8a0b1a01239b02acc8fa77), use its index and add the new point at the next index.

Perhaps you can tell us what you try to do. 
And isn't it much easier to use MapWindow5 instead? Then you don't need to rebuild all the basic stuff yourselves.

**Comment by pierralex** [comment]
I am drawing trajectories which i can edit in 2 ways:
- a window form (using a DataGridView)
- using mapwingis

Both of them communicate to a Mediator throgh interfaces. This mediator updates both views so that coordinates in the datagridview and positions in the axmap are always consistant.
I need the user to be able to add a point without interacting directly with the axMap. If he inserts a row with coordinates in the DataGridView, the shape being edited in the axMap must be updated too.
So far, i did not find a way to add a point to the layer being edited through the ShapeEditor. When i insert a point throught the ShapeEditor, i am loosing the last point of the shape. Which i do not want.

I also want these actions to be cancellable. By closing the form containing the DataGridView, the edited data must be kept(DialogResult.OK) or removed (DialogResult.Cancel).

I cannot use MapWindow5 because we use our how data model and views. Our use case is air traffic so we need specific functionalities.

I will look closer in the link you provided today and come back.

Best,

**Comment by pierralex** [comment]
Sorry for coming back late on that issue.
I really did not find a way to do what I am looking for. My previous comment might not be very clear so let met reformulate:
1. I have a trajectory represented by a single polyline on 1 layer.
2. I can edit the trajectory simultaneously through axMap interactive edition and a windows form (datagridview listing all the positions)

I have a mediator class which handles communications through the axMap and the Windows Form. 

When i start edition, I start interactive edition:

`      public void StartEditRefTraj(IRefTrajectory traj)
        {
            if (!dictIdRefTrajectoryIdLayer.ContainsKey(traj.Id))
            {
                throw new KeyNotFoundException(traj.Id);
            }

            Shapefile sfLine = axMap.get_Shapefile(dictIdRefTrajectoryIdLayer[traj.Id]);

            sfLine.InteractiveEditing = true;
            axMap.CursorMode = tkCursorMode.cmEditShape;
            axMap.ShapeEditor.StartEdit(dictIdRefTrajectoryIdLayer[traj.Id], 0);
            axMap.ShapeEditor.VerticesVisible = false;
        }`

When i insert a position through my windows form (interactive edition is still active), the following method is called:
`public void OnInsertPoint(int index, IVector2 point)
{
            // Shift existing positions
            for (int i = axMap.ShapeEditor.numPoints; i >= index; --i)
            {
                double x, y;
                axMap.ShapeEditor.get_PointXY(i - 1, out x, out y);
                axMap.ShapeEditor.put_PointXY(i, x, y);
            }

            axMap.ShapeEditor.put_PointXY(index, point.X, point.Y);
 }`

The new point is inserted at the correct position but the last point is removed.

I tryed to use Shapefile.EditUpdateShape() after inserting a new point but on my view, nothing changes.

What am I doing wrong? And could you provide me a quick sample of how to trigger a point insertion while on a shape being edited interactively?

**Comment by pierralex** [comment]
Sorry for code formatting by i really do get how to do it properly there

**Comment by pierralex** [comment]
Here is the "dirty" solution I found. It works perfectly but I do not like the fact of inserting the new point in the shapefile. I have to reload the data from my custom data repository if i cancel the edition. It works but i find that dirty.

`int layerHandle = axMap.ShapeEditor.LayerHandle;
            Shapefile sf = axMap.get_Shapefile(layerHandle);

            // stop interactive edition
            axMap.ShapeEditor.Clear();

            sf.Shape[0].InsertPoint(new Point(){ x = point.X, y = point.Y }, ref index);

            axMap.ShapeEditor.StartEdit(layerHandle, 0);`

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
