### ISSUE TITLE
How to get height value from geoposition?

### ISSUE THREAD

**Issue by zcwbnu** [MapWindow/MapWinGIS#79]
I  loaded DEM image, How can I get  elevation from Latitude and longitude? Can anybody help me？

**Comment by pmeems** [comment]
You can use the mouse click event to get to pixel position of the mouse and use axmap.PixelToProj (https://www.mapwindow.org/documentation/mapwingis4.9/group__map__coordinates.html#ga7f9ea56b66c63f474bb996f28da6fd1e) to convert to map units. Then use img.ProjectionToImage (https://www.mapwindow.org/documentation/mapwingis4.9/group__image__position.html#gaee82e575961d83b4c8cdb2ef3b9708a9) to get the column and row.
Next use img.Value (https://www.mapwindow.org/documentation/mapwingis4.9/group__image__data.html#ga43a68dec573ef77d473f3be6330a7d41) to get the pixel value.

Is this what you are looking for?
