### ISSUE TITLE
Layer position

### ISSUE THREAD

**Issue by jirigcs** [MapWindow/MapWinGIS#8]
I've posted this issue on codeplex which might be abandoned... My apologies for creating redundant posts.

I'm experiencing strange positioning of shapefiles when adding them into MapWinGIS (AxMap) component: When adding the point shapefile, the new one is added below the previous one but the position number (get_LayerPosition) of the newly added layer is higher then position number of the previous one. When adding polyline or polygon shapefile, everything seems to work properly (new layers overlay the older ones, position number increases). Am I doing something wrong or is there some reason for such behavior? 

Thank you,
Jiri 

Here is my code snippet for adding new layer: 

```
Private Sub tsmiAddLyr_Click(sender As Object, e As EventArgs) Handles tsmiAddLyr.Click
    OpenFileDialog1.Filter = "Shapefiles (*.shp)|*.shp"
    OpenFileDialog1.FileName = ""
    If OpenFileDialog1.ShowDialog = DialogResult.OK Then
        Dim sf = New Shapefile()
        If Not sf.Open(OpenFileDialog1.FileName) Then
            MessageBox.Show("Failed to open shapefile: " + sf.ErrorMsg(sf.LastErrorCode))
        Else
            Dim layerHandle As Integer = AxMap1.AddLayer(sf, True)
            Dim it As New ListViewItem(AxMap1.get_LayerPosition(layerHandle))
            it.SubItems.Add(AxMap1.get_LayerName(layerHandle))
            it.SubItems.Add(layerHandle)
            it.SubItems.Add(0)
            it.Checked = True
            lvLegend.Items.Add(it)

        End If
    End If
End Sub
```

Visual Studio 2015, MapWinGIS 4.9.4.2 Win32

**Comment by pmeems** [comment]
What happens if you open the file by filename:
`axMap1.AddLayerFromFilename(OpenFileDialog1.FileName, tkFileOpenStrategy.fosAutoDetect, true);`
More info at http://www.mapwindow.org/documentation/mapwingis4.9/group__map__layer__management.html#gafe3a6d4ebaf64e8b68c8c8dd0ddbb0d0

And so I understand your workflow.
You first add a polygon layer, then you add a point layer and you cannot see these points because they are below the polygon layer. When you hide the polygon layer you can see the points again.
Do I understand it correctly?

**Comment by pmeems** [comment]
I just created a small piece of code in C#:

    // Create a polygon shapefile:
    var sfPolygon = new Shapefile();
    sfPolygon.CreateNewWithShapeID("", ShpfileType.SHP_POLYGON);
    var shp = new Shape();
    shp.ImportFromWKT(
        "POLYGON((330695.973322992 5914896.16305817, 330711.986129861 5914867.19586245, 330713.350435287 5914867.56644015, 330716.510827627 5914862.28973662, 330715.632568651 5914860.60107999, 330652.234582712 5914803.80510632, 330553.749382483 5914715.80328169, 330551.979355848 5914714.83347535, 330549.911988583 5914715.86502807, 330545.027807355 5914724.05916443, 330544.592985976 5914725.93531509, 330544.30963704 5914726.72754692, 330543.612620707 5914726.14904553, 330543.271515787 5914727.06633931, 330542.234090059 5914729.85597723, 330542.959654761 5914730.50411962, 330530.319252794 5914765.86064153, 330505.294840402 5914836.7930124, 330471.411812074 5914931.61558331, 330486.074748666 5914941.33795239, 330585.983154737 5915010.32749106, 330618.427962455 5915031.20447119, 330653.234601917 5914970.37328093, 330695.973322992 5914896.16305817))");
    sfPolygon.EditAddShape(shp);
    
    // Create some random points:
    var random = new Random();
    const int numPoints = 50;
    var extents = sfPolygon.Extents;
    var width = extents.xMax - extents.xMin;
    var height = extents.yMax - extents.yMin;
    
    var sfPoint = new Shapefile();
    sfPoint.CreateNewWithShapeID("", ShpfileType.SHP_POINT);
    for (var i = 0; i < numPoints; i++)
    {
        var x = extents.xMin + (width * random.NextDouble());
        var y = extents.yMin + (height * random.NextDouble());
        var shpPoint = new Shape();
        shpPoint.Create(ShpfileType.SHP_POINT);
        shpPoint.AddPoint(x, y);
        sfPoint.EditAddShape(shpPoint);
    }
    
    axMap1.AddLayer(sfPolygon, true);
    axMap1.AddLayer(sfPoint, true);

The result:
![image](https://cloud.githubusercontent.com/assets/12067729/22406000/e32c000e-e64a-11e6-905d-9e2e585ccd2a.png)

As you can see the point layer is acting as expected.

**Comment by jirigcs** [comment]
Hi Paul, thank you for your answer.

My problem is that I do not understand how layer positioning works. I understand that the layer position is generated automatically during layer import.

Let me give you an example: At the beginning, I add point layer (let's call it pnts1) into the map component - it has position 0. Then I add another point layer (pnts2). Its automatically generated position is 1 however it is placed below the initial point layer (pnts1). Then I add some polygon layer (poly1). It gets position of 2 and it is placed above both point layers.
So at the end, I have the following sequence of layers in terms of their order (from top to bottom):
poly1
pnts1
pnts2

I assume that the higher number of layer position indicates its position above the layer with lower number of layer position. So based on their position, the sequence should be (again from top to bottom):
poly1
pnts2
pnts1

Is it happening only to me? Or is there some intention for such behaving?

Thank you
Jiri

**Comment by jirigcs** [comment]
Please can anyone give me an indication whether he/she also experiences the positioning issue as described above?
Thanks,
Jiri

**Comment by pmeems** [comment]
I'm not sure what is going wrong in your code.
No magic is happening when adding a layer. The layers are drawn in the order you add them, assuming you don't change the order after loading.

Can you create a simpler demo and just add the layers and let me know if the order is still wrong?

**Comment by pmeems** [comment]
Closing this old question.
