### ISSUE TITLE
Example Shp need.

### ISSUE THREAD

**Issue by imjoerock** [MapWindow/MapWinGIS#81]
Hi Paul, There're many great examples you did as link ,https://www.mapwindow.org/documentation/mapwingis4.9/examples.html. It's great and right way to start learning Mapwingis. Anyway, It would be great if you can share .shp file for concern example. We can not run some example with specific shp file need.

**Comment by pmeems** [comment]
Which shapefile do you need? Most examples create the data.
We had some sample data at https://gisdata.codeplex.com/. I see it is archived now.

**Comment by imjoerock** [comment]
Hi Paul, Thanks. I'll check it out.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
