### ISSUE TITLE
Unable to assign point values to Label Font size.

### ISSUE THREAD

**Issue by Keshannagari** [MapWindow/MapWinGIS#82]
Hi , i want to assign label font size as 2.6 but in MapWinGis it is reading this as 3 or if am assigning the font size as 2.4 then it is reading it as 2. 
Please find the code line which am using to assign font size. 
 
'newShapeFile.Labels.FontSize2 = Convert.ToInt32(2.4);' or ' newShapeFile.Labels.FontSize2 = Convert.ToInt32(2.6);' 

Please correct me if am doing anything wrong or suggest me how to assign Label font size with point value.

**Comment by pmeems** [comment]
First, when you call Convert.ToInt32 you will convert 2.4 to 2 and 2.6 to 3
Second, looking at the documentation: https://www.mapwindow.org/documentation/mapwingis4.9/class_labels.html#a4201e683cb2d4c5b535c17a8342a7417 and looking at the source code MapWinGIS expects an integer, not a floating number.

If you do need floating numbers as font size I can make a feature request if you like. Not sure when it will be added, though.

**Comment by Keshannagari** [comment]
Yes, Could you implement and do the needful as the data need to be visible as same as other platforms.

**Comment by pmeems** [comment]
I created a feature request for this: https://mapwindow.atlassian.net/browse/MWGIS-113

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
