### ISSUE TITLE
How to move polyline feature's vertices?

### ISSUE THREAD

**Issue by zcwbnu** [MapWindow/MapWinGIS#83]
I create a polyline feature and I want to edit it. How can I select a vertex and move it with mouse? Can anyone help me?

**Comment by pmeems** [comment]
Please have a look at the shape editor class: https://www.mapwindow.org/documentation/mapwingis4.9/class_shape_editor.html

**Comment by zcwbnu** [comment]
this is my code,   StartEdit always return false.
mapWindow::IShapeEditorPtr se;
se.CreateInstance("MapWinGIS.ShapeEditor");
se->put_EditorBehavior(tkEditorBehavior::ebVertexEditor);
VARIANT_BOOL b = se->StartEdit(0,0);

**Comment by pierralex** [comment]
I see several issues there (or i need to see more of your code).

1. You should use the axmap ShapeEditor property and use this instance of the ShapeEditor
2. According to your code, you try to edit the shape indexed 0 in layer having 0 for layerHandle. Are you sure that these are corrects? I would avise to store the layer handle uppon creation and to use it.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
