### ISSUE TITLE
ShapeFile.GetClosestVertex

### ISSUE THREAD

**Issue by pierralex** [MapWindow/MapWinGIS#85]
According to documentation, if parameter maxDistance is set to 0, there is no limitation.
But it does not work. There are two issues in ShapefileHelper::GetClosestPoint:

- comparison in return statement always return false if maxDistance = 0

- l343 dist < minDist && dist < maxDistance always evaluate to false if maxDistance = 0

I will propose a correction if i find the time

**Comment by pmeems** [comment]
Can you share some code so we can reproduce?
Are you using Shape.ClosestPoints	(Shape shape2): https://www.mapwindow.org/documentation/mapwingis4.9/class_shape.html#a50fb5435d697e3e59d31131d9e65c5e0

**Comment by pierralex** [comment]
I do not have a sample to provide because I implented my own algorithm as a workaround but i faced this problem using Shapefile.GetClosestVertex.
I just remember that the method provided -1 for PointIndex and ShapeIndex  when i set maxDistance to 0. And that i identify these issues by investigating MapWindow repository.

Originally, i used this method uppon mouseup event (looking for the closest point in a polyline).

**Comment by pmeems** [comment]
Did you even found the time to look at this in depth?

I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
