### ISSUE TITLE
CurrentScale unit

### ISSUE THREAD

**Issue by pierralex** [MapWindow/MapWinGIS#86]
Hi pmeems,
I do not understand the unit used for Axmap.CurrentScale.
I need to know how many map units are used per pixels or inch/centimeters on the screen. How can I do that?

Best,

**Comment by pmeems** [comment]
Are you looking for ProjToPixel():
https://www.mapwindow.org/documentation/mapwingis4.9/group__map__coordinates.html#ga9c9dedd197c0620f9cf35de41dc03207 and PixelToProj()
https://www.mapwindow.org/documentation/mapwingis4.9/group__map__coordinates.html#ga7f9ea56b66c63f474bb996f28da6fd1e

**Comment by pierralex** [comment]
No, I need to tag a point while in edition mode. For that I implement a mouse up event handler. I need to find the closest point if any within a specific range. This range is in map units but i want to determine it in number of pixels (to remain constant according to the zoom level). So i need to convert a number of pixel on screen into a projected distance.
So i would like to understand the unit used for Axmap.CurrentScale.

**Comment by pmeems** [comment]
Sorry for the very late reply.
In case you still need this.
Please have a look at [GetCurrentScale()](https://github.com/MapWindow/MapWinGIS/blob/master/src/Control/Map_Scale.cpp#L371)

I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
