### ISSUE TITLE
Problem with function GeoProjection.Transform in Windows 10

### ISSUE THREAD

**Issue by DanyMar** [MapWindow/MapWinGIS#88]
Hi, I use MapWinGis 4.9.5.0, system Windows 10, Visual Studio 2017. I loads to my project shape  in coordiante system ESPG 3857(Google Mercator) and sent axMap1.Projection = tkMapProjection.PROJECTION_GOOGLE_MERCATOR.  Function GeoProjection.StartTransform returns false. Points I have in coordiante system ESPG 2180(poland cs92). The problem only occurs in the system Windows 10.

**Comment by pmeems** [comment]
Could you show the code you are using and tell us what language (C#, C++) you are using?
And can you share (a piece) of your data for us to test?

**Comment by DanyMar** [comment]
I'm sorry my mistake. I did it wrong. Everything works. Topic can be closed.
