### ISSUE TITLE
Map object rotation

### ISSUE THREAD

**Issue by saadb** [MapWindow/MapWinGIS#89]
I had a request to see if MapWinGIS can support rotating the AxMap object about it centeroid.
That means all of the shapes and images and figure contained by the instance of AxMap be rotated say 90 degree to the left so that north is pointing west.
Sometimes certain views when rotated can be easier to visualize.
ArcGIS has a similar feature called something like rotating the Data Frame

Thank you

**Comment by pmeems** [comment]
Thanks for your feedback.
We do have a partial implementation of map rotation, but due to some problems in the past, it was not finished. Somebody could have a look at it and try to finish it. The core team doesn't have the time right now.
As a workaround, you could rotate the whole control.

**Comment by saadb** [comment]
can you please, elaborate on how to rotate the whole control?

**Comment by pmeems** [comment]
I'm sorry, I thought I remembered some user doing this years ago as a workaround, but I can't find it anymore. And searching for "WinForms rotate controls" shows that it is not possible to do.

We've created an issue for it: https://mapwindow.atlassian.net/browse/MWGIS-85.
Now we need some resources to work in it.

**Comment by saadb** [comment]
Thank you for the update

**Comment by Luiz-HSSD** [comment]
could you send me version source  4.8

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
