### ISSUE TITLE
mousedown

### ISSUE THREAD

**Issue by gpsfishing** [MapWindow/MapWinGIS#9]
ver 4.9.4.2 win 32 using Visual Foxpro 9.0 windows 7

with sendmousedown=true

event mousedown does not fire on left mouse click
mouse down does fire on right mouse click

with sendmouseup

event fires on mouse clicks, but if cursormode is set to 0, cursor icon changes as if in cursormode=1 but functions as in cursormode= 0

**Comment by pmeems** [comment]
I'm not sure what your problem is without seeing some code.
Did you look at this example:
http://www.mapwindow.org/documentation/mapwingis4.9/_mark_points_8cs-example.html

**Comment by gpsfishing** [comment]
On 1/29/2017 12:54 PM, Paul Meems wrote:
> I'm not sure what your problem is without seeing some code.
> Did you look at this example:
> http://www.mapwindow.org/documentation/mapwingis4.9/_mark_points_8cs-example.html
>
>
The following code when run only fires the mouse _down_ event message 
when the right mouse button is pressed. No message when the left mouse 
button is pressed.

PUBLIC main
main=CREATEOBJECT('mapform')
main.visible=.t.

main.addobject('map','mymap','mapwingis.map.1')

DEFINE CLASS mapform AS form

     Top = 0
     Left = 0
     Height = 372
     Width = 409
     DoCreate = .T.
     Caption = "Form1"
     Name = "mapform"

     PROCEDURE destroy
         CLEAR EVENTS
     ENDPROC

ENDDEFINE

DEFINE CLASS mymap as olecontrol

     height = 372
     width = 409
     visible=.t.

     PROCEDURE Init
         LPARAMETERS null
         this.sendmousedown=.t.
     endproc

     PROCEDURE MouseDown
         LPARAMETERS button, shift, x, y
         =MESSAGEBOX('Mouse down fired.')
     ENDPROC

ENDDEFINE

However when the code below is run, the mouse _up_ event fires on both 
left and right mouse button release.

PUBLIC main
main=CREATEOBJECT('mapform')
main.visible=.t.

main.addobject('map','mymap','mapwingis.map.1')

DEFINE CLASS mapform AS form

     Top = 0
     Left = 0
     Height = 372
     Width = 409
     DoCreate = .T.
     Caption = "Form1"
     Name = "mapform"

     PROCEDURE destroy
         CLEAR EVENTS
     ENDPROC

ENDDEFINE

DEFINE CLASS mymap as olecontrol

     height = 372
     width = 409
     visible=.t.

     PROCEDURE Init
         LPARAMETERS null
         this.sendmouseup=.t.
     endproc

     PROCEDURE MouseUp
         LPARAMETERS button, shift, x, y
         =MESSAGEBOX('Mouse up fired.')
     ENDPROC

ENDDEFINE

**Comment by timkolesa** [comment]
Looking at the source code, the mousedown is only passed down when cursormode=4 (cmnone).

src/Control/Map_Events.cpp 

// ************************************************************
//		OnLButtonDown
// ************************************************************
void CMapView::OnLButtonDown(UINT nFlags, CPoint point)
{
	if (HasRotation()) {
		_rotate->getOriginalPixelPoint(point.x, point.y, &(point.x), &(point.y));
	}
.
.
.
.	
	default: //if( m_cursorMode == cmNone )
		{
			SetCapture();
			if( m_sendMouseDown == TRUE )
				this->FireMouseDown(MK_LBUTTON, (short)vbflags, x, y);
		}
		break;
	}
}

Therefore this works with the cursormode set to 4 but that does not allow me to trap a mouse click when the cursormode is set to zoomin which is what I need to do. Any ideas?

PUBLIC main 
main=CREATEOBJECT('mapform') 
main.visible=.t. 
main.addobject('map','mymap','mapwingis.map.1') 

DEFINE CLASS mapform AS form 
Top = 0 
Left = 0 
Height = 372 
Width = 409 
DoCreate = .T. 
Caption = "Form1" 
Name = "mapform" 

PROCEDURE destroy 
CLEAR EVENTS 
ENDPROC 

ENDDEFINE 

DEFINE CLASS mymap as olecontrol 
height = 372 
width = 409 
visible=.t. 

PROCEDURE Init 
LPARAMETERS null 
this.sendmousedown=.t. 
this.cursormode=4 && <-------------   added line to make mousedown work
endproc 

PROCEDURE MouseDown 
LPARAMETERS button, shift, x, y 
=MESSAGEBOX('Mouse down fired.') 
ENDPROC 

ENDDEFINE

**Comment by pmeems** [comment]
Perhaps it is easier for us if you tell what you want to accomplish.
I don't think anybody here still knows how to read VisualFoxPro code ;)

When you set the cursormode to tkCursorMode.cmZoomIn the shape should be selected.

**Comment by timkolesa** [comment]
Thanks. 

Basically I needed to trap the mousedown event when in zoom in mode to perform some functions after the user zoomed in by left clicking. I've changed my programmatic flow so this is no longer necessary.

BUT

Maybe it should be said in the documentation that sendmousedown function only occurs when the cursormode == cmnone

AND

VFP isn't that old! :)

**Comment by manuel76413** [comment]
the mouse event design could be better.
a good designation should be whenever the user needs to receive mouse down or up events,  he can get it.
however in this version MapWinGIS， only in 
		this.axMap1.CursorMode = MapWinGIS.tkCursorMode.cmPan;
So, if the user needs to deal with things in mouse down or up, how can he do?

**Comment by pmeems** [comment]
If you look at the documentation of [MouseDownEvent](https://www.mapwindow.org/documentation/mapwingis4.9/group__map__events.html#ga73bb10449981208214063f48cc06fe03) you'll see you need to set [SendMouseDown](https://www.mapwindow.org/documentation/mapwingis4.9/group__map__interaction.html#gabdd3a82d13432eef94d063439ea3de91) to true first.

And if you have suggestions to improve MapWinGIS you can make a Pull Request and we will add it.
