### ISSUE TITLE
Measuring: bugs

### ISSUE THREAD

**Issue by ultraTCS** [MapWindow/MapWinGIS#90]
See attached patch for some bugs in this file wrt return values.
[Measuring.cpp.txt](https://github.com/MapWindow/MapWinGIS/files/1929568/Measuring.cpp.txt)

**Comment by pmeems** [comment]
Thanks for the patch. We will try to merge it soon.
It seems you know what you are doing. I could give you GIT Commit rights so you can make the changes directly.  Please send me a mail if you are interested: bontepaarden(AT)gmail(D0T)com.

@jerryfaust: Would you be so kind to look at the patch and merge it. Please do make a JIRA issue for tracking.

**Comment by pmeems** [comment]
@jerryfaust Did we even merged these changes? 
And do we have a JIRA issue? I can't find it.

**Comment by jerryfaust** [comment]
Specified changes (plus a few) have now been integrated.  Done, assigned to [MWGIS-158](https://mapwindow.atlassian.net/browse/MWGIS-158);

**Comment by jerryfaust** [comment]
Closing this issue.
