### ISSUE TITLE
Measurement Tool Bearing

### ISSUE THREAD

**Issue by ultraTCS** [MapWindow/MapWinGIS#92]
Hi,

It appears that the Measurement Tool does distance and area calculations correctly based on ellipsoid; however the bearing is calculated using simple geometry.

The GeographicLib API that is used (`Geodesic::Inverse(...)`) has an override that returns the correct angle (azimuth). `CUtils::GeodesicDistance(...)` should be updated to correct this.

**Comment by pmeems** [comment]
I'm sorry I completely forgot to follow up on this issue.

Can you explain a bit more what needs to be changed?
Or even better create a pull request (against the dev-branch)?

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWinGIS/releases) could you create a new issue?
For now, I close this old issue.
