### ISSUE TITLE
Shape Incompatible with the Shapefile Type

### ISSUE THREAD

**Issue by HollidayHT** [MapWindow/MapWinGIS#93]
I am trying to clip a shape in a polygon shapefile, the clipping operation leaves a 2 part polygon as is expected, however when I attempt to update the original shape with the clipped shape I get an error 213 
"shape type is incompatible with the shapefile type". Exporting the shape to a WKT i can see the original shape was a polygon
POLYGON ((-10929096.5230755 4123271.91322619,-10929175.1284508 4123271.74004734,

and the clipped shape is a Multipolygon
MULTIPOLYGON (((-10929200.5261364 4123271.694416,-10929302.2190845 4123271.51170698,

The code is pretty simple

        pShp = sf.Shape(iP).Clip(cShp, tkClipOperation.clDifference)
        sf.Shape(iP).CopyFrom(pShp)

Do I have to create the shapefile a certain way to support MULTIPOLYGON shapes or is there a way to change an existing shapes type. It seems I can delete the original shape and add the clipped one to the shapefile but that causes other issues for the application.

**Comment by pmeems** [comment]
Most likely sf is set-up as a polygon. You're adding a multipolygon which results in the error.

You could try to convert the multipolygon to a polygon with multiple parts using shape.Explode():
https://www.mapwindow.org/documentation/mapwingis4.9/class_shape.html#ab185535d603a4edff898295267cbf5db

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
