### ISSUE TITLE
Change measuring unit to custom format during run-time.

### ISSUE THREAD

**Issue by imjoerock** [MapWindow/MapWinGIS#95]
Dear Paul, I would like to change measured area format to my custom format (as image , https://imgur.com/a/ydHqqwo ). I searched around forum but not found the relate answer, I really no idea for now. Could you pls advice on this?, thanks.

**Comment by imjoerock** [comment]
Hi, any advice. thanks.

**Comment by jerryfaust** [comment]
At this point, there is no way to modify the display units without modifying the library.  The unit types are restricted to the enumerations, and the screen rendering is done down in private methods, so there is no way to 'override' the current behavior.  You would have to modify the library itself, adding enumerations (for both Area and Length units) and modifying the screen drawing code accordingly.

**Comment by imjoerock** [comment]
Dear Jerry, Thanks.

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
