### ISSUE TITLE
select point by click mouse

### ISSUE THREAD

**Issue by imjoerock** [MapWindow/MapWinGIS#96]
Dear all, Could someone advice  me how to make selection by clicking on point, as shown image (https://ibb.co/mM7zoy). I look around for several days but not so luck. So tired for now...:<

**Comment by jerryfaust** [comment]
I presume you've seen [this example](https://www.mapwindow.org/documentation/mapwingis4.9/_select_box_8cs-example.html), which uses a drag-selection box to select.

Following is a function I have used (written in VB.NET) that I have tweaked a little for your purposes.  It takes the mouse point (in screen units) to find a feature in a specified layer, within a certain tolerance, and 'highlight' the feature in a specified color.  It can identify a point, line, or polygon feature.  Note that you will have to manage the de-selection of the feature.

```
Private Function GetContainingShape(ByVal layerHandle As Integer, ByVal x As Integer, ByVal y As Integer) As Integer
    Dim shapeIndex As Integer = -1
    ' get specified layer
    Dim layer As Shapefile = AxMap1.get_Shapefile(layerHandle)
    If layer IsNot Nothing Then
        Dim projX, projY, pixWidth, pixHeight As Double
        AxMap1.PixelToProj(x, y, projX, projY)

        ' determine pixel width
        AxMap1.PixelToProj(x + 1, y, pixWidth, pixHeight)
        pixWidth = Math.Abs(pixWidth - projX)

        ' create point to check containment
        Dim ext As New Extents
        ext.SetBounds(projX, projY, 0, projX, projY, 0)

        ' return list of features
        Dim results As Object
        ' set default values for all line and point intersection
        ' algorithm for 'tolerance' aims for 1/2 of the icon width (16 pixels),
        ' but tries not to exceed 10 meters when zoomed in, or 2 pixels when zoomed out
        Dim tolerance As Double = Math.Min(16 * pixWidth, Math.Max(10, 2 * pixWidth))
        Dim mode As SelectMode = SelectMode.INTERSECTION
        ' make exception for Polygon types
        Select Case layer.ShapefileType2D
            Case ShpfileType.SHP_POLYGON
                ' polygons use no tolerance so that cursor has to be inside poly
                tolerance = 0.0
        End Select

        ' set selection properties (this should really be done at the module-level)
        layer.SelectionAppearance = tkSelectionAppearance.saSelectionColor
        layer.SelectionColor = _utils.ColorByName(tkMapColor.Cyan)

        ' get intersecting shapes
        If layer.SelectShapes(ext, tolerance, mode, results) Then
            Dim shapeIndices() As Integer = TryCast(results, Integer())
            If shapeIndices IsNot Nothing AndAlso shapeIndices.Count > 0 Then
                ' return first shape
                shapeIndex = shapeIndices(0)

                ' the following line causes the shape to 'highlighted' in the Selection Color;
                ' set back to False to de-select the feature
                layer.ShapeSelected(shapeIndex) = True
            End If
        End If
    End If
    Return shapeIndex
End Function

```

**Comment by imjoerock** [comment]
Dear Jerry, Thanks for reply and example. Btw, drag selection is work perfectly but I need clicking on point selection instead. My concern is, I need to draw polygon by click on interested points, which some I need and some I don't. So I can not use drag action to select only points I need.

**Comment by pmeems** [comment]
Did you have a look at this example:
https://www.mapwindow.org/documentation/mapwingis4.9/_remove_shape_8cs-example.html
It is also using SelectShapes but with INCLUSION.
It should work by just clicking on the shape (point, line, polygon).

**Comment by pmeems** [comment]
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)
