### ISSUE TITLE
Projected to WGS_84

### ISSUE THREAD

**Issue by joe-go12** [MapWindow/MapWinGIS#99]
dear paul,
how to add a projected utm  image when the map has a geographic GeoProjection??

thank you

**Comment by joe-go12** [comment]
the question is that how to assign a projection to an image that i created, so i can put it where ever i want on map according to coordinates that i give.

**Comment by pmeems** [comment]
You need to reproject the image first to the projection of the map.
When you set GlobalSettings.ReprojectLayersOnAdding: https://www.mapwindow.org/documentation/mapwingis4.9/class_global_settings.html#a3b13db883be4cef7fd2f04fc0e7ccf7f the reprojection should go automatically.

You can also manually reproject (warp) the image before adding using GdalUtils.GDALWarp: https://www.mapwindow.org/documentation/mapwingis4.9/class_gdal_utils.html#a7181b1e9a14adb676c68e00b3cd90c1c

**Comment by GISSALL** [comment]
hello Paul,
thank you for your response.
this can be done if the image has a projection,but my problem is that my image does not have any projection.
if i want to put my image, that has NO projection, for example on coordinates 56.1304° N, 106.3468° W, how it can be done ?

**Comment by joe-go12** [comment]
Hello Paul,
Thank you for your response.
This can be done if my image already has a projection so i can Reproject it.
But the problem is that the image does not have any projection.
if i want to put the image, that has NO projection, on coordinates 56.1304° N, 106.3468° W, how it can be done , knowing that my map projection is Geographic, WGS84?

**Comment by pmeems** [comment]
What kind of image is it? jpg and png have no way to store coordinates. Then you need to create a aux.xml file to hold that data.
Tiff files do have options to store the coordinates. Then you only need to create the prj file.

How was the image created? Can't you add the projection at that moment?
In MapWindow5 you can use the _image registration_ plug-in to manually click the same locations on the map and on the image.

**Comment by joe-go12** [comment]
I Created a Grid.Then i Used Utils.GridToImage to create the Image from the Grid.so the kind of image is MApWinGIS.Image. I want to put this Image.
The Grid And The Image has no projection.
I gave the XllCenter and YllCenter coordinates.
then i gave the Image a Projection Like the projection of the MapControl.
the i added the image to the MapControl using MapControl.AddLayer().

but this way is wrong.
